// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package getusers

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/nskondratev/socks5-proxy-server/proxy/internal/bot/store"
)

// UsersStoreMock implements usersStore
type UsersStoreMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSetUserState          func(ctx context.Context, username string, state store.UserState) (err error)
	funcSetUserStateOrigin    string
	inspectFuncSetUserState   func(ctx context.Context, username string, state store.UserState)
	afterSetUserStateCounter  uint64
	beforeSetUserStateCounter uint64
	SetUserStateMock          mUsersStoreMockSetUserState
}

// NewUsersStoreMock returns a mock for usersStore
func NewUsersStoreMock(t minimock.Tester) *UsersStoreMock {
	m := &UsersStoreMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SetUserStateMock = mUsersStoreMockSetUserState{mock: m}
	m.SetUserStateMock.callArgs = []*UsersStoreMockSetUserStateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUsersStoreMockSetUserState struct {
	optional           bool
	mock               *UsersStoreMock
	defaultExpectation *UsersStoreMockSetUserStateExpectation
	expectations       []*UsersStoreMockSetUserStateExpectation

	callArgs []*UsersStoreMockSetUserStateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UsersStoreMockSetUserStateExpectation specifies expectation struct of the usersStore.SetUserState
type UsersStoreMockSetUserStateExpectation struct {
	mock               *UsersStoreMock
	params             *UsersStoreMockSetUserStateParams
	paramPtrs          *UsersStoreMockSetUserStateParamPtrs
	expectationOrigins UsersStoreMockSetUserStateExpectationOrigins
	results            *UsersStoreMockSetUserStateResults
	returnOrigin       string
	Counter            uint64
}

// UsersStoreMockSetUserStateParams contains parameters of the usersStore.SetUserState
type UsersStoreMockSetUserStateParams struct {
	ctx      context.Context
	username string
	state    store.UserState
}

// UsersStoreMockSetUserStateParamPtrs contains pointers to parameters of the usersStore.SetUserState
type UsersStoreMockSetUserStateParamPtrs struct {
	ctx      *context.Context
	username *string
	state    *store.UserState
}

// UsersStoreMockSetUserStateResults contains results of the usersStore.SetUserState
type UsersStoreMockSetUserStateResults struct {
	err error
}

// UsersStoreMockSetUserStateOrigins contains origins of expectations of the usersStore.SetUserState
type UsersStoreMockSetUserStateExpectationOrigins struct {
	origin         string
	originCtx      string
	originUsername string
	originState    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSetUserState *mUsersStoreMockSetUserState) Optional() *mUsersStoreMockSetUserState {
	mmSetUserState.optional = true
	return mmSetUserState
}

// Expect sets up expected params for usersStore.SetUserState
func (mmSetUserState *mUsersStoreMockSetUserState) Expect(ctx context.Context, username string, state store.UserState) *mUsersStoreMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("UsersStoreMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &UsersStoreMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.paramPtrs != nil {
		mmSetUserState.mock.t.Fatalf("UsersStoreMock.SetUserState mock is already set by ExpectParams functions")
	}

	mmSetUserState.defaultExpectation.params = &UsersStoreMockSetUserStateParams{ctx, username, state}
	mmSetUserState.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSetUserState.expectations {
		if minimock.Equal(e.params, mmSetUserState.defaultExpectation.params) {
			mmSetUserState.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSetUserState.defaultExpectation.params)
		}
	}

	return mmSetUserState
}

// ExpectCtxParam1 sets up expected param ctx for usersStore.SetUserState
func (mmSetUserState *mUsersStoreMockSetUserState) ExpectCtxParam1(ctx context.Context) *mUsersStoreMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("UsersStoreMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &UsersStoreMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.params != nil {
		mmSetUserState.mock.t.Fatalf("UsersStoreMock.SetUserState mock is already set by Expect")
	}

	if mmSetUserState.defaultExpectation.paramPtrs == nil {
		mmSetUserState.defaultExpectation.paramPtrs = &UsersStoreMockSetUserStateParamPtrs{}
	}
	mmSetUserState.defaultExpectation.paramPtrs.ctx = &ctx
	mmSetUserState.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSetUserState
}

// ExpectUsernameParam2 sets up expected param username for usersStore.SetUserState
func (mmSetUserState *mUsersStoreMockSetUserState) ExpectUsernameParam2(username string) *mUsersStoreMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("UsersStoreMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &UsersStoreMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.params != nil {
		mmSetUserState.mock.t.Fatalf("UsersStoreMock.SetUserState mock is already set by Expect")
	}

	if mmSetUserState.defaultExpectation.paramPtrs == nil {
		mmSetUserState.defaultExpectation.paramPtrs = &UsersStoreMockSetUserStateParamPtrs{}
	}
	mmSetUserState.defaultExpectation.paramPtrs.username = &username
	mmSetUserState.defaultExpectation.expectationOrigins.originUsername = minimock.CallerInfo(1)

	return mmSetUserState
}

// ExpectStateParam3 sets up expected param state for usersStore.SetUserState
func (mmSetUserState *mUsersStoreMockSetUserState) ExpectStateParam3(state store.UserState) *mUsersStoreMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("UsersStoreMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &UsersStoreMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.params != nil {
		mmSetUserState.mock.t.Fatalf("UsersStoreMock.SetUserState mock is already set by Expect")
	}

	if mmSetUserState.defaultExpectation.paramPtrs == nil {
		mmSetUserState.defaultExpectation.paramPtrs = &UsersStoreMockSetUserStateParamPtrs{}
	}
	mmSetUserState.defaultExpectation.paramPtrs.state = &state
	mmSetUserState.defaultExpectation.expectationOrigins.originState = minimock.CallerInfo(1)

	return mmSetUserState
}

// Inspect accepts an inspector function that has same arguments as the usersStore.SetUserState
func (mmSetUserState *mUsersStoreMockSetUserState) Inspect(f func(ctx context.Context, username string, state store.UserState)) *mUsersStoreMockSetUserState {
	if mmSetUserState.mock.inspectFuncSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("Inspect function is already set for UsersStoreMock.SetUserState")
	}

	mmSetUserState.mock.inspectFuncSetUserState = f

	return mmSetUserState
}

// Return sets up results that will be returned by usersStore.SetUserState
func (mmSetUserState *mUsersStoreMockSetUserState) Return(err error) *UsersStoreMock {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("UsersStoreMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &UsersStoreMockSetUserStateExpectation{mock: mmSetUserState.mock}
	}
	mmSetUserState.defaultExpectation.results = &UsersStoreMockSetUserStateResults{err}
	mmSetUserState.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSetUserState.mock
}

// Set uses given function f to mock the usersStore.SetUserState method
func (mmSetUserState *mUsersStoreMockSetUserState) Set(f func(ctx context.Context, username string, state store.UserState) (err error)) *UsersStoreMock {
	if mmSetUserState.defaultExpectation != nil {
		mmSetUserState.mock.t.Fatalf("Default expectation is already set for the usersStore.SetUserState method")
	}

	if len(mmSetUserState.expectations) > 0 {
		mmSetUserState.mock.t.Fatalf("Some expectations are already set for the usersStore.SetUserState method")
	}

	mmSetUserState.mock.funcSetUserState = f
	mmSetUserState.mock.funcSetUserStateOrigin = minimock.CallerInfo(1)
	return mmSetUserState.mock
}

// When sets expectation for the usersStore.SetUserState which will trigger the result defined by the following
// Then helper
func (mmSetUserState *mUsersStoreMockSetUserState) When(ctx context.Context, username string, state store.UserState) *UsersStoreMockSetUserStateExpectation {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("UsersStoreMock.SetUserState mock is already set by Set")
	}

	expectation := &UsersStoreMockSetUserStateExpectation{
		mock:               mmSetUserState.mock,
		params:             &UsersStoreMockSetUserStateParams{ctx, username, state},
		expectationOrigins: UsersStoreMockSetUserStateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSetUserState.expectations = append(mmSetUserState.expectations, expectation)
	return expectation
}

// Then sets up usersStore.SetUserState return parameters for the expectation previously defined by the When method
func (e *UsersStoreMockSetUserStateExpectation) Then(err error) *UsersStoreMock {
	e.results = &UsersStoreMockSetUserStateResults{err}
	return e.mock
}

// Times sets number of times usersStore.SetUserState should be invoked
func (mmSetUserState *mUsersStoreMockSetUserState) Times(n uint64) *mUsersStoreMockSetUserState {
	if n == 0 {
		mmSetUserState.mock.t.Fatalf("Times of UsersStoreMock.SetUserState mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSetUserState.expectedInvocations, n)
	mmSetUserState.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSetUserState
}

func (mmSetUserState *mUsersStoreMockSetUserState) invocationsDone() bool {
	if len(mmSetUserState.expectations) == 0 && mmSetUserState.defaultExpectation == nil && mmSetUserState.mock.funcSetUserState == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSetUserState.mock.afterSetUserStateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSetUserState.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SetUserState implements usersStore
func (mmSetUserState *UsersStoreMock) SetUserState(ctx context.Context, username string, state store.UserState) (err error) {
	mm_atomic.AddUint64(&mmSetUserState.beforeSetUserStateCounter, 1)
	defer mm_atomic.AddUint64(&mmSetUserState.afterSetUserStateCounter, 1)

	mmSetUserState.t.Helper()

	if mmSetUserState.inspectFuncSetUserState != nil {
		mmSetUserState.inspectFuncSetUserState(ctx, username, state)
	}

	mm_params := UsersStoreMockSetUserStateParams{ctx, username, state}

	// Record call args
	mmSetUserState.SetUserStateMock.mutex.Lock()
	mmSetUserState.SetUserStateMock.callArgs = append(mmSetUserState.SetUserStateMock.callArgs, &mm_params)
	mmSetUserState.SetUserStateMock.mutex.Unlock()

	for _, e := range mmSetUserState.SetUserStateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSetUserState.SetUserStateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSetUserState.SetUserStateMock.defaultExpectation.Counter, 1)
		mm_want := mmSetUserState.SetUserStateMock.defaultExpectation.params
		mm_want_ptrs := mmSetUserState.SetUserStateMock.defaultExpectation.paramPtrs

		mm_got := UsersStoreMockSetUserStateParams{ctx, username, state}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSetUserState.t.Errorf("UsersStoreMock.SetUserState got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.username != nil && !minimock.Equal(*mm_want_ptrs.username, mm_got.username) {
				mmSetUserState.t.Errorf("UsersStoreMock.SetUserState got unexpected parameter username, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.originUsername, *mm_want_ptrs.username, mm_got.username, minimock.Diff(*mm_want_ptrs.username, mm_got.username))
			}

			if mm_want_ptrs.state != nil && !minimock.Equal(*mm_want_ptrs.state, mm_got.state) {
				mmSetUserState.t.Errorf("UsersStoreMock.SetUserState got unexpected parameter state, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.originState, *mm_want_ptrs.state, mm_got.state, minimock.Diff(*mm_want_ptrs.state, mm_got.state))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSetUserState.t.Errorf("UsersStoreMock.SetUserState got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSetUserState.SetUserStateMock.defaultExpectation.results
		if mm_results == nil {
			mmSetUserState.t.Fatal("No results are set for the UsersStoreMock.SetUserState")
		}
		return (*mm_results).err
	}
	if mmSetUserState.funcSetUserState != nil {
		return mmSetUserState.funcSetUserState(ctx, username, state)
	}
	mmSetUserState.t.Fatalf("Unexpected call to UsersStoreMock.SetUserState. %v %v %v", ctx, username, state)
	return
}

// SetUserStateAfterCounter returns a count of finished UsersStoreMock.SetUserState invocations
func (mmSetUserState *UsersStoreMock) SetUserStateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetUserState.afterSetUserStateCounter)
}

// SetUserStateBeforeCounter returns a count of UsersStoreMock.SetUserState invocations
func (mmSetUserState *UsersStoreMock) SetUserStateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetUserState.beforeSetUserStateCounter)
}

// Calls returns a list of arguments used in each call to UsersStoreMock.SetUserState.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSetUserState *mUsersStoreMockSetUserState) Calls() []*UsersStoreMockSetUserStateParams {
	mmSetUserState.mutex.RLock()

	argCopy := make([]*UsersStoreMockSetUserStateParams, len(mmSetUserState.callArgs))
	copy(argCopy, mmSetUserState.callArgs)

	mmSetUserState.mutex.RUnlock()

	return argCopy
}

// MinimockSetUserStateDone returns true if the count of the SetUserState invocations corresponds
// the number of defined expectations
func (m *UsersStoreMock) MinimockSetUserStateDone() bool {
	if m.SetUserStateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SetUserStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SetUserStateMock.invocationsDone()
}

// MinimockSetUserStateInspect logs each unmet expectation
func (m *UsersStoreMock) MinimockSetUserStateInspect() {
	for _, e := range m.SetUserStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UsersStoreMock.SetUserState at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSetUserStateCounter := mm_atomic.LoadUint64(&m.afterSetUserStateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SetUserStateMock.defaultExpectation != nil && afterSetUserStateCounter < 1 {
		if m.SetUserStateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UsersStoreMock.SetUserState at\n%s", m.SetUserStateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UsersStoreMock.SetUserState at\n%s with params: %#v", m.SetUserStateMock.defaultExpectation.expectationOrigins.origin, *m.SetUserStateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSetUserState != nil && afterSetUserStateCounter < 1 {
		m.t.Errorf("Expected call to UsersStoreMock.SetUserState at\n%s", m.funcSetUserStateOrigin)
	}

	if !m.SetUserStateMock.invocationsDone() && afterSetUserStateCounter > 0 {
		m.t.Errorf("Expected %d calls to UsersStoreMock.SetUserState at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SetUserStateMock.expectedInvocations), m.SetUserStateMock.expectedInvocationsOrigin, afterSetUserStateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UsersStoreMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSetUserStateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UsersStoreMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UsersStoreMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSetUserStateDone()
}
