// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package proxy

//go:generate minimock -i github.com/nskondratev/socks5-proxy-server/proxy/internal/adapters/proxy.cache -o cache_mock_test.go -n CacheMock -p proxy

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// CacheMock implements cache
type CacheMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAdd          func(key AuthCacheKey, value bool)
	funcAddOrigin    string
	inspectFuncAdd   func(key AuthCacheKey, value bool)
	afterAddCounter  uint64
	beforeAddCounter uint64
	AddMock          mCacheMockAdd

	funcGet          func(key AuthCacheKey) (value bool, exists bool)
	funcGetOrigin    string
	inspectFuncGet   func(key AuthCacheKey)
	afterGetCounter  uint64
	beforeGetCounter uint64
	GetMock          mCacheMockGet
}

// NewCacheMock returns a mock for cache
func NewCacheMock(t minimock.Tester) *CacheMock {
	m := &CacheMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddMock = mCacheMockAdd{mock: m}
	m.AddMock.callArgs = []*CacheMockAddParams{}

	m.GetMock = mCacheMockGet{mock: m}
	m.GetMock.callArgs = []*CacheMockGetParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mCacheMockAdd struct {
	optional           bool
	mock               *CacheMock
	defaultExpectation *CacheMockAddExpectation
	expectations       []*CacheMockAddExpectation

	callArgs []*CacheMockAddParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CacheMockAddExpectation specifies expectation struct of the cache.Add
type CacheMockAddExpectation struct {
	mock               *CacheMock
	params             *CacheMockAddParams
	paramPtrs          *CacheMockAddParamPtrs
	expectationOrigins CacheMockAddExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// CacheMockAddParams contains parameters of the cache.Add
type CacheMockAddParams struct {
	key   AuthCacheKey
	value bool
}

// CacheMockAddParamPtrs contains pointers to parameters of the cache.Add
type CacheMockAddParamPtrs struct {
	key   *AuthCacheKey
	value *bool
}

// CacheMockAddOrigins contains origins of expectations of the cache.Add
type CacheMockAddExpectationOrigins struct {
	origin      string
	originKey   string
	originValue string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAdd *mCacheMockAdd) Optional() *mCacheMockAdd {
	mmAdd.optional = true
	return mmAdd
}

// Expect sets up expected params for cache.Add
func (mmAdd *mCacheMockAdd) Expect(key AuthCacheKey, value bool) *mCacheMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("CacheMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &CacheMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.paramPtrs != nil {
		mmAdd.mock.t.Fatalf("CacheMock.Add mock is already set by ExpectParams functions")
	}

	mmAdd.defaultExpectation.params = &CacheMockAddParams{key, value}
	mmAdd.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAdd.expectations {
		if minimock.Equal(e.params, mmAdd.defaultExpectation.params) {
			mmAdd.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAdd.defaultExpectation.params)
		}
	}

	return mmAdd
}

// ExpectKeyParam1 sets up expected param key for cache.Add
func (mmAdd *mCacheMockAdd) ExpectKeyParam1(key AuthCacheKey) *mCacheMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("CacheMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &CacheMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.params != nil {
		mmAdd.mock.t.Fatalf("CacheMock.Add mock is already set by Expect")
	}

	if mmAdd.defaultExpectation.paramPtrs == nil {
		mmAdd.defaultExpectation.paramPtrs = &CacheMockAddParamPtrs{}
	}
	mmAdd.defaultExpectation.paramPtrs.key = &key
	mmAdd.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmAdd
}

// ExpectValueParam2 sets up expected param value for cache.Add
func (mmAdd *mCacheMockAdd) ExpectValueParam2(value bool) *mCacheMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("CacheMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &CacheMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.params != nil {
		mmAdd.mock.t.Fatalf("CacheMock.Add mock is already set by Expect")
	}

	if mmAdd.defaultExpectation.paramPtrs == nil {
		mmAdd.defaultExpectation.paramPtrs = &CacheMockAddParamPtrs{}
	}
	mmAdd.defaultExpectation.paramPtrs.value = &value
	mmAdd.defaultExpectation.expectationOrigins.originValue = minimock.CallerInfo(1)

	return mmAdd
}

// Inspect accepts an inspector function that has same arguments as the cache.Add
func (mmAdd *mCacheMockAdd) Inspect(f func(key AuthCacheKey, value bool)) *mCacheMockAdd {
	if mmAdd.mock.inspectFuncAdd != nil {
		mmAdd.mock.t.Fatalf("Inspect function is already set for CacheMock.Add")
	}

	mmAdd.mock.inspectFuncAdd = f

	return mmAdd
}

// Return sets up results that will be returned by cache.Add
func (mmAdd *mCacheMockAdd) Return() *CacheMock {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("CacheMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &CacheMockAddExpectation{mock: mmAdd.mock}
	}

	mmAdd.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAdd.mock
}

// Set uses given function f to mock the cache.Add method
func (mmAdd *mCacheMockAdd) Set(f func(key AuthCacheKey, value bool)) *CacheMock {
	if mmAdd.defaultExpectation != nil {
		mmAdd.mock.t.Fatalf("Default expectation is already set for the cache.Add method")
	}

	if len(mmAdd.expectations) > 0 {
		mmAdd.mock.t.Fatalf("Some expectations are already set for the cache.Add method")
	}

	mmAdd.mock.funcAdd = f
	mmAdd.mock.funcAddOrigin = minimock.CallerInfo(1)
	return mmAdd.mock
}

// When sets expectation for the cache.Add which will trigger the result defined by the following
// Then helper
func (mmAdd *mCacheMockAdd) When(key AuthCacheKey, value bool) *CacheMockAddExpectation {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("CacheMock.Add mock is already set by Set")
	}

	expectation := &CacheMockAddExpectation{
		mock:               mmAdd.mock,
		params:             &CacheMockAddParams{key, value},
		expectationOrigins: CacheMockAddExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAdd.expectations = append(mmAdd.expectations, expectation)
	return expectation
}

// Then sets up cache.Add return parameters for the expectation previously defined by the When method

func (e *CacheMockAddExpectation) Then() *CacheMock {
	return e.mock
}

// Times sets number of times cache.Add should be invoked
func (mmAdd *mCacheMockAdd) Times(n uint64) *mCacheMockAdd {
	if n == 0 {
		mmAdd.mock.t.Fatalf("Times of CacheMock.Add mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAdd.expectedInvocations, n)
	mmAdd.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAdd
}

func (mmAdd *mCacheMockAdd) invocationsDone() bool {
	if len(mmAdd.expectations) == 0 && mmAdd.defaultExpectation == nil && mmAdd.mock.funcAdd == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAdd.mock.afterAddCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAdd.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Add implements cache
func (mmAdd *CacheMock) Add(key AuthCacheKey, value bool) {
	mm_atomic.AddUint64(&mmAdd.beforeAddCounter, 1)
	defer mm_atomic.AddUint64(&mmAdd.afterAddCounter, 1)

	mmAdd.t.Helper()

	if mmAdd.inspectFuncAdd != nil {
		mmAdd.inspectFuncAdd(key, value)
	}

	mm_params := CacheMockAddParams{key, value}

	// Record call args
	mmAdd.AddMock.mutex.Lock()
	mmAdd.AddMock.callArgs = append(mmAdd.AddMock.callArgs, &mm_params)
	mmAdd.AddMock.mutex.Unlock()

	for _, e := range mmAdd.AddMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmAdd.AddMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAdd.AddMock.defaultExpectation.Counter, 1)
		mm_want := mmAdd.AddMock.defaultExpectation.params
		mm_want_ptrs := mmAdd.AddMock.defaultExpectation.paramPtrs

		mm_got := CacheMockAddParams{key, value}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmAdd.t.Errorf("CacheMock.Add got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAdd.AddMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

			if mm_want_ptrs.value != nil && !minimock.Equal(*mm_want_ptrs.value, mm_got.value) {
				mmAdd.t.Errorf("CacheMock.Add got unexpected parameter value, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAdd.AddMock.defaultExpectation.expectationOrigins.originValue, *mm_want_ptrs.value, mm_got.value, minimock.Diff(*mm_want_ptrs.value, mm_got.value))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAdd.t.Errorf("CacheMock.Add got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAdd.AddMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmAdd.funcAdd != nil {
		mmAdd.funcAdd(key, value)
		return
	}
	mmAdd.t.Fatalf("Unexpected call to CacheMock.Add. %v %v", key, value)

}

// AddAfterCounter returns a count of finished CacheMock.Add invocations
func (mmAdd *CacheMock) AddAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.afterAddCounter)
}

// AddBeforeCounter returns a count of CacheMock.Add invocations
func (mmAdd *CacheMock) AddBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.beforeAddCounter)
}

// Calls returns a list of arguments used in each call to CacheMock.Add.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAdd *mCacheMockAdd) Calls() []*CacheMockAddParams {
	mmAdd.mutex.RLock()

	argCopy := make([]*CacheMockAddParams, len(mmAdd.callArgs))
	copy(argCopy, mmAdd.callArgs)

	mmAdd.mutex.RUnlock()

	return argCopy
}

// MinimockAddDone returns true if the count of the Add invocations corresponds
// the number of defined expectations
func (m *CacheMock) MinimockAddDone() bool {
	if m.AddMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddMock.invocationsDone()
}

// MinimockAddInspect logs each unmet expectation
func (m *CacheMock) MinimockAddInspect() {
	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CacheMock.Add at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddCounter := mm_atomic.LoadUint64(&m.afterAddCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddMock.defaultExpectation != nil && afterAddCounter < 1 {
		if m.AddMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CacheMock.Add at\n%s", m.AddMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CacheMock.Add at\n%s with params: %#v", m.AddMock.defaultExpectation.expectationOrigins.origin, *m.AddMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAdd != nil && afterAddCounter < 1 {
		m.t.Errorf("Expected call to CacheMock.Add at\n%s", m.funcAddOrigin)
	}

	if !m.AddMock.invocationsDone() && afterAddCounter > 0 {
		m.t.Errorf("Expected %d calls to CacheMock.Add at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddMock.expectedInvocations), m.AddMock.expectedInvocationsOrigin, afterAddCounter)
	}
}

type mCacheMockGet struct {
	optional           bool
	mock               *CacheMock
	defaultExpectation *CacheMockGetExpectation
	expectations       []*CacheMockGetExpectation

	callArgs []*CacheMockGetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CacheMockGetExpectation specifies expectation struct of the cache.Get
type CacheMockGetExpectation struct {
	mock               *CacheMock
	params             *CacheMockGetParams
	paramPtrs          *CacheMockGetParamPtrs
	expectationOrigins CacheMockGetExpectationOrigins
	results            *CacheMockGetResults
	returnOrigin       string
	Counter            uint64
}

// CacheMockGetParams contains parameters of the cache.Get
type CacheMockGetParams struct {
	key AuthCacheKey
}

// CacheMockGetParamPtrs contains pointers to parameters of the cache.Get
type CacheMockGetParamPtrs struct {
	key *AuthCacheKey
}

// CacheMockGetResults contains results of the cache.Get
type CacheMockGetResults struct {
	value  bool
	exists bool
}

// CacheMockGetOrigins contains origins of expectations of the cache.Get
type CacheMockGetExpectationOrigins struct {
	origin    string
	originKey string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGet *mCacheMockGet) Optional() *mCacheMockGet {
	mmGet.optional = true
	return mmGet
}

// Expect sets up expected params for cache.Get
func (mmGet *mCacheMockGet) Expect(key AuthCacheKey) *mCacheMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("CacheMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &CacheMockGetExpectation{}
	}

	if mmGet.defaultExpectation.paramPtrs != nil {
		mmGet.mock.t.Fatalf("CacheMock.Get mock is already set by ExpectParams functions")
	}

	mmGet.defaultExpectation.params = &CacheMockGetParams{key}
	mmGet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGet.expectations {
		if minimock.Equal(e.params, mmGet.defaultExpectation.params) {
			mmGet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGet.defaultExpectation.params)
		}
	}

	return mmGet
}

// ExpectKeyParam1 sets up expected param key for cache.Get
func (mmGet *mCacheMockGet) ExpectKeyParam1(key AuthCacheKey) *mCacheMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("CacheMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &CacheMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("CacheMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &CacheMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.key = &key
	mmGet.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmGet
}

// Inspect accepts an inspector function that has same arguments as the cache.Get
func (mmGet *mCacheMockGet) Inspect(f func(key AuthCacheKey)) *mCacheMockGet {
	if mmGet.mock.inspectFuncGet != nil {
		mmGet.mock.t.Fatalf("Inspect function is already set for CacheMock.Get")
	}

	mmGet.mock.inspectFuncGet = f

	return mmGet
}

// Return sets up results that will be returned by cache.Get
func (mmGet *mCacheMockGet) Return(value bool, exists bool) *CacheMock {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("CacheMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &CacheMockGetExpectation{mock: mmGet.mock}
	}
	mmGet.defaultExpectation.results = &CacheMockGetResults{value, exists}
	mmGet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// Set uses given function f to mock the cache.Get method
func (mmGet *mCacheMockGet) Set(f func(key AuthCacheKey) (value bool, exists bool)) *CacheMock {
	if mmGet.defaultExpectation != nil {
		mmGet.mock.t.Fatalf("Default expectation is already set for the cache.Get method")
	}

	if len(mmGet.expectations) > 0 {
		mmGet.mock.t.Fatalf("Some expectations are already set for the cache.Get method")
	}

	mmGet.mock.funcGet = f
	mmGet.mock.funcGetOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// When sets expectation for the cache.Get which will trigger the result defined by the following
// Then helper
func (mmGet *mCacheMockGet) When(key AuthCacheKey) *CacheMockGetExpectation {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("CacheMock.Get mock is already set by Set")
	}

	expectation := &CacheMockGetExpectation{
		mock:               mmGet.mock,
		params:             &CacheMockGetParams{key},
		expectationOrigins: CacheMockGetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGet.expectations = append(mmGet.expectations, expectation)
	return expectation
}

// Then sets up cache.Get return parameters for the expectation previously defined by the When method
func (e *CacheMockGetExpectation) Then(value bool, exists bool) *CacheMock {
	e.results = &CacheMockGetResults{value, exists}
	return e.mock
}

// Times sets number of times cache.Get should be invoked
func (mmGet *mCacheMockGet) Times(n uint64) *mCacheMockGet {
	if n == 0 {
		mmGet.mock.t.Fatalf("Times of CacheMock.Get mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGet.expectedInvocations, n)
	mmGet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGet
}

func (mmGet *mCacheMockGet) invocationsDone() bool {
	if len(mmGet.expectations) == 0 && mmGet.defaultExpectation == nil && mmGet.mock.funcGet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGet.mock.afterGetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Get implements cache
func (mmGet *CacheMock) Get(key AuthCacheKey) (value bool, exists bool) {
	mm_atomic.AddUint64(&mmGet.beforeGetCounter, 1)
	defer mm_atomic.AddUint64(&mmGet.afterGetCounter, 1)

	mmGet.t.Helper()

	if mmGet.inspectFuncGet != nil {
		mmGet.inspectFuncGet(key)
	}

	mm_params := CacheMockGetParams{key}

	// Record call args
	mmGet.GetMock.mutex.Lock()
	mmGet.GetMock.callArgs = append(mmGet.GetMock.callArgs, &mm_params)
	mmGet.GetMock.mutex.Unlock()

	for _, e := range mmGet.GetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.value, e.results.exists
		}
	}

	if mmGet.GetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGet.GetMock.defaultExpectation.Counter, 1)
		mm_want := mmGet.GetMock.defaultExpectation.params
		mm_want_ptrs := mmGet.GetMock.defaultExpectation.paramPtrs

		mm_got := CacheMockGetParams{key}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmGet.t.Errorf("CacheMock.Get got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGet.t.Errorf("CacheMock.Get got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGet.GetMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGet.GetMock.defaultExpectation.results
		if mm_results == nil {
			mmGet.t.Fatal("No results are set for the CacheMock.Get")
		}
		return (*mm_results).value, (*mm_results).exists
	}
	if mmGet.funcGet != nil {
		return mmGet.funcGet(key)
	}
	mmGet.t.Fatalf("Unexpected call to CacheMock.Get. %v", key)
	return
}

// GetAfterCounter returns a count of finished CacheMock.Get invocations
func (mmGet *CacheMock) GetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.afterGetCounter)
}

// GetBeforeCounter returns a count of CacheMock.Get invocations
func (mmGet *CacheMock) GetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.beforeGetCounter)
}

// Calls returns a list of arguments used in each call to CacheMock.Get.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGet *mCacheMockGet) Calls() []*CacheMockGetParams {
	mmGet.mutex.RLock()

	argCopy := make([]*CacheMockGetParams, len(mmGet.callArgs))
	copy(argCopy, mmGet.callArgs)

	mmGet.mutex.RUnlock()

	return argCopy
}

// MinimockGetDone returns true if the count of the Get invocations corresponds
// the number of defined expectations
func (m *CacheMock) MinimockGetDone() bool {
	if m.GetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetMock.invocationsDone()
}

// MinimockGetInspect logs each unmet expectation
func (m *CacheMock) MinimockGetInspect() {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CacheMock.Get at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetCounter := mm_atomic.LoadUint64(&m.afterGetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && afterGetCounter < 1 {
		if m.GetMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CacheMock.Get at\n%s", m.GetMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CacheMock.Get at\n%s with params: %#v", m.GetMock.defaultExpectation.expectationOrigins.origin, *m.GetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && afterGetCounter < 1 {
		m.t.Errorf("Expected call to CacheMock.Get at\n%s", m.funcGetOrigin)
	}

	if !m.GetMock.invocationsDone() && afterGetCounter > 0 {
		m.t.Errorf("Expected %d calls to CacheMock.Get at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetMock.expectedInvocations), m.GetMock.expectedInvocationsOrigin, afterGetCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *CacheMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddInspect()

			m.MinimockGetInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *CacheMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *CacheMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddDone() &&
		m.MinimockGetDone()
}
