// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package proxy

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// PasswordHashGetterMock implements passwordHashGetter
type PasswordHashGetterMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetPasswordHash          func(ctx context.Context, userName string) (s1 string, err error)
	funcGetPasswordHashOrigin    string
	inspectFuncGetPasswordHash   func(ctx context.Context, userName string)
	afterGetPasswordHashCounter  uint64
	beforeGetPasswordHashCounter uint64
	GetPasswordHashMock          mPasswordHashGetterMockGetPasswordHash
}

// NewPasswordHashGetterMock returns a mock for passwordHashGetter
func NewPasswordHashGetterMock(t minimock.Tester) *PasswordHashGetterMock {
	m := &PasswordHashGetterMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetPasswordHashMock = mPasswordHashGetterMockGetPasswordHash{mock: m}
	m.GetPasswordHashMock.callArgs = []*PasswordHashGetterMockGetPasswordHashParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mPasswordHashGetterMockGetPasswordHash struct {
	optional           bool
	mock               *PasswordHashGetterMock
	defaultExpectation *PasswordHashGetterMockGetPasswordHashExpectation
	expectations       []*PasswordHashGetterMockGetPasswordHashExpectation

	callArgs []*PasswordHashGetterMockGetPasswordHashParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PasswordHashGetterMockGetPasswordHashExpectation specifies expectation struct of the passwordHashGetter.GetPasswordHash
type PasswordHashGetterMockGetPasswordHashExpectation struct {
	mock               *PasswordHashGetterMock
	params             *PasswordHashGetterMockGetPasswordHashParams
	paramPtrs          *PasswordHashGetterMockGetPasswordHashParamPtrs
	expectationOrigins PasswordHashGetterMockGetPasswordHashExpectationOrigins
	results            *PasswordHashGetterMockGetPasswordHashResults
	returnOrigin       string
	Counter            uint64
}

// PasswordHashGetterMockGetPasswordHashParams contains parameters of the passwordHashGetter.GetPasswordHash
type PasswordHashGetterMockGetPasswordHashParams struct {
	ctx      context.Context
	userName string
}

// PasswordHashGetterMockGetPasswordHashParamPtrs contains pointers to parameters of the passwordHashGetter.GetPasswordHash
type PasswordHashGetterMockGetPasswordHashParamPtrs struct {
	ctx      *context.Context
	userName *string
}

// PasswordHashGetterMockGetPasswordHashResults contains results of the passwordHashGetter.GetPasswordHash
type PasswordHashGetterMockGetPasswordHashResults struct {
	s1  string
	err error
}

// PasswordHashGetterMockGetPasswordHashOrigins contains origins of expectations of the passwordHashGetter.GetPasswordHash
type PasswordHashGetterMockGetPasswordHashExpectationOrigins struct {
	origin         string
	originCtx      string
	originUserName string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetPasswordHash *mPasswordHashGetterMockGetPasswordHash) Optional() *mPasswordHashGetterMockGetPasswordHash {
	mmGetPasswordHash.optional = true
	return mmGetPasswordHash
}

// Expect sets up expected params for passwordHashGetter.GetPasswordHash
func (mmGetPasswordHash *mPasswordHashGetterMockGetPasswordHash) Expect(ctx context.Context, userName string) *mPasswordHashGetterMockGetPasswordHash {
	if mmGetPasswordHash.mock.funcGetPasswordHash != nil {
		mmGetPasswordHash.mock.t.Fatalf("PasswordHashGetterMock.GetPasswordHash mock is already set by Set")
	}

	if mmGetPasswordHash.defaultExpectation == nil {
		mmGetPasswordHash.defaultExpectation = &PasswordHashGetterMockGetPasswordHashExpectation{}
	}

	if mmGetPasswordHash.defaultExpectation.paramPtrs != nil {
		mmGetPasswordHash.mock.t.Fatalf("PasswordHashGetterMock.GetPasswordHash mock is already set by ExpectParams functions")
	}

	mmGetPasswordHash.defaultExpectation.params = &PasswordHashGetterMockGetPasswordHashParams{ctx, userName}
	mmGetPasswordHash.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetPasswordHash.expectations {
		if minimock.Equal(e.params, mmGetPasswordHash.defaultExpectation.params) {
			mmGetPasswordHash.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetPasswordHash.defaultExpectation.params)
		}
	}

	return mmGetPasswordHash
}

// ExpectCtxParam1 sets up expected param ctx for passwordHashGetter.GetPasswordHash
func (mmGetPasswordHash *mPasswordHashGetterMockGetPasswordHash) ExpectCtxParam1(ctx context.Context) *mPasswordHashGetterMockGetPasswordHash {
	if mmGetPasswordHash.mock.funcGetPasswordHash != nil {
		mmGetPasswordHash.mock.t.Fatalf("PasswordHashGetterMock.GetPasswordHash mock is already set by Set")
	}

	if mmGetPasswordHash.defaultExpectation == nil {
		mmGetPasswordHash.defaultExpectation = &PasswordHashGetterMockGetPasswordHashExpectation{}
	}

	if mmGetPasswordHash.defaultExpectation.params != nil {
		mmGetPasswordHash.mock.t.Fatalf("PasswordHashGetterMock.GetPasswordHash mock is already set by Expect")
	}

	if mmGetPasswordHash.defaultExpectation.paramPtrs == nil {
		mmGetPasswordHash.defaultExpectation.paramPtrs = &PasswordHashGetterMockGetPasswordHashParamPtrs{}
	}
	mmGetPasswordHash.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetPasswordHash.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetPasswordHash
}

// ExpectUserNameParam2 sets up expected param userName for passwordHashGetter.GetPasswordHash
func (mmGetPasswordHash *mPasswordHashGetterMockGetPasswordHash) ExpectUserNameParam2(userName string) *mPasswordHashGetterMockGetPasswordHash {
	if mmGetPasswordHash.mock.funcGetPasswordHash != nil {
		mmGetPasswordHash.mock.t.Fatalf("PasswordHashGetterMock.GetPasswordHash mock is already set by Set")
	}

	if mmGetPasswordHash.defaultExpectation == nil {
		mmGetPasswordHash.defaultExpectation = &PasswordHashGetterMockGetPasswordHashExpectation{}
	}

	if mmGetPasswordHash.defaultExpectation.params != nil {
		mmGetPasswordHash.mock.t.Fatalf("PasswordHashGetterMock.GetPasswordHash mock is already set by Expect")
	}

	if mmGetPasswordHash.defaultExpectation.paramPtrs == nil {
		mmGetPasswordHash.defaultExpectation.paramPtrs = &PasswordHashGetterMockGetPasswordHashParamPtrs{}
	}
	mmGetPasswordHash.defaultExpectation.paramPtrs.userName = &userName
	mmGetPasswordHash.defaultExpectation.expectationOrigins.originUserName = minimock.CallerInfo(1)

	return mmGetPasswordHash
}

// Inspect accepts an inspector function that has same arguments as the passwordHashGetter.GetPasswordHash
func (mmGetPasswordHash *mPasswordHashGetterMockGetPasswordHash) Inspect(f func(ctx context.Context, userName string)) *mPasswordHashGetterMockGetPasswordHash {
	if mmGetPasswordHash.mock.inspectFuncGetPasswordHash != nil {
		mmGetPasswordHash.mock.t.Fatalf("Inspect function is already set for PasswordHashGetterMock.GetPasswordHash")
	}

	mmGetPasswordHash.mock.inspectFuncGetPasswordHash = f

	return mmGetPasswordHash
}

// Return sets up results that will be returned by passwordHashGetter.GetPasswordHash
func (mmGetPasswordHash *mPasswordHashGetterMockGetPasswordHash) Return(s1 string, err error) *PasswordHashGetterMock {
	if mmGetPasswordHash.mock.funcGetPasswordHash != nil {
		mmGetPasswordHash.mock.t.Fatalf("PasswordHashGetterMock.GetPasswordHash mock is already set by Set")
	}

	if mmGetPasswordHash.defaultExpectation == nil {
		mmGetPasswordHash.defaultExpectation = &PasswordHashGetterMockGetPasswordHashExpectation{mock: mmGetPasswordHash.mock}
	}
	mmGetPasswordHash.defaultExpectation.results = &PasswordHashGetterMockGetPasswordHashResults{s1, err}
	mmGetPasswordHash.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetPasswordHash.mock
}

// Set uses given function f to mock the passwordHashGetter.GetPasswordHash method
func (mmGetPasswordHash *mPasswordHashGetterMockGetPasswordHash) Set(f func(ctx context.Context, userName string) (s1 string, err error)) *PasswordHashGetterMock {
	if mmGetPasswordHash.defaultExpectation != nil {
		mmGetPasswordHash.mock.t.Fatalf("Default expectation is already set for the passwordHashGetter.GetPasswordHash method")
	}

	if len(mmGetPasswordHash.expectations) > 0 {
		mmGetPasswordHash.mock.t.Fatalf("Some expectations are already set for the passwordHashGetter.GetPasswordHash method")
	}

	mmGetPasswordHash.mock.funcGetPasswordHash = f
	mmGetPasswordHash.mock.funcGetPasswordHashOrigin = minimock.CallerInfo(1)
	return mmGetPasswordHash.mock
}

// When sets expectation for the passwordHashGetter.GetPasswordHash which will trigger the result defined by the following
// Then helper
func (mmGetPasswordHash *mPasswordHashGetterMockGetPasswordHash) When(ctx context.Context, userName string) *PasswordHashGetterMockGetPasswordHashExpectation {
	if mmGetPasswordHash.mock.funcGetPasswordHash != nil {
		mmGetPasswordHash.mock.t.Fatalf("PasswordHashGetterMock.GetPasswordHash mock is already set by Set")
	}

	expectation := &PasswordHashGetterMockGetPasswordHashExpectation{
		mock:               mmGetPasswordHash.mock,
		params:             &PasswordHashGetterMockGetPasswordHashParams{ctx, userName},
		expectationOrigins: PasswordHashGetterMockGetPasswordHashExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetPasswordHash.expectations = append(mmGetPasswordHash.expectations, expectation)
	return expectation
}

// Then sets up passwordHashGetter.GetPasswordHash return parameters for the expectation previously defined by the When method
func (e *PasswordHashGetterMockGetPasswordHashExpectation) Then(s1 string, err error) *PasswordHashGetterMock {
	e.results = &PasswordHashGetterMockGetPasswordHashResults{s1, err}
	return e.mock
}

// Times sets number of times passwordHashGetter.GetPasswordHash should be invoked
func (mmGetPasswordHash *mPasswordHashGetterMockGetPasswordHash) Times(n uint64) *mPasswordHashGetterMockGetPasswordHash {
	if n == 0 {
		mmGetPasswordHash.mock.t.Fatalf("Times of PasswordHashGetterMock.GetPasswordHash mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetPasswordHash.expectedInvocations, n)
	mmGetPasswordHash.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetPasswordHash
}

func (mmGetPasswordHash *mPasswordHashGetterMockGetPasswordHash) invocationsDone() bool {
	if len(mmGetPasswordHash.expectations) == 0 && mmGetPasswordHash.defaultExpectation == nil && mmGetPasswordHash.mock.funcGetPasswordHash == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetPasswordHash.mock.afterGetPasswordHashCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetPasswordHash.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetPasswordHash implements passwordHashGetter
func (mmGetPasswordHash *PasswordHashGetterMock) GetPasswordHash(ctx context.Context, userName string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmGetPasswordHash.beforeGetPasswordHashCounter, 1)
	defer mm_atomic.AddUint64(&mmGetPasswordHash.afterGetPasswordHashCounter, 1)

	mmGetPasswordHash.t.Helper()

	if mmGetPasswordHash.inspectFuncGetPasswordHash != nil {
		mmGetPasswordHash.inspectFuncGetPasswordHash(ctx, userName)
	}

	mm_params := PasswordHashGetterMockGetPasswordHashParams{ctx, userName}

	// Record call args
	mmGetPasswordHash.GetPasswordHashMock.mutex.Lock()
	mmGetPasswordHash.GetPasswordHashMock.callArgs = append(mmGetPasswordHash.GetPasswordHashMock.callArgs, &mm_params)
	mmGetPasswordHash.GetPasswordHashMock.mutex.Unlock()

	for _, e := range mmGetPasswordHash.GetPasswordHashMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmGetPasswordHash.GetPasswordHashMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetPasswordHash.GetPasswordHashMock.defaultExpectation.Counter, 1)
		mm_want := mmGetPasswordHash.GetPasswordHashMock.defaultExpectation.params
		mm_want_ptrs := mmGetPasswordHash.GetPasswordHashMock.defaultExpectation.paramPtrs

		mm_got := PasswordHashGetterMockGetPasswordHashParams{ctx, userName}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetPasswordHash.t.Errorf("PasswordHashGetterMock.GetPasswordHash got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetPasswordHash.GetPasswordHashMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userName != nil && !minimock.Equal(*mm_want_ptrs.userName, mm_got.userName) {
				mmGetPasswordHash.t.Errorf("PasswordHashGetterMock.GetPasswordHash got unexpected parameter userName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetPasswordHash.GetPasswordHashMock.defaultExpectation.expectationOrigins.originUserName, *mm_want_ptrs.userName, mm_got.userName, minimock.Diff(*mm_want_ptrs.userName, mm_got.userName))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetPasswordHash.t.Errorf("PasswordHashGetterMock.GetPasswordHash got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetPasswordHash.GetPasswordHashMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetPasswordHash.GetPasswordHashMock.defaultExpectation.results
		if mm_results == nil {
			mmGetPasswordHash.t.Fatal("No results are set for the PasswordHashGetterMock.GetPasswordHash")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmGetPasswordHash.funcGetPasswordHash != nil {
		return mmGetPasswordHash.funcGetPasswordHash(ctx, userName)
	}
	mmGetPasswordHash.t.Fatalf("Unexpected call to PasswordHashGetterMock.GetPasswordHash. %v %v", ctx, userName)
	return
}

// GetPasswordHashAfterCounter returns a count of finished PasswordHashGetterMock.GetPasswordHash invocations
func (mmGetPasswordHash *PasswordHashGetterMock) GetPasswordHashAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetPasswordHash.afterGetPasswordHashCounter)
}

// GetPasswordHashBeforeCounter returns a count of PasswordHashGetterMock.GetPasswordHash invocations
func (mmGetPasswordHash *PasswordHashGetterMock) GetPasswordHashBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetPasswordHash.beforeGetPasswordHashCounter)
}

// Calls returns a list of arguments used in each call to PasswordHashGetterMock.GetPasswordHash.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetPasswordHash *mPasswordHashGetterMockGetPasswordHash) Calls() []*PasswordHashGetterMockGetPasswordHashParams {
	mmGetPasswordHash.mutex.RLock()

	argCopy := make([]*PasswordHashGetterMockGetPasswordHashParams, len(mmGetPasswordHash.callArgs))
	copy(argCopy, mmGetPasswordHash.callArgs)

	mmGetPasswordHash.mutex.RUnlock()

	return argCopy
}

// MinimockGetPasswordHashDone returns true if the count of the GetPasswordHash invocations corresponds
// the number of defined expectations
func (m *PasswordHashGetterMock) MinimockGetPasswordHashDone() bool {
	if m.GetPasswordHashMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetPasswordHashMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetPasswordHashMock.invocationsDone()
}

// MinimockGetPasswordHashInspect logs each unmet expectation
func (m *PasswordHashGetterMock) MinimockGetPasswordHashInspect() {
	for _, e := range m.GetPasswordHashMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PasswordHashGetterMock.GetPasswordHash at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetPasswordHashCounter := mm_atomic.LoadUint64(&m.afterGetPasswordHashCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetPasswordHashMock.defaultExpectation != nil && afterGetPasswordHashCounter < 1 {
		if m.GetPasswordHashMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to PasswordHashGetterMock.GetPasswordHash at\n%s", m.GetPasswordHashMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to PasswordHashGetterMock.GetPasswordHash at\n%s with params: %#v", m.GetPasswordHashMock.defaultExpectation.expectationOrigins.origin, *m.GetPasswordHashMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetPasswordHash != nil && afterGetPasswordHashCounter < 1 {
		m.t.Errorf("Expected call to PasswordHashGetterMock.GetPasswordHash at\n%s", m.funcGetPasswordHashOrigin)
	}

	if !m.GetPasswordHashMock.invocationsDone() && afterGetPasswordHashCounter > 0 {
		m.t.Errorf("Expected %d calls to PasswordHashGetterMock.GetPasswordHash at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetPasswordHashMock.expectedInvocations), m.GetPasswordHashMock.expectedInvocationsOrigin, afterGetPasswordHashCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *PasswordHashGetterMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetPasswordHashInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *PasswordHashGetterMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *PasswordHashGetterMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetPasswordHashDone()
}
