// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package proxy

//go:generate minimock -i github.com/nskondratev/socks5-proxy-server/proxy/internal/adapters/proxy.passwordComparator -o password_comparator_mock_test.go -n PasswordComparatorMock -p proxy

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// PasswordComparatorMock implements passwordComparator
type PasswordComparatorMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcValid          func(input string, toCompare string) (b1 bool, err error)
	funcValidOrigin    string
	inspectFuncValid   func(input string, toCompare string)
	afterValidCounter  uint64
	beforeValidCounter uint64
	ValidMock          mPasswordComparatorMockValid
}

// NewPasswordComparatorMock returns a mock for passwordComparator
func NewPasswordComparatorMock(t minimock.Tester) *PasswordComparatorMock {
	m := &PasswordComparatorMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ValidMock = mPasswordComparatorMockValid{mock: m}
	m.ValidMock.callArgs = []*PasswordComparatorMockValidParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mPasswordComparatorMockValid struct {
	optional           bool
	mock               *PasswordComparatorMock
	defaultExpectation *PasswordComparatorMockValidExpectation
	expectations       []*PasswordComparatorMockValidExpectation

	callArgs []*PasswordComparatorMockValidParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PasswordComparatorMockValidExpectation specifies expectation struct of the passwordComparator.Valid
type PasswordComparatorMockValidExpectation struct {
	mock               *PasswordComparatorMock
	params             *PasswordComparatorMockValidParams
	paramPtrs          *PasswordComparatorMockValidParamPtrs
	expectationOrigins PasswordComparatorMockValidExpectationOrigins
	results            *PasswordComparatorMockValidResults
	returnOrigin       string
	Counter            uint64
}

// PasswordComparatorMockValidParams contains parameters of the passwordComparator.Valid
type PasswordComparatorMockValidParams struct {
	input     string
	toCompare string
}

// PasswordComparatorMockValidParamPtrs contains pointers to parameters of the passwordComparator.Valid
type PasswordComparatorMockValidParamPtrs struct {
	input     *string
	toCompare *string
}

// PasswordComparatorMockValidResults contains results of the passwordComparator.Valid
type PasswordComparatorMockValidResults struct {
	b1  bool
	err error
}

// PasswordComparatorMockValidOrigins contains origins of expectations of the passwordComparator.Valid
type PasswordComparatorMockValidExpectationOrigins struct {
	origin          string
	originInput     string
	originToCompare string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmValid *mPasswordComparatorMockValid) Optional() *mPasswordComparatorMockValid {
	mmValid.optional = true
	return mmValid
}

// Expect sets up expected params for passwordComparator.Valid
func (mmValid *mPasswordComparatorMockValid) Expect(input string, toCompare string) *mPasswordComparatorMockValid {
	if mmValid.mock.funcValid != nil {
		mmValid.mock.t.Fatalf("PasswordComparatorMock.Valid mock is already set by Set")
	}

	if mmValid.defaultExpectation == nil {
		mmValid.defaultExpectation = &PasswordComparatorMockValidExpectation{}
	}

	if mmValid.defaultExpectation.paramPtrs != nil {
		mmValid.mock.t.Fatalf("PasswordComparatorMock.Valid mock is already set by ExpectParams functions")
	}

	mmValid.defaultExpectation.params = &PasswordComparatorMockValidParams{input, toCompare}
	mmValid.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmValid.expectations {
		if minimock.Equal(e.params, mmValid.defaultExpectation.params) {
			mmValid.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmValid.defaultExpectation.params)
		}
	}

	return mmValid
}

// ExpectInputParam1 sets up expected param input for passwordComparator.Valid
func (mmValid *mPasswordComparatorMockValid) ExpectInputParam1(input string) *mPasswordComparatorMockValid {
	if mmValid.mock.funcValid != nil {
		mmValid.mock.t.Fatalf("PasswordComparatorMock.Valid mock is already set by Set")
	}

	if mmValid.defaultExpectation == nil {
		mmValid.defaultExpectation = &PasswordComparatorMockValidExpectation{}
	}

	if mmValid.defaultExpectation.params != nil {
		mmValid.mock.t.Fatalf("PasswordComparatorMock.Valid mock is already set by Expect")
	}

	if mmValid.defaultExpectation.paramPtrs == nil {
		mmValid.defaultExpectation.paramPtrs = &PasswordComparatorMockValidParamPtrs{}
	}
	mmValid.defaultExpectation.paramPtrs.input = &input
	mmValid.defaultExpectation.expectationOrigins.originInput = minimock.CallerInfo(1)

	return mmValid
}

// ExpectToCompareParam2 sets up expected param toCompare for passwordComparator.Valid
func (mmValid *mPasswordComparatorMockValid) ExpectToCompareParam2(toCompare string) *mPasswordComparatorMockValid {
	if mmValid.mock.funcValid != nil {
		mmValid.mock.t.Fatalf("PasswordComparatorMock.Valid mock is already set by Set")
	}

	if mmValid.defaultExpectation == nil {
		mmValid.defaultExpectation = &PasswordComparatorMockValidExpectation{}
	}

	if mmValid.defaultExpectation.params != nil {
		mmValid.mock.t.Fatalf("PasswordComparatorMock.Valid mock is already set by Expect")
	}

	if mmValid.defaultExpectation.paramPtrs == nil {
		mmValid.defaultExpectation.paramPtrs = &PasswordComparatorMockValidParamPtrs{}
	}
	mmValid.defaultExpectation.paramPtrs.toCompare = &toCompare
	mmValid.defaultExpectation.expectationOrigins.originToCompare = minimock.CallerInfo(1)

	return mmValid
}

// Inspect accepts an inspector function that has same arguments as the passwordComparator.Valid
func (mmValid *mPasswordComparatorMockValid) Inspect(f func(input string, toCompare string)) *mPasswordComparatorMockValid {
	if mmValid.mock.inspectFuncValid != nil {
		mmValid.mock.t.Fatalf("Inspect function is already set for PasswordComparatorMock.Valid")
	}

	mmValid.mock.inspectFuncValid = f

	return mmValid
}

// Return sets up results that will be returned by passwordComparator.Valid
func (mmValid *mPasswordComparatorMockValid) Return(b1 bool, err error) *PasswordComparatorMock {
	if mmValid.mock.funcValid != nil {
		mmValid.mock.t.Fatalf("PasswordComparatorMock.Valid mock is already set by Set")
	}

	if mmValid.defaultExpectation == nil {
		mmValid.defaultExpectation = &PasswordComparatorMockValidExpectation{mock: mmValid.mock}
	}
	mmValid.defaultExpectation.results = &PasswordComparatorMockValidResults{b1, err}
	mmValid.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmValid.mock
}

// Set uses given function f to mock the passwordComparator.Valid method
func (mmValid *mPasswordComparatorMockValid) Set(f func(input string, toCompare string) (b1 bool, err error)) *PasswordComparatorMock {
	if mmValid.defaultExpectation != nil {
		mmValid.mock.t.Fatalf("Default expectation is already set for the passwordComparator.Valid method")
	}

	if len(mmValid.expectations) > 0 {
		mmValid.mock.t.Fatalf("Some expectations are already set for the passwordComparator.Valid method")
	}

	mmValid.mock.funcValid = f
	mmValid.mock.funcValidOrigin = minimock.CallerInfo(1)
	return mmValid.mock
}

// When sets expectation for the passwordComparator.Valid which will trigger the result defined by the following
// Then helper
func (mmValid *mPasswordComparatorMockValid) When(input string, toCompare string) *PasswordComparatorMockValidExpectation {
	if mmValid.mock.funcValid != nil {
		mmValid.mock.t.Fatalf("PasswordComparatorMock.Valid mock is already set by Set")
	}

	expectation := &PasswordComparatorMockValidExpectation{
		mock:               mmValid.mock,
		params:             &PasswordComparatorMockValidParams{input, toCompare},
		expectationOrigins: PasswordComparatorMockValidExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmValid.expectations = append(mmValid.expectations, expectation)
	return expectation
}

// Then sets up passwordComparator.Valid return parameters for the expectation previously defined by the When method
func (e *PasswordComparatorMockValidExpectation) Then(b1 bool, err error) *PasswordComparatorMock {
	e.results = &PasswordComparatorMockValidResults{b1, err}
	return e.mock
}

// Times sets number of times passwordComparator.Valid should be invoked
func (mmValid *mPasswordComparatorMockValid) Times(n uint64) *mPasswordComparatorMockValid {
	if n == 0 {
		mmValid.mock.t.Fatalf("Times of PasswordComparatorMock.Valid mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmValid.expectedInvocations, n)
	mmValid.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmValid
}

func (mmValid *mPasswordComparatorMockValid) invocationsDone() bool {
	if len(mmValid.expectations) == 0 && mmValid.defaultExpectation == nil && mmValid.mock.funcValid == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmValid.mock.afterValidCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmValid.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Valid implements passwordComparator
func (mmValid *PasswordComparatorMock) Valid(input string, toCompare string) (b1 bool, err error) {
	mm_atomic.AddUint64(&mmValid.beforeValidCounter, 1)
	defer mm_atomic.AddUint64(&mmValid.afterValidCounter, 1)

	mmValid.t.Helper()

	if mmValid.inspectFuncValid != nil {
		mmValid.inspectFuncValid(input, toCompare)
	}

	mm_params := PasswordComparatorMockValidParams{input, toCompare}

	// Record call args
	mmValid.ValidMock.mutex.Lock()
	mmValid.ValidMock.callArgs = append(mmValid.ValidMock.callArgs, &mm_params)
	mmValid.ValidMock.mutex.Unlock()

	for _, e := range mmValid.ValidMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.b1, e.results.err
		}
	}

	if mmValid.ValidMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmValid.ValidMock.defaultExpectation.Counter, 1)
		mm_want := mmValid.ValidMock.defaultExpectation.params
		mm_want_ptrs := mmValid.ValidMock.defaultExpectation.paramPtrs

		mm_got := PasswordComparatorMockValidParams{input, toCompare}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.input != nil && !minimock.Equal(*mm_want_ptrs.input, mm_got.input) {
				mmValid.t.Errorf("PasswordComparatorMock.Valid got unexpected parameter input, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmValid.ValidMock.defaultExpectation.expectationOrigins.originInput, *mm_want_ptrs.input, mm_got.input, minimock.Diff(*mm_want_ptrs.input, mm_got.input))
			}

			if mm_want_ptrs.toCompare != nil && !minimock.Equal(*mm_want_ptrs.toCompare, mm_got.toCompare) {
				mmValid.t.Errorf("PasswordComparatorMock.Valid got unexpected parameter toCompare, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmValid.ValidMock.defaultExpectation.expectationOrigins.originToCompare, *mm_want_ptrs.toCompare, mm_got.toCompare, minimock.Diff(*mm_want_ptrs.toCompare, mm_got.toCompare))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmValid.t.Errorf("PasswordComparatorMock.Valid got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmValid.ValidMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmValid.ValidMock.defaultExpectation.results
		if mm_results == nil {
			mmValid.t.Fatal("No results are set for the PasswordComparatorMock.Valid")
		}
		return (*mm_results).b1, (*mm_results).err
	}
	if mmValid.funcValid != nil {
		return mmValid.funcValid(input, toCompare)
	}
	mmValid.t.Fatalf("Unexpected call to PasswordComparatorMock.Valid. %v %v", input, toCompare)
	return
}

// ValidAfterCounter returns a count of finished PasswordComparatorMock.Valid invocations
func (mmValid *PasswordComparatorMock) ValidAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValid.afterValidCounter)
}

// ValidBeforeCounter returns a count of PasswordComparatorMock.Valid invocations
func (mmValid *PasswordComparatorMock) ValidBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValid.beforeValidCounter)
}

// Calls returns a list of arguments used in each call to PasswordComparatorMock.Valid.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmValid *mPasswordComparatorMockValid) Calls() []*PasswordComparatorMockValidParams {
	mmValid.mutex.RLock()

	argCopy := make([]*PasswordComparatorMockValidParams, len(mmValid.callArgs))
	copy(argCopy, mmValid.callArgs)

	mmValid.mutex.RUnlock()

	return argCopy
}

// MinimockValidDone returns true if the count of the Valid invocations corresponds
// the number of defined expectations
func (m *PasswordComparatorMock) MinimockValidDone() bool {
	if m.ValidMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ValidMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ValidMock.invocationsDone()
}

// MinimockValidInspect logs each unmet expectation
func (m *PasswordComparatorMock) MinimockValidInspect() {
	for _, e := range m.ValidMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PasswordComparatorMock.Valid at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterValidCounter := mm_atomic.LoadUint64(&m.afterValidCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ValidMock.defaultExpectation != nil && afterValidCounter < 1 {
		if m.ValidMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to PasswordComparatorMock.Valid at\n%s", m.ValidMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to PasswordComparatorMock.Valid at\n%s with params: %#v", m.ValidMock.defaultExpectation.expectationOrigins.origin, *m.ValidMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcValid != nil && afterValidCounter < 1 {
		m.t.Errorf("Expected call to PasswordComparatorMock.Valid at\n%s", m.funcValidOrigin)
	}

	if !m.ValidMock.invocationsDone() && afterValidCounter > 0 {
		m.t.Errorf("Expected %d calls to PasswordComparatorMock.Valid at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ValidMock.expectedInvocations), m.ValidMock.expectedInvocationsOrigin, afterValidCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *PasswordComparatorMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockValidInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *PasswordComparatorMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *PasswordComparatorMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockValidDone()
}
