// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package usersstats

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/nskondratev/socks5-proxy-server/internal/bot/store"
)

// StateStatsStoreMock implements stateStatsStore
type StateStatsStoreMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetUsersStats          func(ctx context.Context) (ua1 []store.UserStat, err error)
	funcGetUsersStatsOrigin    string
	inspectFuncGetUsersStats   func(ctx context.Context)
	afterGetUsersStatsCounter  uint64
	beforeGetUsersStatsCounter uint64
	GetUsersStatsMock          mStateStatsStoreMockGetUsersStats

	funcSetUserState          func(ctx context.Context, username string, state store.UserState) (err error)
	funcSetUserStateOrigin    string
	inspectFuncSetUserState   func(ctx context.Context, username string, state store.UserState)
	afterSetUserStateCounter  uint64
	beforeSetUserStateCounter uint64
	SetUserStateMock          mStateStatsStoreMockSetUserState
}

// NewStateStatsStoreMock returns a mock for stateStatsStore
func NewStateStatsStoreMock(t minimock.Tester) *StateStatsStoreMock {
	m := &StateStatsStoreMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetUsersStatsMock = mStateStatsStoreMockGetUsersStats{mock: m}
	m.GetUsersStatsMock.callArgs = []*StateStatsStoreMockGetUsersStatsParams{}

	m.SetUserStateMock = mStateStatsStoreMockSetUserState{mock: m}
	m.SetUserStateMock.callArgs = []*StateStatsStoreMockSetUserStateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStateStatsStoreMockGetUsersStats struct {
	optional           bool
	mock               *StateStatsStoreMock
	defaultExpectation *StateStatsStoreMockGetUsersStatsExpectation
	expectations       []*StateStatsStoreMockGetUsersStatsExpectation

	callArgs []*StateStatsStoreMockGetUsersStatsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StateStatsStoreMockGetUsersStatsExpectation specifies expectation struct of the stateStatsStore.GetUsersStats
type StateStatsStoreMockGetUsersStatsExpectation struct {
	mock               *StateStatsStoreMock
	params             *StateStatsStoreMockGetUsersStatsParams
	paramPtrs          *StateStatsStoreMockGetUsersStatsParamPtrs
	expectationOrigins StateStatsStoreMockGetUsersStatsExpectationOrigins
	results            *StateStatsStoreMockGetUsersStatsResults
	returnOrigin       string
	Counter            uint64
}

// StateStatsStoreMockGetUsersStatsParams contains parameters of the stateStatsStore.GetUsersStats
type StateStatsStoreMockGetUsersStatsParams struct {
	ctx context.Context
}

// StateStatsStoreMockGetUsersStatsParamPtrs contains pointers to parameters of the stateStatsStore.GetUsersStats
type StateStatsStoreMockGetUsersStatsParamPtrs struct {
	ctx *context.Context
}

// StateStatsStoreMockGetUsersStatsResults contains results of the stateStatsStore.GetUsersStats
type StateStatsStoreMockGetUsersStatsResults struct {
	ua1 []store.UserStat
	err error
}

// StateStatsStoreMockGetUsersStatsOrigins contains origins of expectations of the stateStatsStore.GetUsersStats
type StateStatsStoreMockGetUsersStatsExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetUsersStats *mStateStatsStoreMockGetUsersStats) Optional() *mStateStatsStoreMockGetUsersStats {
	mmGetUsersStats.optional = true
	return mmGetUsersStats
}

// Expect sets up expected params for stateStatsStore.GetUsersStats
func (mmGetUsersStats *mStateStatsStoreMockGetUsersStats) Expect(ctx context.Context) *mStateStatsStoreMockGetUsersStats {
	if mmGetUsersStats.mock.funcGetUsersStats != nil {
		mmGetUsersStats.mock.t.Fatalf("StateStatsStoreMock.GetUsersStats mock is already set by Set")
	}

	if mmGetUsersStats.defaultExpectation == nil {
		mmGetUsersStats.defaultExpectation = &StateStatsStoreMockGetUsersStatsExpectation{}
	}

	if mmGetUsersStats.defaultExpectation.paramPtrs != nil {
		mmGetUsersStats.mock.t.Fatalf("StateStatsStoreMock.GetUsersStats mock is already set by ExpectParams functions")
	}

	mmGetUsersStats.defaultExpectation.params = &StateStatsStoreMockGetUsersStatsParams{ctx}
	mmGetUsersStats.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetUsersStats.expectations {
		if minimock.Equal(e.params, mmGetUsersStats.defaultExpectation.params) {
			mmGetUsersStats.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetUsersStats.defaultExpectation.params)
		}
	}

	return mmGetUsersStats
}

// ExpectCtxParam1 sets up expected param ctx for stateStatsStore.GetUsersStats
func (mmGetUsersStats *mStateStatsStoreMockGetUsersStats) ExpectCtxParam1(ctx context.Context) *mStateStatsStoreMockGetUsersStats {
	if mmGetUsersStats.mock.funcGetUsersStats != nil {
		mmGetUsersStats.mock.t.Fatalf("StateStatsStoreMock.GetUsersStats mock is already set by Set")
	}

	if mmGetUsersStats.defaultExpectation == nil {
		mmGetUsersStats.defaultExpectation = &StateStatsStoreMockGetUsersStatsExpectation{}
	}

	if mmGetUsersStats.defaultExpectation.params != nil {
		mmGetUsersStats.mock.t.Fatalf("StateStatsStoreMock.GetUsersStats mock is already set by Expect")
	}

	if mmGetUsersStats.defaultExpectation.paramPtrs == nil {
		mmGetUsersStats.defaultExpectation.paramPtrs = &StateStatsStoreMockGetUsersStatsParamPtrs{}
	}
	mmGetUsersStats.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetUsersStats.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetUsersStats
}

// Inspect accepts an inspector function that has same arguments as the stateStatsStore.GetUsersStats
func (mmGetUsersStats *mStateStatsStoreMockGetUsersStats) Inspect(f func(ctx context.Context)) *mStateStatsStoreMockGetUsersStats {
	if mmGetUsersStats.mock.inspectFuncGetUsersStats != nil {
		mmGetUsersStats.mock.t.Fatalf("Inspect function is already set for StateStatsStoreMock.GetUsersStats")
	}

	mmGetUsersStats.mock.inspectFuncGetUsersStats = f

	return mmGetUsersStats
}

// Return sets up results that will be returned by stateStatsStore.GetUsersStats
func (mmGetUsersStats *mStateStatsStoreMockGetUsersStats) Return(ua1 []store.UserStat, err error) *StateStatsStoreMock {
	if mmGetUsersStats.mock.funcGetUsersStats != nil {
		mmGetUsersStats.mock.t.Fatalf("StateStatsStoreMock.GetUsersStats mock is already set by Set")
	}

	if mmGetUsersStats.defaultExpectation == nil {
		mmGetUsersStats.defaultExpectation = &StateStatsStoreMockGetUsersStatsExpectation{mock: mmGetUsersStats.mock}
	}
	mmGetUsersStats.defaultExpectation.results = &StateStatsStoreMockGetUsersStatsResults{ua1, err}
	mmGetUsersStats.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetUsersStats.mock
}

// Set uses given function f to mock the stateStatsStore.GetUsersStats method
func (mmGetUsersStats *mStateStatsStoreMockGetUsersStats) Set(f func(ctx context.Context) (ua1 []store.UserStat, err error)) *StateStatsStoreMock {
	if mmGetUsersStats.defaultExpectation != nil {
		mmGetUsersStats.mock.t.Fatalf("Default expectation is already set for the stateStatsStore.GetUsersStats method")
	}

	if len(mmGetUsersStats.expectations) > 0 {
		mmGetUsersStats.mock.t.Fatalf("Some expectations are already set for the stateStatsStore.GetUsersStats method")
	}

	mmGetUsersStats.mock.funcGetUsersStats = f
	mmGetUsersStats.mock.funcGetUsersStatsOrigin = minimock.CallerInfo(1)
	return mmGetUsersStats.mock
}

// When sets expectation for the stateStatsStore.GetUsersStats which will trigger the result defined by the following
// Then helper
func (mmGetUsersStats *mStateStatsStoreMockGetUsersStats) When(ctx context.Context) *StateStatsStoreMockGetUsersStatsExpectation {
	if mmGetUsersStats.mock.funcGetUsersStats != nil {
		mmGetUsersStats.mock.t.Fatalf("StateStatsStoreMock.GetUsersStats mock is already set by Set")
	}

	expectation := &StateStatsStoreMockGetUsersStatsExpectation{
		mock:               mmGetUsersStats.mock,
		params:             &StateStatsStoreMockGetUsersStatsParams{ctx},
		expectationOrigins: StateStatsStoreMockGetUsersStatsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetUsersStats.expectations = append(mmGetUsersStats.expectations, expectation)
	return expectation
}

// Then sets up stateStatsStore.GetUsersStats return parameters for the expectation previously defined by the When method
func (e *StateStatsStoreMockGetUsersStatsExpectation) Then(ua1 []store.UserStat, err error) *StateStatsStoreMock {
	e.results = &StateStatsStoreMockGetUsersStatsResults{ua1, err}
	return e.mock
}

// Times sets number of times stateStatsStore.GetUsersStats should be invoked
func (mmGetUsersStats *mStateStatsStoreMockGetUsersStats) Times(n uint64) *mStateStatsStoreMockGetUsersStats {
	if n == 0 {
		mmGetUsersStats.mock.t.Fatalf("Times of StateStatsStoreMock.GetUsersStats mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetUsersStats.expectedInvocations, n)
	mmGetUsersStats.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetUsersStats
}

func (mmGetUsersStats *mStateStatsStoreMockGetUsersStats) invocationsDone() bool {
	if len(mmGetUsersStats.expectations) == 0 && mmGetUsersStats.defaultExpectation == nil && mmGetUsersStats.mock.funcGetUsersStats == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetUsersStats.mock.afterGetUsersStatsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetUsersStats.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetUsersStats implements stateStatsStore
func (mmGetUsersStats *StateStatsStoreMock) GetUsersStats(ctx context.Context) (ua1 []store.UserStat, err error) {
	mm_atomic.AddUint64(&mmGetUsersStats.beforeGetUsersStatsCounter, 1)
	defer mm_atomic.AddUint64(&mmGetUsersStats.afterGetUsersStatsCounter, 1)

	mmGetUsersStats.t.Helper()

	if mmGetUsersStats.inspectFuncGetUsersStats != nil {
		mmGetUsersStats.inspectFuncGetUsersStats(ctx)
	}

	mm_params := StateStatsStoreMockGetUsersStatsParams{ctx}

	// Record call args
	mmGetUsersStats.GetUsersStatsMock.mutex.Lock()
	mmGetUsersStats.GetUsersStatsMock.callArgs = append(mmGetUsersStats.GetUsersStatsMock.callArgs, &mm_params)
	mmGetUsersStats.GetUsersStatsMock.mutex.Unlock()

	for _, e := range mmGetUsersStats.GetUsersStatsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ua1, e.results.err
		}
	}

	if mmGetUsersStats.GetUsersStatsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetUsersStats.GetUsersStatsMock.defaultExpectation.Counter, 1)
		mm_want := mmGetUsersStats.GetUsersStatsMock.defaultExpectation.params
		mm_want_ptrs := mmGetUsersStats.GetUsersStatsMock.defaultExpectation.paramPtrs

		mm_got := StateStatsStoreMockGetUsersStatsParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetUsersStats.t.Errorf("StateStatsStoreMock.GetUsersStats got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUsersStats.GetUsersStatsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetUsersStats.t.Errorf("StateStatsStoreMock.GetUsersStats got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetUsersStats.GetUsersStatsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetUsersStats.GetUsersStatsMock.defaultExpectation.results
		if mm_results == nil {
			mmGetUsersStats.t.Fatal("No results are set for the StateStatsStoreMock.GetUsersStats")
		}
		return (*mm_results).ua1, (*mm_results).err
	}
	if mmGetUsersStats.funcGetUsersStats != nil {
		return mmGetUsersStats.funcGetUsersStats(ctx)
	}
	mmGetUsersStats.t.Fatalf("Unexpected call to StateStatsStoreMock.GetUsersStats. %v", ctx)
	return
}

// GetUsersStatsAfterCounter returns a count of finished StateStatsStoreMock.GetUsersStats invocations
func (mmGetUsersStats *StateStatsStoreMock) GetUsersStatsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUsersStats.afterGetUsersStatsCounter)
}

// GetUsersStatsBeforeCounter returns a count of StateStatsStoreMock.GetUsersStats invocations
func (mmGetUsersStats *StateStatsStoreMock) GetUsersStatsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUsersStats.beforeGetUsersStatsCounter)
}

// Calls returns a list of arguments used in each call to StateStatsStoreMock.GetUsersStats.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetUsersStats *mStateStatsStoreMockGetUsersStats) Calls() []*StateStatsStoreMockGetUsersStatsParams {
	mmGetUsersStats.mutex.RLock()

	argCopy := make([]*StateStatsStoreMockGetUsersStatsParams, len(mmGetUsersStats.callArgs))
	copy(argCopy, mmGetUsersStats.callArgs)

	mmGetUsersStats.mutex.RUnlock()

	return argCopy
}

// MinimockGetUsersStatsDone returns true if the count of the GetUsersStats invocations corresponds
// the number of defined expectations
func (m *StateStatsStoreMock) MinimockGetUsersStatsDone() bool {
	if m.GetUsersStatsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetUsersStatsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetUsersStatsMock.invocationsDone()
}

// MinimockGetUsersStatsInspect logs each unmet expectation
func (m *StateStatsStoreMock) MinimockGetUsersStatsInspect() {
	for _, e := range m.GetUsersStatsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StateStatsStoreMock.GetUsersStats at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetUsersStatsCounter := mm_atomic.LoadUint64(&m.afterGetUsersStatsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetUsersStatsMock.defaultExpectation != nil && afterGetUsersStatsCounter < 1 {
		if m.GetUsersStatsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StateStatsStoreMock.GetUsersStats at\n%s", m.GetUsersStatsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StateStatsStoreMock.GetUsersStats at\n%s with params: %#v", m.GetUsersStatsMock.defaultExpectation.expectationOrigins.origin, *m.GetUsersStatsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetUsersStats != nil && afterGetUsersStatsCounter < 1 {
		m.t.Errorf("Expected call to StateStatsStoreMock.GetUsersStats at\n%s", m.funcGetUsersStatsOrigin)
	}

	if !m.GetUsersStatsMock.invocationsDone() && afterGetUsersStatsCounter > 0 {
		m.t.Errorf("Expected %d calls to StateStatsStoreMock.GetUsersStats at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetUsersStatsMock.expectedInvocations), m.GetUsersStatsMock.expectedInvocationsOrigin, afterGetUsersStatsCounter)
	}
}

type mStateStatsStoreMockSetUserState struct {
	optional           bool
	mock               *StateStatsStoreMock
	defaultExpectation *StateStatsStoreMockSetUserStateExpectation
	expectations       []*StateStatsStoreMockSetUserStateExpectation

	callArgs []*StateStatsStoreMockSetUserStateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StateStatsStoreMockSetUserStateExpectation specifies expectation struct of the stateStatsStore.SetUserState
type StateStatsStoreMockSetUserStateExpectation struct {
	mock               *StateStatsStoreMock
	params             *StateStatsStoreMockSetUserStateParams
	paramPtrs          *StateStatsStoreMockSetUserStateParamPtrs
	expectationOrigins StateStatsStoreMockSetUserStateExpectationOrigins
	results            *StateStatsStoreMockSetUserStateResults
	returnOrigin       string
	Counter            uint64
}

// StateStatsStoreMockSetUserStateParams contains parameters of the stateStatsStore.SetUserState
type StateStatsStoreMockSetUserStateParams struct {
	ctx      context.Context
	username string
	state    store.UserState
}

// StateStatsStoreMockSetUserStateParamPtrs contains pointers to parameters of the stateStatsStore.SetUserState
type StateStatsStoreMockSetUserStateParamPtrs struct {
	ctx      *context.Context
	username *string
	state    *store.UserState
}

// StateStatsStoreMockSetUserStateResults contains results of the stateStatsStore.SetUserState
type StateStatsStoreMockSetUserStateResults struct {
	err error
}

// StateStatsStoreMockSetUserStateOrigins contains origins of expectations of the stateStatsStore.SetUserState
type StateStatsStoreMockSetUserStateExpectationOrigins struct {
	origin         string
	originCtx      string
	originUsername string
	originState    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSetUserState *mStateStatsStoreMockSetUserState) Optional() *mStateStatsStoreMockSetUserState {
	mmSetUserState.optional = true
	return mmSetUserState
}

// Expect sets up expected params for stateStatsStore.SetUserState
func (mmSetUserState *mStateStatsStoreMockSetUserState) Expect(ctx context.Context, username string, state store.UserState) *mStateStatsStoreMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StateStatsStoreMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &StateStatsStoreMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.paramPtrs != nil {
		mmSetUserState.mock.t.Fatalf("StateStatsStoreMock.SetUserState mock is already set by ExpectParams functions")
	}

	mmSetUserState.defaultExpectation.params = &StateStatsStoreMockSetUserStateParams{ctx, username, state}
	mmSetUserState.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSetUserState.expectations {
		if minimock.Equal(e.params, mmSetUserState.defaultExpectation.params) {
			mmSetUserState.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSetUserState.defaultExpectation.params)
		}
	}

	return mmSetUserState
}

// ExpectCtxParam1 sets up expected param ctx for stateStatsStore.SetUserState
func (mmSetUserState *mStateStatsStoreMockSetUserState) ExpectCtxParam1(ctx context.Context) *mStateStatsStoreMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StateStatsStoreMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &StateStatsStoreMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.params != nil {
		mmSetUserState.mock.t.Fatalf("StateStatsStoreMock.SetUserState mock is already set by Expect")
	}

	if mmSetUserState.defaultExpectation.paramPtrs == nil {
		mmSetUserState.defaultExpectation.paramPtrs = &StateStatsStoreMockSetUserStateParamPtrs{}
	}
	mmSetUserState.defaultExpectation.paramPtrs.ctx = &ctx
	mmSetUserState.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSetUserState
}

// ExpectUsernameParam2 sets up expected param username for stateStatsStore.SetUserState
func (mmSetUserState *mStateStatsStoreMockSetUserState) ExpectUsernameParam2(username string) *mStateStatsStoreMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StateStatsStoreMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &StateStatsStoreMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.params != nil {
		mmSetUserState.mock.t.Fatalf("StateStatsStoreMock.SetUserState mock is already set by Expect")
	}

	if mmSetUserState.defaultExpectation.paramPtrs == nil {
		mmSetUserState.defaultExpectation.paramPtrs = &StateStatsStoreMockSetUserStateParamPtrs{}
	}
	mmSetUserState.defaultExpectation.paramPtrs.username = &username
	mmSetUserState.defaultExpectation.expectationOrigins.originUsername = minimock.CallerInfo(1)

	return mmSetUserState
}

// ExpectStateParam3 sets up expected param state for stateStatsStore.SetUserState
func (mmSetUserState *mStateStatsStoreMockSetUserState) ExpectStateParam3(state store.UserState) *mStateStatsStoreMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StateStatsStoreMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &StateStatsStoreMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.params != nil {
		mmSetUserState.mock.t.Fatalf("StateStatsStoreMock.SetUserState mock is already set by Expect")
	}

	if mmSetUserState.defaultExpectation.paramPtrs == nil {
		mmSetUserState.defaultExpectation.paramPtrs = &StateStatsStoreMockSetUserStateParamPtrs{}
	}
	mmSetUserState.defaultExpectation.paramPtrs.state = &state
	mmSetUserState.defaultExpectation.expectationOrigins.originState = minimock.CallerInfo(1)

	return mmSetUserState
}

// Inspect accepts an inspector function that has same arguments as the stateStatsStore.SetUserState
func (mmSetUserState *mStateStatsStoreMockSetUserState) Inspect(f func(ctx context.Context, username string, state store.UserState)) *mStateStatsStoreMockSetUserState {
	if mmSetUserState.mock.inspectFuncSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("Inspect function is already set for StateStatsStoreMock.SetUserState")
	}

	mmSetUserState.mock.inspectFuncSetUserState = f

	return mmSetUserState
}

// Return sets up results that will be returned by stateStatsStore.SetUserState
func (mmSetUserState *mStateStatsStoreMockSetUserState) Return(err error) *StateStatsStoreMock {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StateStatsStoreMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &StateStatsStoreMockSetUserStateExpectation{mock: mmSetUserState.mock}
	}
	mmSetUserState.defaultExpectation.results = &StateStatsStoreMockSetUserStateResults{err}
	mmSetUserState.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSetUserState.mock
}

// Set uses given function f to mock the stateStatsStore.SetUserState method
func (mmSetUserState *mStateStatsStoreMockSetUserState) Set(f func(ctx context.Context, username string, state store.UserState) (err error)) *StateStatsStoreMock {
	if mmSetUserState.defaultExpectation != nil {
		mmSetUserState.mock.t.Fatalf("Default expectation is already set for the stateStatsStore.SetUserState method")
	}

	if len(mmSetUserState.expectations) > 0 {
		mmSetUserState.mock.t.Fatalf("Some expectations are already set for the stateStatsStore.SetUserState method")
	}

	mmSetUserState.mock.funcSetUserState = f
	mmSetUserState.mock.funcSetUserStateOrigin = minimock.CallerInfo(1)
	return mmSetUserState.mock
}

// When sets expectation for the stateStatsStore.SetUserState which will trigger the result defined by the following
// Then helper
func (mmSetUserState *mStateStatsStoreMockSetUserState) When(ctx context.Context, username string, state store.UserState) *StateStatsStoreMockSetUserStateExpectation {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StateStatsStoreMock.SetUserState mock is already set by Set")
	}

	expectation := &StateStatsStoreMockSetUserStateExpectation{
		mock:               mmSetUserState.mock,
		params:             &StateStatsStoreMockSetUserStateParams{ctx, username, state},
		expectationOrigins: StateStatsStoreMockSetUserStateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSetUserState.expectations = append(mmSetUserState.expectations, expectation)
	return expectation
}

// Then sets up stateStatsStore.SetUserState return parameters for the expectation previously defined by the When method
func (e *StateStatsStoreMockSetUserStateExpectation) Then(err error) *StateStatsStoreMock {
	e.results = &StateStatsStoreMockSetUserStateResults{err}
	return e.mock
}

// Times sets number of times stateStatsStore.SetUserState should be invoked
func (mmSetUserState *mStateStatsStoreMockSetUserState) Times(n uint64) *mStateStatsStoreMockSetUserState {
	if n == 0 {
		mmSetUserState.mock.t.Fatalf("Times of StateStatsStoreMock.SetUserState mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSetUserState.expectedInvocations, n)
	mmSetUserState.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSetUserState
}

func (mmSetUserState *mStateStatsStoreMockSetUserState) invocationsDone() bool {
	if len(mmSetUserState.expectations) == 0 && mmSetUserState.defaultExpectation == nil && mmSetUserState.mock.funcSetUserState == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSetUserState.mock.afterSetUserStateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSetUserState.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SetUserState implements stateStatsStore
func (mmSetUserState *StateStatsStoreMock) SetUserState(ctx context.Context, username string, state store.UserState) (err error) {
	mm_atomic.AddUint64(&mmSetUserState.beforeSetUserStateCounter, 1)
	defer mm_atomic.AddUint64(&mmSetUserState.afterSetUserStateCounter, 1)

	mmSetUserState.t.Helper()

	if mmSetUserState.inspectFuncSetUserState != nil {
		mmSetUserState.inspectFuncSetUserState(ctx, username, state)
	}

	mm_params := StateStatsStoreMockSetUserStateParams{ctx, username, state}

	// Record call args
	mmSetUserState.SetUserStateMock.mutex.Lock()
	mmSetUserState.SetUserStateMock.callArgs = append(mmSetUserState.SetUserStateMock.callArgs, &mm_params)
	mmSetUserState.SetUserStateMock.mutex.Unlock()

	for _, e := range mmSetUserState.SetUserStateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSetUserState.SetUserStateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSetUserState.SetUserStateMock.defaultExpectation.Counter, 1)
		mm_want := mmSetUserState.SetUserStateMock.defaultExpectation.params
		mm_want_ptrs := mmSetUserState.SetUserStateMock.defaultExpectation.paramPtrs

		mm_got := StateStatsStoreMockSetUserStateParams{ctx, username, state}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSetUserState.t.Errorf("StateStatsStoreMock.SetUserState got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.username != nil && !minimock.Equal(*mm_want_ptrs.username, mm_got.username) {
				mmSetUserState.t.Errorf("StateStatsStoreMock.SetUserState got unexpected parameter username, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.originUsername, *mm_want_ptrs.username, mm_got.username, minimock.Diff(*mm_want_ptrs.username, mm_got.username))
			}

			if mm_want_ptrs.state != nil && !minimock.Equal(*mm_want_ptrs.state, mm_got.state) {
				mmSetUserState.t.Errorf("StateStatsStoreMock.SetUserState got unexpected parameter state, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.originState, *mm_want_ptrs.state, mm_got.state, minimock.Diff(*mm_want_ptrs.state, mm_got.state))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSetUserState.t.Errorf("StateStatsStoreMock.SetUserState got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSetUserState.SetUserStateMock.defaultExpectation.results
		if mm_results == nil {
			mmSetUserState.t.Fatal("No results are set for the StateStatsStoreMock.SetUserState")
		}
		return (*mm_results).err
	}
	if mmSetUserState.funcSetUserState != nil {
		return mmSetUserState.funcSetUserState(ctx, username, state)
	}
	mmSetUserState.t.Fatalf("Unexpected call to StateStatsStoreMock.SetUserState. %v %v %v", ctx, username, state)
	return
}

// SetUserStateAfterCounter returns a count of finished StateStatsStoreMock.SetUserState invocations
func (mmSetUserState *StateStatsStoreMock) SetUserStateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetUserState.afterSetUserStateCounter)
}

// SetUserStateBeforeCounter returns a count of StateStatsStoreMock.SetUserState invocations
func (mmSetUserState *StateStatsStoreMock) SetUserStateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetUserState.beforeSetUserStateCounter)
}

// Calls returns a list of arguments used in each call to StateStatsStoreMock.SetUserState.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSetUserState *mStateStatsStoreMockSetUserState) Calls() []*StateStatsStoreMockSetUserStateParams {
	mmSetUserState.mutex.RLock()

	argCopy := make([]*StateStatsStoreMockSetUserStateParams, len(mmSetUserState.callArgs))
	copy(argCopy, mmSetUserState.callArgs)

	mmSetUserState.mutex.RUnlock()

	return argCopy
}

// MinimockSetUserStateDone returns true if the count of the SetUserState invocations corresponds
// the number of defined expectations
func (m *StateStatsStoreMock) MinimockSetUserStateDone() bool {
	if m.SetUserStateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SetUserStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SetUserStateMock.invocationsDone()
}

// MinimockSetUserStateInspect logs each unmet expectation
func (m *StateStatsStoreMock) MinimockSetUserStateInspect() {
	for _, e := range m.SetUserStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StateStatsStoreMock.SetUserState at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSetUserStateCounter := mm_atomic.LoadUint64(&m.afterSetUserStateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SetUserStateMock.defaultExpectation != nil && afterSetUserStateCounter < 1 {
		if m.SetUserStateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StateStatsStoreMock.SetUserState at\n%s", m.SetUserStateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StateStatsStoreMock.SetUserState at\n%s with params: %#v", m.SetUserStateMock.defaultExpectation.expectationOrigins.origin, *m.SetUserStateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSetUserState != nil && afterSetUserStateCounter < 1 {
		m.t.Errorf("Expected call to StateStatsStoreMock.SetUserState at\n%s", m.funcSetUserStateOrigin)
	}

	if !m.SetUserStateMock.invocationsDone() && afterSetUserStateCounter > 0 {
		m.t.Errorf("Expected %d calls to StateStatsStoreMock.SetUserState at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SetUserStateMock.expectedInvocations), m.SetUserStateMock.expectedInvocationsOrigin, afterSetUserStateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StateStatsStoreMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetUsersStatsInspect()

			m.MinimockSetUserStateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StateStatsStoreMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StateStatsStoreMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetUsersStatsDone() &&
		m.MinimockSetUserStateDone()
}
