// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package store

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// RedisMock implements redis
type RedisMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcHGet          func(ctx context.Context, key string, field string) (s1 string, err error)
	funcHGetOrigin    string
	inspectFuncHGet   func(ctx context.Context, key string, field string)
	afterHGetCounter  uint64
	beforeHGetCounter uint64
	HGetMock          mRedisMockHGet

	funcHSet          func(ctx context.Context, key string, values ...interface{}) (err error)
	funcHSetOrigin    string
	inspectFuncHSet   func(ctx context.Context, key string, values ...interface{})
	afterHSetCounter  uint64
	beforeHSetCounter uint64
	HSetMock          mRedisMockHSet
}

// NewRedisMock returns a mock for redis
func NewRedisMock(t minimock.Tester) *RedisMock {
	m := &RedisMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.HGetMock = mRedisMockHGet{mock: m}
	m.HGetMock.callArgs = []*RedisMockHGetParams{}

	m.HSetMock = mRedisMockHSet{mock: m}
	m.HSetMock.callArgs = []*RedisMockHSetParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRedisMockHGet struct {
	optional           bool
	mock               *RedisMock
	defaultExpectation *RedisMockHGetExpectation
	expectations       []*RedisMockHGetExpectation

	callArgs []*RedisMockHGetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RedisMockHGetExpectation specifies expectation struct of the redis.HGet
type RedisMockHGetExpectation struct {
	mock               *RedisMock
	params             *RedisMockHGetParams
	paramPtrs          *RedisMockHGetParamPtrs
	expectationOrigins RedisMockHGetExpectationOrigins
	results            *RedisMockHGetResults
	returnOrigin       string
	Counter            uint64
}

// RedisMockHGetParams contains parameters of the redis.HGet
type RedisMockHGetParams struct {
	ctx   context.Context
	key   string
	field string
}

// RedisMockHGetParamPtrs contains pointers to parameters of the redis.HGet
type RedisMockHGetParamPtrs struct {
	ctx   *context.Context
	key   *string
	field *string
}

// RedisMockHGetResults contains results of the redis.HGet
type RedisMockHGetResults struct {
	s1  string
	err error
}

// RedisMockHGetOrigins contains origins of expectations of the redis.HGet
type RedisMockHGetExpectationOrigins struct {
	origin      string
	originCtx   string
	originKey   string
	originField string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmHGet *mRedisMockHGet) Optional() *mRedisMockHGet {
	mmHGet.optional = true
	return mmHGet
}

// Expect sets up expected params for redis.HGet
func (mmHGet *mRedisMockHGet) Expect(ctx context.Context, key string, field string) *mRedisMockHGet {
	if mmHGet.mock.funcHGet != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Set")
	}

	if mmHGet.defaultExpectation == nil {
		mmHGet.defaultExpectation = &RedisMockHGetExpectation{}
	}

	if mmHGet.defaultExpectation.paramPtrs != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by ExpectParams functions")
	}

	mmHGet.defaultExpectation.params = &RedisMockHGetParams{ctx, key, field}
	mmHGet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmHGet.expectations {
		if minimock.Equal(e.params, mmHGet.defaultExpectation.params) {
			mmHGet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmHGet.defaultExpectation.params)
		}
	}

	return mmHGet
}

// ExpectCtxParam1 sets up expected param ctx for redis.HGet
func (mmHGet *mRedisMockHGet) ExpectCtxParam1(ctx context.Context) *mRedisMockHGet {
	if mmHGet.mock.funcHGet != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Set")
	}

	if mmHGet.defaultExpectation == nil {
		mmHGet.defaultExpectation = &RedisMockHGetExpectation{}
	}

	if mmHGet.defaultExpectation.params != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Expect")
	}

	if mmHGet.defaultExpectation.paramPtrs == nil {
		mmHGet.defaultExpectation.paramPtrs = &RedisMockHGetParamPtrs{}
	}
	mmHGet.defaultExpectation.paramPtrs.ctx = &ctx
	mmHGet.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmHGet
}

// ExpectKeyParam2 sets up expected param key for redis.HGet
func (mmHGet *mRedisMockHGet) ExpectKeyParam2(key string) *mRedisMockHGet {
	if mmHGet.mock.funcHGet != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Set")
	}

	if mmHGet.defaultExpectation == nil {
		mmHGet.defaultExpectation = &RedisMockHGetExpectation{}
	}

	if mmHGet.defaultExpectation.params != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Expect")
	}

	if mmHGet.defaultExpectation.paramPtrs == nil {
		mmHGet.defaultExpectation.paramPtrs = &RedisMockHGetParamPtrs{}
	}
	mmHGet.defaultExpectation.paramPtrs.key = &key
	mmHGet.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmHGet
}

// ExpectFieldParam3 sets up expected param field for redis.HGet
func (mmHGet *mRedisMockHGet) ExpectFieldParam3(field string) *mRedisMockHGet {
	if mmHGet.mock.funcHGet != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Set")
	}

	if mmHGet.defaultExpectation == nil {
		mmHGet.defaultExpectation = &RedisMockHGetExpectation{}
	}

	if mmHGet.defaultExpectation.params != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Expect")
	}

	if mmHGet.defaultExpectation.paramPtrs == nil {
		mmHGet.defaultExpectation.paramPtrs = &RedisMockHGetParamPtrs{}
	}
	mmHGet.defaultExpectation.paramPtrs.field = &field
	mmHGet.defaultExpectation.expectationOrigins.originField = minimock.CallerInfo(1)

	return mmHGet
}

// Inspect accepts an inspector function that has same arguments as the redis.HGet
func (mmHGet *mRedisMockHGet) Inspect(f func(ctx context.Context, key string, field string)) *mRedisMockHGet {
	if mmHGet.mock.inspectFuncHGet != nil {
		mmHGet.mock.t.Fatalf("Inspect function is already set for RedisMock.HGet")
	}

	mmHGet.mock.inspectFuncHGet = f

	return mmHGet
}

// Return sets up results that will be returned by redis.HGet
func (mmHGet *mRedisMockHGet) Return(s1 string, err error) *RedisMock {
	if mmHGet.mock.funcHGet != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Set")
	}

	if mmHGet.defaultExpectation == nil {
		mmHGet.defaultExpectation = &RedisMockHGetExpectation{mock: mmHGet.mock}
	}
	mmHGet.defaultExpectation.results = &RedisMockHGetResults{s1, err}
	mmHGet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmHGet.mock
}

// Set uses given function f to mock the redis.HGet method
func (mmHGet *mRedisMockHGet) Set(f func(ctx context.Context, key string, field string) (s1 string, err error)) *RedisMock {
	if mmHGet.defaultExpectation != nil {
		mmHGet.mock.t.Fatalf("Default expectation is already set for the redis.HGet method")
	}

	if len(mmHGet.expectations) > 0 {
		mmHGet.mock.t.Fatalf("Some expectations are already set for the redis.HGet method")
	}

	mmHGet.mock.funcHGet = f
	mmHGet.mock.funcHGetOrigin = minimock.CallerInfo(1)
	return mmHGet.mock
}

// When sets expectation for the redis.HGet which will trigger the result defined by the following
// Then helper
func (mmHGet *mRedisMockHGet) When(ctx context.Context, key string, field string) *RedisMockHGetExpectation {
	if mmHGet.mock.funcHGet != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Set")
	}

	expectation := &RedisMockHGetExpectation{
		mock:               mmHGet.mock,
		params:             &RedisMockHGetParams{ctx, key, field},
		expectationOrigins: RedisMockHGetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmHGet.expectations = append(mmHGet.expectations, expectation)
	return expectation
}

// Then sets up redis.HGet return parameters for the expectation previously defined by the When method
func (e *RedisMockHGetExpectation) Then(s1 string, err error) *RedisMock {
	e.results = &RedisMockHGetResults{s1, err}
	return e.mock
}

// Times sets number of times redis.HGet should be invoked
func (mmHGet *mRedisMockHGet) Times(n uint64) *mRedisMockHGet {
	if n == 0 {
		mmHGet.mock.t.Fatalf("Times of RedisMock.HGet mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmHGet.expectedInvocations, n)
	mmHGet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmHGet
}

func (mmHGet *mRedisMockHGet) invocationsDone() bool {
	if len(mmHGet.expectations) == 0 && mmHGet.defaultExpectation == nil && mmHGet.mock.funcHGet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmHGet.mock.afterHGetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmHGet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// HGet implements redis
func (mmHGet *RedisMock) HGet(ctx context.Context, key string, field string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmHGet.beforeHGetCounter, 1)
	defer mm_atomic.AddUint64(&mmHGet.afterHGetCounter, 1)

	mmHGet.t.Helper()

	if mmHGet.inspectFuncHGet != nil {
		mmHGet.inspectFuncHGet(ctx, key, field)
	}

	mm_params := RedisMockHGetParams{ctx, key, field}

	// Record call args
	mmHGet.HGetMock.mutex.Lock()
	mmHGet.HGetMock.callArgs = append(mmHGet.HGetMock.callArgs, &mm_params)
	mmHGet.HGetMock.mutex.Unlock()

	for _, e := range mmHGet.HGetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmHGet.HGetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmHGet.HGetMock.defaultExpectation.Counter, 1)
		mm_want := mmHGet.HGetMock.defaultExpectation.params
		mm_want_ptrs := mmHGet.HGetMock.defaultExpectation.paramPtrs

		mm_got := RedisMockHGetParams{ctx, key, field}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmHGet.t.Errorf("RedisMock.HGet got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHGet.HGetMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmHGet.t.Errorf("RedisMock.HGet got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHGet.HGetMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

			if mm_want_ptrs.field != nil && !minimock.Equal(*mm_want_ptrs.field, mm_got.field) {
				mmHGet.t.Errorf("RedisMock.HGet got unexpected parameter field, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHGet.HGetMock.defaultExpectation.expectationOrigins.originField, *mm_want_ptrs.field, mm_got.field, minimock.Diff(*mm_want_ptrs.field, mm_got.field))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmHGet.t.Errorf("RedisMock.HGet got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmHGet.HGetMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmHGet.HGetMock.defaultExpectation.results
		if mm_results == nil {
			mmHGet.t.Fatal("No results are set for the RedisMock.HGet")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmHGet.funcHGet != nil {
		return mmHGet.funcHGet(ctx, key, field)
	}
	mmHGet.t.Fatalf("Unexpected call to RedisMock.HGet. %v %v %v", ctx, key, field)
	return
}

// HGetAfterCounter returns a count of finished RedisMock.HGet invocations
func (mmHGet *RedisMock) HGetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHGet.afterHGetCounter)
}

// HGetBeforeCounter returns a count of RedisMock.HGet invocations
func (mmHGet *RedisMock) HGetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHGet.beforeHGetCounter)
}

// Calls returns a list of arguments used in each call to RedisMock.HGet.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmHGet *mRedisMockHGet) Calls() []*RedisMockHGetParams {
	mmHGet.mutex.RLock()

	argCopy := make([]*RedisMockHGetParams, len(mmHGet.callArgs))
	copy(argCopy, mmHGet.callArgs)

	mmHGet.mutex.RUnlock()

	return argCopy
}

// MinimockHGetDone returns true if the count of the HGet invocations corresponds
// the number of defined expectations
func (m *RedisMock) MinimockHGetDone() bool {
	if m.HGetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.HGetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.HGetMock.invocationsDone()
}

// MinimockHGetInspect logs each unmet expectation
func (m *RedisMock) MinimockHGetInspect() {
	for _, e := range m.HGetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RedisMock.HGet at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterHGetCounter := mm_atomic.LoadUint64(&m.afterHGetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.HGetMock.defaultExpectation != nil && afterHGetCounter < 1 {
		if m.HGetMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RedisMock.HGet at\n%s", m.HGetMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RedisMock.HGet at\n%s with params: %#v", m.HGetMock.defaultExpectation.expectationOrigins.origin, *m.HGetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcHGet != nil && afterHGetCounter < 1 {
		m.t.Errorf("Expected call to RedisMock.HGet at\n%s", m.funcHGetOrigin)
	}

	if !m.HGetMock.invocationsDone() && afterHGetCounter > 0 {
		m.t.Errorf("Expected %d calls to RedisMock.HGet at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.HGetMock.expectedInvocations), m.HGetMock.expectedInvocationsOrigin, afterHGetCounter)
	}
}

type mRedisMockHSet struct {
	optional           bool
	mock               *RedisMock
	defaultExpectation *RedisMockHSetExpectation
	expectations       []*RedisMockHSetExpectation

	callArgs []*RedisMockHSetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RedisMockHSetExpectation specifies expectation struct of the redis.HSet
type RedisMockHSetExpectation struct {
	mock               *RedisMock
	params             *RedisMockHSetParams
	paramPtrs          *RedisMockHSetParamPtrs
	expectationOrigins RedisMockHSetExpectationOrigins
	results            *RedisMockHSetResults
	returnOrigin       string
	Counter            uint64
}

// RedisMockHSetParams contains parameters of the redis.HSet
type RedisMockHSetParams struct {
	ctx    context.Context
	key    string
	values []interface{}
}

// RedisMockHSetParamPtrs contains pointers to parameters of the redis.HSet
type RedisMockHSetParamPtrs struct {
	ctx    *context.Context
	key    *string
	values *[]interface{}
}

// RedisMockHSetResults contains results of the redis.HSet
type RedisMockHSetResults struct {
	err error
}

// RedisMockHSetOrigins contains origins of expectations of the redis.HSet
type RedisMockHSetExpectationOrigins struct {
	origin       string
	originCtx    string
	originKey    string
	originValues string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmHSet *mRedisMockHSet) Optional() *mRedisMockHSet {
	mmHSet.optional = true
	return mmHSet
}

// Expect sets up expected params for redis.HSet
func (mmHSet *mRedisMockHSet) Expect(ctx context.Context, key string, values ...interface{}) *mRedisMockHSet {
	if mmHSet.mock.funcHSet != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Set")
	}

	if mmHSet.defaultExpectation == nil {
		mmHSet.defaultExpectation = &RedisMockHSetExpectation{}
	}

	if mmHSet.defaultExpectation.paramPtrs != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by ExpectParams functions")
	}

	mmHSet.defaultExpectation.params = &RedisMockHSetParams{ctx, key, values}
	mmHSet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmHSet.expectations {
		if minimock.Equal(e.params, mmHSet.defaultExpectation.params) {
			mmHSet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmHSet.defaultExpectation.params)
		}
	}

	return mmHSet
}

// ExpectCtxParam1 sets up expected param ctx for redis.HSet
func (mmHSet *mRedisMockHSet) ExpectCtxParam1(ctx context.Context) *mRedisMockHSet {
	if mmHSet.mock.funcHSet != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Set")
	}

	if mmHSet.defaultExpectation == nil {
		mmHSet.defaultExpectation = &RedisMockHSetExpectation{}
	}

	if mmHSet.defaultExpectation.params != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Expect")
	}

	if mmHSet.defaultExpectation.paramPtrs == nil {
		mmHSet.defaultExpectation.paramPtrs = &RedisMockHSetParamPtrs{}
	}
	mmHSet.defaultExpectation.paramPtrs.ctx = &ctx
	mmHSet.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmHSet
}

// ExpectKeyParam2 sets up expected param key for redis.HSet
func (mmHSet *mRedisMockHSet) ExpectKeyParam2(key string) *mRedisMockHSet {
	if mmHSet.mock.funcHSet != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Set")
	}

	if mmHSet.defaultExpectation == nil {
		mmHSet.defaultExpectation = &RedisMockHSetExpectation{}
	}

	if mmHSet.defaultExpectation.params != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Expect")
	}

	if mmHSet.defaultExpectation.paramPtrs == nil {
		mmHSet.defaultExpectation.paramPtrs = &RedisMockHSetParamPtrs{}
	}
	mmHSet.defaultExpectation.paramPtrs.key = &key
	mmHSet.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmHSet
}

// ExpectValuesParam3 sets up expected param values for redis.HSet
func (mmHSet *mRedisMockHSet) ExpectValuesParam3(values ...interface{}) *mRedisMockHSet {
	if mmHSet.mock.funcHSet != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Set")
	}

	if mmHSet.defaultExpectation == nil {
		mmHSet.defaultExpectation = &RedisMockHSetExpectation{}
	}

	if mmHSet.defaultExpectation.params != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Expect")
	}

	if mmHSet.defaultExpectation.paramPtrs == nil {
		mmHSet.defaultExpectation.paramPtrs = &RedisMockHSetParamPtrs{}
	}
	mmHSet.defaultExpectation.paramPtrs.values = &values
	mmHSet.defaultExpectation.expectationOrigins.originValues = minimock.CallerInfo(1)

	return mmHSet
}

// Inspect accepts an inspector function that has same arguments as the redis.HSet
func (mmHSet *mRedisMockHSet) Inspect(f func(ctx context.Context, key string, values ...interface{})) *mRedisMockHSet {
	if mmHSet.mock.inspectFuncHSet != nil {
		mmHSet.mock.t.Fatalf("Inspect function is already set for RedisMock.HSet")
	}

	mmHSet.mock.inspectFuncHSet = f

	return mmHSet
}

// Return sets up results that will be returned by redis.HSet
func (mmHSet *mRedisMockHSet) Return(err error) *RedisMock {
	if mmHSet.mock.funcHSet != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Set")
	}

	if mmHSet.defaultExpectation == nil {
		mmHSet.defaultExpectation = &RedisMockHSetExpectation{mock: mmHSet.mock}
	}
	mmHSet.defaultExpectation.results = &RedisMockHSetResults{err}
	mmHSet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmHSet.mock
}

// Set uses given function f to mock the redis.HSet method
func (mmHSet *mRedisMockHSet) Set(f func(ctx context.Context, key string, values ...interface{}) (err error)) *RedisMock {
	if mmHSet.defaultExpectation != nil {
		mmHSet.mock.t.Fatalf("Default expectation is already set for the redis.HSet method")
	}

	if len(mmHSet.expectations) > 0 {
		mmHSet.mock.t.Fatalf("Some expectations are already set for the redis.HSet method")
	}

	mmHSet.mock.funcHSet = f
	mmHSet.mock.funcHSetOrigin = minimock.CallerInfo(1)
	return mmHSet.mock
}

// When sets expectation for the redis.HSet which will trigger the result defined by the following
// Then helper
func (mmHSet *mRedisMockHSet) When(ctx context.Context, key string, values ...interface{}) *RedisMockHSetExpectation {
	if mmHSet.mock.funcHSet != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Set")
	}

	expectation := &RedisMockHSetExpectation{
		mock:               mmHSet.mock,
		params:             &RedisMockHSetParams{ctx, key, values},
		expectationOrigins: RedisMockHSetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmHSet.expectations = append(mmHSet.expectations, expectation)
	return expectation
}

// Then sets up redis.HSet return parameters for the expectation previously defined by the When method
func (e *RedisMockHSetExpectation) Then(err error) *RedisMock {
	e.results = &RedisMockHSetResults{err}
	return e.mock
}

// Times sets number of times redis.HSet should be invoked
func (mmHSet *mRedisMockHSet) Times(n uint64) *mRedisMockHSet {
	if n == 0 {
		mmHSet.mock.t.Fatalf("Times of RedisMock.HSet mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmHSet.expectedInvocations, n)
	mmHSet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmHSet
}

func (mmHSet *mRedisMockHSet) invocationsDone() bool {
	if len(mmHSet.expectations) == 0 && mmHSet.defaultExpectation == nil && mmHSet.mock.funcHSet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmHSet.mock.afterHSetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmHSet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// HSet implements redis
func (mmHSet *RedisMock) HSet(ctx context.Context, key string, values ...interface{}) (err error) {
	mm_atomic.AddUint64(&mmHSet.beforeHSetCounter, 1)
	defer mm_atomic.AddUint64(&mmHSet.afterHSetCounter, 1)

	mmHSet.t.Helper()

	if mmHSet.inspectFuncHSet != nil {
		mmHSet.inspectFuncHSet(ctx, key, values...)
	}

	mm_params := RedisMockHSetParams{ctx, key, values}

	// Record call args
	mmHSet.HSetMock.mutex.Lock()
	mmHSet.HSetMock.callArgs = append(mmHSet.HSetMock.callArgs, &mm_params)
	mmHSet.HSetMock.mutex.Unlock()

	for _, e := range mmHSet.HSetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmHSet.HSetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmHSet.HSetMock.defaultExpectation.Counter, 1)
		mm_want := mmHSet.HSetMock.defaultExpectation.params
		mm_want_ptrs := mmHSet.HSetMock.defaultExpectation.paramPtrs

		mm_got := RedisMockHSetParams{ctx, key, values}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmHSet.t.Errorf("RedisMock.HSet got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHSet.HSetMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmHSet.t.Errorf("RedisMock.HSet got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHSet.HSetMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

			if mm_want_ptrs.values != nil && !minimock.Equal(*mm_want_ptrs.values, mm_got.values) {
				mmHSet.t.Errorf("RedisMock.HSet got unexpected parameter values, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHSet.HSetMock.defaultExpectation.expectationOrigins.originValues, *mm_want_ptrs.values, mm_got.values, minimock.Diff(*mm_want_ptrs.values, mm_got.values))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmHSet.t.Errorf("RedisMock.HSet got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmHSet.HSetMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmHSet.HSetMock.defaultExpectation.results
		if mm_results == nil {
			mmHSet.t.Fatal("No results are set for the RedisMock.HSet")
		}
		return (*mm_results).err
	}
	if mmHSet.funcHSet != nil {
		return mmHSet.funcHSet(ctx, key, values...)
	}
	mmHSet.t.Fatalf("Unexpected call to RedisMock.HSet. %v %v %v", ctx, key, values)
	return
}

// HSetAfterCounter returns a count of finished RedisMock.HSet invocations
func (mmHSet *RedisMock) HSetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHSet.afterHSetCounter)
}

// HSetBeforeCounter returns a count of RedisMock.HSet invocations
func (mmHSet *RedisMock) HSetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHSet.beforeHSetCounter)
}

// Calls returns a list of arguments used in each call to RedisMock.HSet.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmHSet *mRedisMockHSet) Calls() []*RedisMockHSetParams {
	mmHSet.mutex.RLock()

	argCopy := make([]*RedisMockHSetParams, len(mmHSet.callArgs))
	copy(argCopy, mmHSet.callArgs)

	mmHSet.mutex.RUnlock()

	return argCopy
}

// MinimockHSetDone returns true if the count of the HSet invocations corresponds
// the number of defined expectations
func (m *RedisMock) MinimockHSetDone() bool {
	if m.HSetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.HSetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.HSetMock.invocationsDone()
}

// MinimockHSetInspect logs each unmet expectation
func (m *RedisMock) MinimockHSetInspect() {
	for _, e := range m.HSetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RedisMock.HSet at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterHSetCounter := mm_atomic.LoadUint64(&m.afterHSetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.HSetMock.defaultExpectation != nil && afterHSetCounter < 1 {
		if m.HSetMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RedisMock.HSet at\n%s", m.HSetMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RedisMock.HSet at\n%s with params: %#v", m.HSetMock.defaultExpectation.expectationOrigins.origin, *m.HSetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcHSet != nil && afterHSetCounter < 1 {
		m.t.Errorf("Expected call to RedisMock.HSet at\n%s", m.funcHSetOrigin)
	}

	if !m.HSetMock.invocationsDone() && afterHSetCounter > 0 {
		m.t.Errorf("Expected %d calls to RedisMock.HSet at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.HSetMock.expectedInvocations), m.HSetMock.expectedInvocationsOrigin, afterHSetCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RedisMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockHGetInspect()

			m.MinimockHSetInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RedisMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RedisMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockHGetDone() &&
		m.MinimockHSetDone()
}
