// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package message

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/nskondratev/socks5-proxy-server/proxy/internal/bot/store"
)

// StoreIMock implements storeI
type StoreIMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateUser          func(ctx context.Context, username string, password string) (err error)
	funcCreateUserOrigin    string
	inspectFuncCreateUser   func(ctx context.Context, username string, password string)
	afterCreateUserCounter  uint64
	beforeCreateUserCounter uint64
	CreateUserMock          mStoreIMockCreateUser

	funcDeleteUser          func(ctx context.Context, username string) (err error)
	funcDeleteUserOrigin    string
	inspectFuncDeleteUser   func(ctx context.Context, username string)
	afterDeleteUserCounter  uint64
	beforeDeleteUserCounter uint64
	DeleteUserMock          mStoreIMockDeleteUser

	funcGetUserState          func(ctx context.Context, username string) (up1 *store.UserState, err error)
	funcGetUserStateOrigin    string
	inspectFuncGetUserState   func(ctx context.Context, username string)
	afterGetUserStateCounter  uint64
	beforeGetUserStateCounter uint64
	GetUserStateMock          mStoreIMockGetUserState

	funcIsUsernameFree          func(ctx context.Context, username string) (b1 bool, err error)
	funcIsUsernameFreeOrigin    string
	inspectFuncIsUsernameFree   func(ctx context.Context, username string)
	afterIsUsernameFreeCounter  uint64
	beforeIsUsernameFreeCounter uint64
	IsUsernameFreeMock          mStoreIMockIsUsernameFree

	funcSetUserState          func(ctx context.Context, username string, state store.UserState) (err error)
	funcSetUserStateOrigin    string
	inspectFuncSetUserState   func(ctx context.Context, username string, state store.UserState)
	afterSetUserStateCounter  uint64
	beforeSetUserStateCounter uint64
	SetUserStateMock          mStoreIMockSetUserState
}

// NewStoreIMock returns a mock for storeI
func NewStoreIMock(t minimock.Tester) *StoreIMock {
	m := &StoreIMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateUserMock = mStoreIMockCreateUser{mock: m}
	m.CreateUserMock.callArgs = []*StoreIMockCreateUserParams{}

	m.DeleteUserMock = mStoreIMockDeleteUser{mock: m}
	m.DeleteUserMock.callArgs = []*StoreIMockDeleteUserParams{}

	m.GetUserStateMock = mStoreIMockGetUserState{mock: m}
	m.GetUserStateMock.callArgs = []*StoreIMockGetUserStateParams{}

	m.IsUsernameFreeMock = mStoreIMockIsUsernameFree{mock: m}
	m.IsUsernameFreeMock.callArgs = []*StoreIMockIsUsernameFreeParams{}

	m.SetUserStateMock = mStoreIMockSetUserState{mock: m}
	m.SetUserStateMock.callArgs = []*StoreIMockSetUserStateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStoreIMockCreateUser struct {
	optional           bool
	mock               *StoreIMock
	defaultExpectation *StoreIMockCreateUserExpectation
	expectations       []*StoreIMockCreateUserExpectation

	callArgs []*StoreIMockCreateUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreIMockCreateUserExpectation specifies expectation struct of the storeI.CreateUser
type StoreIMockCreateUserExpectation struct {
	mock               *StoreIMock
	params             *StoreIMockCreateUserParams
	paramPtrs          *StoreIMockCreateUserParamPtrs
	expectationOrigins StoreIMockCreateUserExpectationOrigins
	results            *StoreIMockCreateUserResults
	returnOrigin       string
	Counter            uint64
}

// StoreIMockCreateUserParams contains parameters of the storeI.CreateUser
type StoreIMockCreateUserParams struct {
	ctx      context.Context
	username string
	password string
}

// StoreIMockCreateUserParamPtrs contains pointers to parameters of the storeI.CreateUser
type StoreIMockCreateUserParamPtrs struct {
	ctx      *context.Context
	username *string
	password *string
}

// StoreIMockCreateUserResults contains results of the storeI.CreateUser
type StoreIMockCreateUserResults struct {
	err error
}

// StoreIMockCreateUserOrigins contains origins of expectations of the storeI.CreateUser
type StoreIMockCreateUserExpectationOrigins struct {
	origin         string
	originCtx      string
	originUsername string
	originPassword string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateUser *mStoreIMockCreateUser) Optional() *mStoreIMockCreateUser {
	mmCreateUser.optional = true
	return mmCreateUser
}

// Expect sets up expected params for storeI.CreateUser
func (mmCreateUser *mStoreIMockCreateUser) Expect(ctx context.Context, username string, password string) *mStoreIMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("StoreIMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &StoreIMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.paramPtrs != nil {
		mmCreateUser.mock.t.Fatalf("StoreIMock.CreateUser mock is already set by ExpectParams functions")
	}

	mmCreateUser.defaultExpectation.params = &StoreIMockCreateUserParams{ctx, username, password}
	mmCreateUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateUser.expectations {
		if minimock.Equal(e.params, mmCreateUser.defaultExpectation.params) {
			mmCreateUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateUser.defaultExpectation.params)
		}
	}

	return mmCreateUser
}

// ExpectCtxParam1 sets up expected param ctx for storeI.CreateUser
func (mmCreateUser *mStoreIMockCreateUser) ExpectCtxParam1(ctx context.Context) *mStoreIMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("StoreIMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &StoreIMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.params != nil {
		mmCreateUser.mock.t.Fatalf("StoreIMock.CreateUser mock is already set by Expect")
	}

	if mmCreateUser.defaultExpectation.paramPtrs == nil {
		mmCreateUser.defaultExpectation.paramPtrs = &StoreIMockCreateUserParamPtrs{}
	}
	mmCreateUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateUser
}

// ExpectUsernameParam2 sets up expected param username for storeI.CreateUser
func (mmCreateUser *mStoreIMockCreateUser) ExpectUsernameParam2(username string) *mStoreIMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("StoreIMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &StoreIMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.params != nil {
		mmCreateUser.mock.t.Fatalf("StoreIMock.CreateUser mock is already set by Expect")
	}

	if mmCreateUser.defaultExpectation.paramPtrs == nil {
		mmCreateUser.defaultExpectation.paramPtrs = &StoreIMockCreateUserParamPtrs{}
	}
	mmCreateUser.defaultExpectation.paramPtrs.username = &username
	mmCreateUser.defaultExpectation.expectationOrigins.originUsername = minimock.CallerInfo(1)

	return mmCreateUser
}

// ExpectPasswordParam3 sets up expected param password for storeI.CreateUser
func (mmCreateUser *mStoreIMockCreateUser) ExpectPasswordParam3(password string) *mStoreIMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("StoreIMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &StoreIMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.params != nil {
		mmCreateUser.mock.t.Fatalf("StoreIMock.CreateUser mock is already set by Expect")
	}

	if mmCreateUser.defaultExpectation.paramPtrs == nil {
		mmCreateUser.defaultExpectation.paramPtrs = &StoreIMockCreateUserParamPtrs{}
	}
	mmCreateUser.defaultExpectation.paramPtrs.password = &password
	mmCreateUser.defaultExpectation.expectationOrigins.originPassword = minimock.CallerInfo(1)

	return mmCreateUser
}

// Inspect accepts an inspector function that has same arguments as the storeI.CreateUser
func (mmCreateUser *mStoreIMockCreateUser) Inspect(f func(ctx context.Context, username string, password string)) *mStoreIMockCreateUser {
	if mmCreateUser.mock.inspectFuncCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("Inspect function is already set for StoreIMock.CreateUser")
	}

	mmCreateUser.mock.inspectFuncCreateUser = f

	return mmCreateUser
}

// Return sets up results that will be returned by storeI.CreateUser
func (mmCreateUser *mStoreIMockCreateUser) Return(err error) *StoreIMock {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("StoreIMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &StoreIMockCreateUserExpectation{mock: mmCreateUser.mock}
	}
	mmCreateUser.defaultExpectation.results = &StoreIMockCreateUserResults{err}
	mmCreateUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateUser.mock
}

// Set uses given function f to mock the storeI.CreateUser method
func (mmCreateUser *mStoreIMockCreateUser) Set(f func(ctx context.Context, username string, password string) (err error)) *StoreIMock {
	if mmCreateUser.defaultExpectation != nil {
		mmCreateUser.mock.t.Fatalf("Default expectation is already set for the storeI.CreateUser method")
	}

	if len(mmCreateUser.expectations) > 0 {
		mmCreateUser.mock.t.Fatalf("Some expectations are already set for the storeI.CreateUser method")
	}

	mmCreateUser.mock.funcCreateUser = f
	mmCreateUser.mock.funcCreateUserOrigin = minimock.CallerInfo(1)
	return mmCreateUser.mock
}

// When sets expectation for the storeI.CreateUser which will trigger the result defined by the following
// Then helper
func (mmCreateUser *mStoreIMockCreateUser) When(ctx context.Context, username string, password string) *StoreIMockCreateUserExpectation {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("StoreIMock.CreateUser mock is already set by Set")
	}

	expectation := &StoreIMockCreateUserExpectation{
		mock:               mmCreateUser.mock,
		params:             &StoreIMockCreateUserParams{ctx, username, password},
		expectationOrigins: StoreIMockCreateUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateUser.expectations = append(mmCreateUser.expectations, expectation)
	return expectation
}

// Then sets up storeI.CreateUser return parameters for the expectation previously defined by the When method
func (e *StoreIMockCreateUserExpectation) Then(err error) *StoreIMock {
	e.results = &StoreIMockCreateUserResults{err}
	return e.mock
}

// Times sets number of times storeI.CreateUser should be invoked
func (mmCreateUser *mStoreIMockCreateUser) Times(n uint64) *mStoreIMockCreateUser {
	if n == 0 {
		mmCreateUser.mock.t.Fatalf("Times of StoreIMock.CreateUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateUser.expectedInvocations, n)
	mmCreateUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateUser
}

func (mmCreateUser *mStoreIMockCreateUser) invocationsDone() bool {
	if len(mmCreateUser.expectations) == 0 && mmCreateUser.defaultExpectation == nil && mmCreateUser.mock.funcCreateUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateUser.mock.afterCreateUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateUser implements storeI
func (mmCreateUser *StoreIMock) CreateUser(ctx context.Context, username string, password string) (err error) {
	mm_atomic.AddUint64(&mmCreateUser.beforeCreateUserCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateUser.afterCreateUserCounter, 1)

	mmCreateUser.t.Helper()

	if mmCreateUser.inspectFuncCreateUser != nil {
		mmCreateUser.inspectFuncCreateUser(ctx, username, password)
	}

	mm_params := StoreIMockCreateUserParams{ctx, username, password}

	// Record call args
	mmCreateUser.CreateUserMock.mutex.Lock()
	mmCreateUser.CreateUserMock.callArgs = append(mmCreateUser.CreateUserMock.callArgs, &mm_params)
	mmCreateUser.CreateUserMock.mutex.Unlock()

	for _, e := range mmCreateUser.CreateUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCreateUser.CreateUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateUser.CreateUserMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateUser.CreateUserMock.defaultExpectation.params
		mm_want_ptrs := mmCreateUser.CreateUserMock.defaultExpectation.paramPtrs

		mm_got := StoreIMockCreateUserParams{ctx, username, password}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateUser.t.Errorf("StoreIMock.CreateUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.username != nil && !minimock.Equal(*mm_want_ptrs.username, mm_got.username) {
				mmCreateUser.t.Errorf("StoreIMock.CreateUser got unexpected parameter username, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.originUsername, *mm_want_ptrs.username, mm_got.username, minimock.Diff(*mm_want_ptrs.username, mm_got.username))
			}

			if mm_want_ptrs.password != nil && !minimock.Equal(*mm_want_ptrs.password, mm_got.password) {
				mmCreateUser.t.Errorf("StoreIMock.CreateUser got unexpected parameter password, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.originPassword, *mm_want_ptrs.password, mm_got.password, minimock.Diff(*mm_want_ptrs.password, mm_got.password))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateUser.t.Errorf("StoreIMock.CreateUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateUser.CreateUserMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateUser.t.Fatal("No results are set for the StoreIMock.CreateUser")
		}
		return (*mm_results).err
	}
	if mmCreateUser.funcCreateUser != nil {
		return mmCreateUser.funcCreateUser(ctx, username, password)
	}
	mmCreateUser.t.Fatalf("Unexpected call to StoreIMock.CreateUser. %v %v %v", ctx, username, password)
	return
}

// CreateUserAfterCounter returns a count of finished StoreIMock.CreateUser invocations
func (mmCreateUser *StoreIMock) CreateUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateUser.afterCreateUserCounter)
}

// CreateUserBeforeCounter returns a count of StoreIMock.CreateUser invocations
func (mmCreateUser *StoreIMock) CreateUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateUser.beforeCreateUserCounter)
}

// Calls returns a list of arguments used in each call to StoreIMock.CreateUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateUser *mStoreIMockCreateUser) Calls() []*StoreIMockCreateUserParams {
	mmCreateUser.mutex.RLock()

	argCopy := make([]*StoreIMockCreateUserParams, len(mmCreateUser.callArgs))
	copy(argCopy, mmCreateUser.callArgs)

	mmCreateUser.mutex.RUnlock()

	return argCopy
}

// MinimockCreateUserDone returns true if the count of the CreateUser invocations corresponds
// the number of defined expectations
func (m *StoreIMock) MinimockCreateUserDone() bool {
	if m.CreateUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateUserMock.invocationsDone()
}

// MinimockCreateUserInspect logs each unmet expectation
func (m *StoreIMock) MinimockCreateUserInspect() {
	for _, e := range m.CreateUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreIMock.CreateUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateUserCounter := mm_atomic.LoadUint64(&m.afterCreateUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateUserMock.defaultExpectation != nil && afterCreateUserCounter < 1 {
		if m.CreateUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreIMock.CreateUser at\n%s", m.CreateUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreIMock.CreateUser at\n%s with params: %#v", m.CreateUserMock.defaultExpectation.expectationOrigins.origin, *m.CreateUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateUser != nil && afterCreateUserCounter < 1 {
		m.t.Errorf("Expected call to StoreIMock.CreateUser at\n%s", m.funcCreateUserOrigin)
	}

	if !m.CreateUserMock.invocationsDone() && afterCreateUserCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreIMock.CreateUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateUserMock.expectedInvocations), m.CreateUserMock.expectedInvocationsOrigin, afterCreateUserCounter)
	}
}

type mStoreIMockDeleteUser struct {
	optional           bool
	mock               *StoreIMock
	defaultExpectation *StoreIMockDeleteUserExpectation
	expectations       []*StoreIMockDeleteUserExpectation

	callArgs []*StoreIMockDeleteUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreIMockDeleteUserExpectation specifies expectation struct of the storeI.DeleteUser
type StoreIMockDeleteUserExpectation struct {
	mock               *StoreIMock
	params             *StoreIMockDeleteUserParams
	paramPtrs          *StoreIMockDeleteUserParamPtrs
	expectationOrigins StoreIMockDeleteUserExpectationOrigins
	results            *StoreIMockDeleteUserResults
	returnOrigin       string
	Counter            uint64
}

// StoreIMockDeleteUserParams contains parameters of the storeI.DeleteUser
type StoreIMockDeleteUserParams struct {
	ctx      context.Context
	username string
}

// StoreIMockDeleteUserParamPtrs contains pointers to parameters of the storeI.DeleteUser
type StoreIMockDeleteUserParamPtrs struct {
	ctx      *context.Context
	username *string
}

// StoreIMockDeleteUserResults contains results of the storeI.DeleteUser
type StoreIMockDeleteUserResults struct {
	err error
}

// StoreIMockDeleteUserOrigins contains origins of expectations of the storeI.DeleteUser
type StoreIMockDeleteUserExpectationOrigins struct {
	origin         string
	originCtx      string
	originUsername string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteUser *mStoreIMockDeleteUser) Optional() *mStoreIMockDeleteUser {
	mmDeleteUser.optional = true
	return mmDeleteUser
}

// Expect sets up expected params for storeI.DeleteUser
func (mmDeleteUser *mStoreIMockDeleteUser) Expect(ctx context.Context, username string) *mStoreIMockDeleteUser {
	if mmDeleteUser.mock.funcDeleteUser != nil {
		mmDeleteUser.mock.t.Fatalf("StoreIMock.DeleteUser mock is already set by Set")
	}

	if mmDeleteUser.defaultExpectation == nil {
		mmDeleteUser.defaultExpectation = &StoreIMockDeleteUserExpectation{}
	}

	if mmDeleteUser.defaultExpectation.paramPtrs != nil {
		mmDeleteUser.mock.t.Fatalf("StoreIMock.DeleteUser mock is already set by ExpectParams functions")
	}

	mmDeleteUser.defaultExpectation.params = &StoreIMockDeleteUserParams{ctx, username}
	mmDeleteUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteUser.expectations {
		if minimock.Equal(e.params, mmDeleteUser.defaultExpectation.params) {
			mmDeleteUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteUser.defaultExpectation.params)
		}
	}

	return mmDeleteUser
}

// ExpectCtxParam1 sets up expected param ctx for storeI.DeleteUser
func (mmDeleteUser *mStoreIMockDeleteUser) ExpectCtxParam1(ctx context.Context) *mStoreIMockDeleteUser {
	if mmDeleteUser.mock.funcDeleteUser != nil {
		mmDeleteUser.mock.t.Fatalf("StoreIMock.DeleteUser mock is already set by Set")
	}

	if mmDeleteUser.defaultExpectation == nil {
		mmDeleteUser.defaultExpectation = &StoreIMockDeleteUserExpectation{}
	}

	if mmDeleteUser.defaultExpectation.params != nil {
		mmDeleteUser.mock.t.Fatalf("StoreIMock.DeleteUser mock is already set by Expect")
	}

	if mmDeleteUser.defaultExpectation.paramPtrs == nil {
		mmDeleteUser.defaultExpectation.paramPtrs = &StoreIMockDeleteUserParamPtrs{}
	}
	mmDeleteUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteUser
}

// ExpectUsernameParam2 sets up expected param username for storeI.DeleteUser
func (mmDeleteUser *mStoreIMockDeleteUser) ExpectUsernameParam2(username string) *mStoreIMockDeleteUser {
	if mmDeleteUser.mock.funcDeleteUser != nil {
		mmDeleteUser.mock.t.Fatalf("StoreIMock.DeleteUser mock is already set by Set")
	}

	if mmDeleteUser.defaultExpectation == nil {
		mmDeleteUser.defaultExpectation = &StoreIMockDeleteUserExpectation{}
	}

	if mmDeleteUser.defaultExpectation.params != nil {
		mmDeleteUser.mock.t.Fatalf("StoreIMock.DeleteUser mock is already set by Expect")
	}

	if mmDeleteUser.defaultExpectation.paramPtrs == nil {
		mmDeleteUser.defaultExpectation.paramPtrs = &StoreIMockDeleteUserParamPtrs{}
	}
	mmDeleteUser.defaultExpectation.paramPtrs.username = &username
	mmDeleteUser.defaultExpectation.expectationOrigins.originUsername = minimock.CallerInfo(1)

	return mmDeleteUser
}

// Inspect accepts an inspector function that has same arguments as the storeI.DeleteUser
func (mmDeleteUser *mStoreIMockDeleteUser) Inspect(f func(ctx context.Context, username string)) *mStoreIMockDeleteUser {
	if mmDeleteUser.mock.inspectFuncDeleteUser != nil {
		mmDeleteUser.mock.t.Fatalf("Inspect function is already set for StoreIMock.DeleteUser")
	}

	mmDeleteUser.mock.inspectFuncDeleteUser = f

	return mmDeleteUser
}

// Return sets up results that will be returned by storeI.DeleteUser
func (mmDeleteUser *mStoreIMockDeleteUser) Return(err error) *StoreIMock {
	if mmDeleteUser.mock.funcDeleteUser != nil {
		mmDeleteUser.mock.t.Fatalf("StoreIMock.DeleteUser mock is already set by Set")
	}

	if mmDeleteUser.defaultExpectation == nil {
		mmDeleteUser.defaultExpectation = &StoreIMockDeleteUserExpectation{mock: mmDeleteUser.mock}
	}
	mmDeleteUser.defaultExpectation.results = &StoreIMockDeleteUserResults{err}
	mmDeleteUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteUser.mock
}

// Set uses given function f to mock the storeI.DeleteUser method
func (mmDeleteUser *mStoreIMockDeleteUser) Set(f func(ctx context.Context, username string) (err error)) *StoreIMock {
	if mmDeleteUser.defaultExpectation != nil {
		mmDeleteUser.mock.t.Fatalf("Default expectation is already set for the storeI.DeleteUser method")
	}

	if len(mmDeleteUser.expectations) > 0 {
		mmDeleteUser.mock.t.Fatalf("Some expectations are already set for the storeI.DeleteUser method")
	}

	mmDeleteUser.mock.funcDeleteUser = f
	mmDeleteUser.mock.funcDeleteUserOrigin = minimock.CallerInfo(1)
	return mmDeleteUser.mock
}

// When sets expectation for the storeI.DeleteUser which will trigger the result defined by the following
// Then helper
func (mmDeleteUser *mStoreIMockDeleteUser) When(ctx context.Context, username string) *StoreIMockDeleteUserExpectation {
	if mmDeleteUser.mock.funcDeleteUser != nil {
		mmDeleteUser.mock.t.Fatalf("StoreIMock.DeleteUser mock is already set by Set")
	}

	expectation := &StoreIMockDeleteUserExpectation{
		mock:               mmDeleteUser.mock,
		params:             &StoreIMockDeleteUserParams{ctx, username},
		expectationOrigins: StoreIMockDeleteUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteUser.expectations = append(mmDeleteUser.expectations, expectation)
	return expectation
}

// Then sets up storeI.DeleteUser return parameters for the expectation previously defined by the When method
func (e *StoreIMockDeleteUserExpectation) Then(err error) *StoreIMock {
	e.results = &StoreIMockDeleteUserResults{err}
	return e.mock
}

// Times sets number of times storeI.DeleteUser should be invoked
func (mmDeleteUser *mStoreIMockDeleteUser) Times(n uint64) *mStoreIMockDeleteUser {
	if n == 0 {
		mmDeleteUser.mock.t.Fatalf("Times of StoreIMock.DeleteUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteUser.expectedInvocations, n)
	mmDeleteUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteUser
}

func (mmDeleteUser *mStoreIMockDeleteUser) invocationsDone() bool {
	if len(mmDeleteUser.expectations) == 0 && mmDeleteUser.defaultExpectation == nil && mmDeleteUser.mock.funcDeleteUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteUser.mock.afterDeleteUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteUser implements storeI
func (mmDeleteUser *StoreIMock) DeleteUser(ctx context.Context, username string) (err error) {
	mm_atomic.AddUint64(&mmDeleteUser.beforeDeleteUserCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteUser.afterDeleteUserCounter, 1)

	mmDeleteUser.t.Helper()

	if mmDeleteUser.inspectFuncDeleteUser != nil {
		mmDeleteUser.inspectFuncDeleteUser(ctx, username)
	}

	mm_params := StoreIMockDeleteUserParams{ctx, username}

	// Record call args
	mmDeleteUser.DeleteUserMock.mutex.Lock()
	mmDeleteUser.DeleteUserMock.callArgs = append(mmDeleteUser.DeleteUserMock.callArgs, &mm_params)
	mmDeleteUser.DeleteUserMock.mutex.Unlock()

	for _, e := range mmDeleteUser.DeleteUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteUser.DeleteUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteUser.DeleteUserMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteUser.DeleteUserMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteUser.DeleteUserMock.defaultExpectation.paramPtrs

		mm_got := StoreIMockDeleteUserParams{ctx, username}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteUser.t.Errorf("StoreIMock.DeleteUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteUser.DeleteUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.username != nil && !minimock.Equal(*mm_want_ptrs.username, mm_got.username) {
				mmDeleteUser.t.Errorf("StoreIMock.DeleteUser got unexpected parameter username, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteUser.DeleteUserMock.defaultExpectation.expectationOrigins.originUsername, *mm_want_ptrs.username, mm_got.username, minimock.Diff(*mm_want_ptrs.username, mm_got.username))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteUser.t.Errorf("StoreIMock.DeleteUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteUser.DeleteUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteUser.DeleteUserMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteUser.t.Fatal("No results are set for the StoreIMock.DeleteUser")
		}
		return (*mm_results).err
	}
	if mmDeleteUser.funcDeleteUser != nil {
		return mmDeleteUser.funcDeleteUser(ctx, username)
	}
	mmDeleteUser.t.Fatalf("Unexpected call to StoreIMock.DeleteUser. %v %v", ctx, username)
	return
}

// DeleteUserAfterCounter returns a count of finished StoreIMock.DeleteUser invocations
func (mmDeleteUser *StoreIMock) DeleteUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteUser.afterDeleteUserCounter)
}

// DeleteUserBeforeCounter returns a count of StoreIMock.DeleteUser invocations
func (mmDeleteUser *StoreIMock) DeleteUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteUser.beforeDeleteUserCounter)
}

// Calls returns a list of arguments used in each call to StoreIMock.DeleteUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteUser *mStoreIMockDeleteUser) Calls() []*StoreIMockDeleteUserParams {
	mmDeleteUser.mutex.RLock()

	argCopy := make([]*StoreIMockDeleteUserParams, len(mmDeleteUser.callArgs))
	copy(argCopy, mmDeleteUser.callArgs)

	mmDeleteUser.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteUserDone returns true if the count of the DeleteUser invocations corresponds
// the number of defined expectations
func (m *StoreIMock) MinimockDeleteUserDone() bool {
	if m.DeleteUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteUserMock.invocationsDone()
}

// MinimockDeleteUserInspect logs each unmet expectation
func (m *StoreIMock) MinimockDeleteUserInspect() {
	for _, e := range m.DeleteUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreIMock.DeleteUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteUserCounter := mm_atomic.LoadUint64(&m.afterDeleteUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteUserMock.defaultExpectation != nil && afterDeleteUserCounter < 1 {
		if m.DeleteUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreIMock.DeleteUser at\n%s", m.DeleteUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreIMock.DeleteUser at\n%s with params: %#v", m.DeleteUserMock.defaultExpectation.expectationOrigins.origin, *m.DeleteUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteUser != nil && afterDeleteUserCounter < 1 {
		m.t.Errorf("Expected call to StoreIMock.DeleteUser at\n%s", m.funcDeleteUserOrigin)
	}

	if !m.DeleteUserMock.invocationsDone() && afterDeleteUserCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreIMock.DeleteUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteUserMock.expectedInvocations), m.DeleteUserMock.expectedInvocationsOrigin, afterDeleteUserCounter)
	}
}

type mStoreIMockGetUserState struct {
	optional           bool
	mock               *StoreIMock
	defaultExpectation *StoreIMockGetUserStateExpectation
	expectations       []*StoreIMockGetUserStateExpectation

	callArgs []*StoreIMockGetUserStateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreIMockGetUserStateExpectation specifies expectation struct of the storeI.GetUserState
type StoreIMockGetUserStateExpectation struct {
	mock               *StoreIMock
	params             *StoreIMockGetUserStateParams
	paramPtrs          *StoreIMockGetUserStateParamPtrs
	expectationOrigins StoreIMockGetUserStateExpectationOrigins
	results            *StoreIMockGetUserStateResults
	returnOrigin       string
	Counter            uint64
}

// StoreIMockGetUserStateParams contains parameters of the storeI.GetUserState
type StoreIMockGetUserStateParams struct {
	ctx      context.Context
	username string
}

// StoreIMockGetUserStateParamPtrs contains pointers to parameters of the storeI.GetUserState
type StoreIMockGetUserStateParamPtrs struct {
	ctx      *context.Context
	username *string
}

// StoreIMockGetUserStateResults contains results of the storeI.GetUserState
type StoreIMockGetUserStateResults struct {
	up1 *store.UserState
	err error
}

// StoreIMockGetUserStateOrigins contains origins of expectations of the storeI.GetUserState
type StoreIMockGetUserStateExpectationOrigins struct {
	origin         string
	originCtx      string
	originUsername string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetUserState *mStoreIMockGetUserState) Optional() *mStoreIMockGetUserState {
	mmGetUserState.optional = true
	return mmGetUserState
}

// Expect sets up expected params for storeI.GetUserState
func (mmGetUserState *mStoreIMockGetUserState) Expect(ctx context.Context, username string) *mStoreIMockGetUserState {
	if mmGetUserState.mock.funcGetUserState != nil {
		mmGetUserState.mock.t.Fatalf("StoreIMock.GetUserState mock is already set by Set")
	}

	if mmGetUserState.defaultExpectation == nil {
		mmGetUserState.defaultExpectation = &StoreIMockGetUserStateExpectation{}
	}

	if mmGetUserState.defaultExpectation.paramPtrs != nil {
		mmGetUserState.mock.t.Fatalf("StoreIMock.GetUserState mock is already set by ExpectParams functions")
	}

	mmGetUserState.defaultExpectation.params = &StoreIMockGetUserStateParams{ctx, username}
	mmGetUserState.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetUserState.expectations {
		if minimock.Equal(e.params, mmGetUserState.defaultExpectation.params) {
			mmGetUserState.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetUserState.defaultExpectation.params)
		}
	}

	return mmGetUserState
}

// ExpectCtxParam1 sets up expected param ctx for storeI.GetUserState
func (mmGetUserState *mStoreIMockGetUserState) ExpectCtxParam1(ctx context.Context) *mStoreIMockGetUserState {
	if mmGetUserState.mock.funcGetUserState != nil {
		mmGetUserState.mock.t.Fatalf("StoreIMock.GetUserState mock is already set by Set")
	}

	if mmGetUserState.defaultExpectation == nil {
		mmGetUserState.defaultExpectation = &StoreIMockGetUserStateExpectation{}
	}

	if mmGetUserState.defaultExpectation.params != nil {
		mmGetUserState.mock.t.Fatalf("StoreIMock.GetUserState mock is already set by Expect")
	}

	if mmGetUserState.defaultExpectation.paramPtrs == nil {
		mmGetUserState.defaultExpectation.paramPtrs = &StoreIMockGetUserStateParamPtrs{}
	}
	mmGetUserState.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetUserState.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetUserState
}

// ExpectUsernameParam2 sets up expected param username for storeI.GetUserState
func (mmGetUserState *mStoreIMockGetUserState) ExpectUsernameParam2(username string) *mStoreIMockGetUserState {
	if mmGetUserState.mock.funcGetUserState != nil {
		mmGetUserState.mock.t.Fatalf("StoreIMock.GetUserState mock is already set by Set")
	}

	if mmGetUserState.defaultExpectation == nil {
		mmGetUserState.defaultExpectation = &StoreIMockGetUserStateExpectation{}
	}

	if mmGetUserState.defaultExpectation.params != nil {
		mmGetUserState.mock.t.Fatalf("StoreIMock.GetUserState mock is already set by Expect")
	}

	if mmGetUserState.defaultExpectation.paramPtrs == nil {
		mmGetUserState.defaultExpectation.paramPtrs = &StoreIMockGetUserStateParamPtrs{}
	}
	mmGetUserState.defaultExpectation.paramPtrs.username = &username
	mmGetUserState.defaultExpectation.expectationOrigins.originUsername = minimock.CallerInfo(1)

	return mmGetUserState
}

// Inspect accepts an inspector function that has same arguments as the storeI.GetUserState
func (mmGetUserState *mStoreIMockGetUserState) Inspect(f func(ctx context.Context, username string)) *mStoreIMockGetUserState {
	if mmGetUserState.mock.inspectFuncGetUserState != nil {
		mmGetUserState.mock.t.Fatalf("Inspect function is already set for StoreIMock.GetUserState")
	}

	mmGetUserState.mock.inspectFuncGetUserState = f

	return mmGetUserState
}

// Return sets up results that will be returned by storeI.GetUserState
func (mmGetUserState *mStoreIMockGetUserState) Return(up1 *store.UserState, err error) *StoreIMock {
	if mmGetUserState.mock.funcGetUserState != nil {
		mmGetUserState.mock.t.Fatalf("StoreIMock.GetUserState mock is already set by Set")
	}

	if mmGetUserState.defaultExpectation == nil {
		mmGetUserState.defaultExpectation = &StoreIMockGetUserStateExpectation{mock: mmGetUserState.mock}
	}
	mmGetUserState.defaultExpectation.results = &StoreIMockGetUserStateResults{up1, err}
	mmGetUserState.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetUserState.mock
}

// Set uses given function f to mock the storeI.GetUserState method
func (mmGetUserState *mStoreIMockGetUserState) Set(f func(ctx context.Context, username string) (up1 *store.UserState, err error)) *StoreIMock {
	if mmGetUserState.defaultExpectation != nil {
		mmGetUserState.mock.t.Fatalf("Default expectation is already set for the storeI.GetUserState method")
	}

	if len(mmGetUserState.expectations) > 0 {
		mmGetUserState.mock.t.Fatalf("Some expectations are already set for the storeI.GetUserState method")
	}

	mmGetUserState.mock.funcGetUserState = f
	mmGetUserState.mock.funcGetUserStateOrigin = minimock.CallerInfo(1)
	return mmGetUserState.mock
}

// When sets expectation for the storeI.GetUserState which will trigger the result defined by the following
// Then helper
func (mmGetUserState *mStoreIMockGetUserState) When(ctx context.Context, username string) *StoreIMockGetUserStateExpectation {
	if mmGetUserState.mock.funcGetUserState != nil {
		mmGetUserState.mock.t.Fatalf("StoreIMock.GetUserState mock is already set by Set")
	}

	expectation := &StoreIMockGetUserStateExpectation{
		mock:               mmGetUserState.mock,
		params:             &StoreIMockGetUserStateParams{ctx, username},
		expectationOrigins: StoreIMockGetUserStateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetUserState.expectations = append(mmGetUserState.expectations, expectation)
	return expectation
}

// Then sets up storeI.GetUserState return parameters for the expectation previously defined by the When method
func (e *StoreIMockGetUserStateExpectation) Then(up1 *store.UserState, err error) *StoreIMock {
	e.results = &StoreIMockGetUserStateResults{up1, err}
	return e.mock
}

// Times sets number of times storeI.GetUserState should be invoked
func (mmGetUserState *mStoreIMockGetUserState) Times(n uint64) *mStoreIMockGetUserState {
	if n == 0 {
		mmGetUserState.mock.t.Fatalf("Times of StoreIMock.GetUserState mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetUserState.expectedInvocations, n)
	mmGetUserState.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetUserState
}

func (mmGetUserState *mStoreIMockGetUserState) invocationsDone() bool {
	if len(mmGetUserState.expectations) == 0 && mmGetUserState.defaultExpectation == nil && mmGetUserState.mock.funcGetUserState == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetUserState.mock.afterGetUserStateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetUserState.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetUserState implements storeI
func (mmGetUserState *StoreIMock) GetUserState(ctx context.Context, username string) (up1 *store.UserState, err error) {
	mm_atomic.AddUint64(&mmGetUserState.beforeGetUserStateCounter, 1)
	defer mm_atomic.AddUint64(&mmGetUserState.afterGetUserStateCounter, 1)

	mmGetUserState.t.Helper()

	if mmGetUserState.inspectFuncGetUserState != nil {
		mmGetUserState.inspectFuncGetUserState(ctx, username)
	}

	mm_params := StoreIMockGetUserStateParams{ctx, username}

	// Record call args
	mmGetUserState.GetUserStateMock.mutex.Lock()
	mmGetUserState.GetUserStateMock.callArgs = append(mmGetUserState.GetUserStateMock.callArgs, &mm_params)
	mmGetUserState.GetUserStateMock.mutex.Unlock()

	for _, e := range mmGetUserState.GetUserStateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGetUserState.GetUserStateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetUserState.GetUserStateMock.defaultExpectation.Counter, 1)
		mm_want := mmGetUserState.GetUserStateMock.defaultExpectation.params
		mm_want_ptrs := mmGetUserState.GetUserStateMock.defaultExpectation.paramPtrs

		mm_got := StoreIMockGetUserStateParams{ctx, username}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetUserState.t.Errorf("StoreIMock.GetUserState got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserState.GetUserStateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.username != nil && !minimock.Equal(*mm_want_ptrs.username, mm_got.username) {
				mmGetUserState.t.Errorf("StoreIMock.GetUserState got unexpected parameter username, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserState.GetUserStateMock.defaultExpectation.expectationOrigins.originUsername, *mm_want_ptrs.username, mm_got.username, minimock.Diff(*mm_want_ptrs.username, mm_got.username))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetUserState.t.Errorf("StoreIMock.GetUserState got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetUserState.GetUserStateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetUserState.GetUserStateMock.defaultExpectation.results
		if mm_results == nil {
			mmGetUserState.t.Fatal("No results are set for the StoreIMock.GetUserState")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGetUserState.funcGetUserState != nil {
		return mmGetUserState.funcGetUserState(ctx, username)
	}
	mmGetUserState.t.Fatalf("Unexpected call to StoreIMock.GetUserState. %v %v", ctx, username)
	return
}

// GetUserStateAfterCounter returns a count of finished StoreIMock.GetUserState invocations
func (mmGetUserState *StoreIMock) GetUserStateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserState.afterGetUserStateCounter)
}

// GetUserStateBeforeCounter returns a count of StoreIMock.GetUserState invocations
func (mmGetUserState *StoreIMock) GetUserStateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserState.beforeGetUserStateCounter)
}

// Calls returns a list of arguments used in each call to StoreIMock.GetUserState.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetUserState *mStoreIMockGetUserState) Calls() []*StoreIMockGetUserStateParams {
	mmGetUserState.mutex.RLock()

	argCopy := make([]*StoreIMockGetUserStateParams, len(mmGetUserState.callArgs))
	copy(argCopy, mmGetUserState.callArgs)

	mmGetUserState.mutex.RUnlock()

	return argCopy
}

// MinimockGetUserStateDone returns true if the count of the GetUserState invocations corresponds
// the number of defined expectations
func (m *StoreIMock) MinimockGetUserStateDone() bool {
	if m.GetUserStateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetUserStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetUserStateMock.invocationsDone()
}

// MinimockGetUserStateInspect logs each unmet expectation
func (m *StoreIMock) MinimockGetUserStateInspect() {
	for _, e := range m.GetUserStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreIMock.GetUserState at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetUserStateCounter := mm_atomic.LoadUint64(&m.afterGetUserStateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetUserStateMock.defaultExpectation != nil && afterGetUserStateCounter < 1 {
		if m.GetUserStateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreIMock.GetUserState at\n%s", m.GetUserStateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreIMock.GetUserState at\n%s with params: %#v", m.GetUserStateMock.defaultExpectation.expectationOrigins.origin, *m.GetUserStateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetUserState != nil && afterGetUserStateCounter < 1 {
		m.t.Errorf("Expected call to StoreIMock.GetUserState at\n%s", m.funcGetUserStateOrigin)
	}

	if !m.GetUserStateMock.invocationsDone() && afterGetUserStateCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreIMock.GetUserState at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetUserStateMock.expectedInvocations), m.GetUserStateMock.expectedInvocationsOrigin, afterGetUserStateCounter)
	}
}

type mStoreIMockIsUsernameFree struct {
	optional           bool
	mock               *StoreIMock
	defaultExpectation *StoreIMockIsUsernameFreeExpectation
	expectations       []*StoreIMockIsUsernameFreeExpectation

	callArgs []*StoreIMockIsUsernameFreeParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreIMockIsUsernameFreeExpectation specifies expectation struct of the storeI.IsUsernameFree
type StoreIMockIsUsernameFreeExpectation struct {
	mock               *StoreIMock
	params             *StoreIMockIsUsernameFreeParams
	paramPtrs          *StoreIMockIsUsernameFreeParamPtrs
	expectationOrigins StoreIMockIsUsernameFreeExpectationOrigins
	results            *StoreIMockIsUsernameFreeResults
	returnOrigin       string
	Counter            uint64
}

// StoreIMockIsUsernameFreeParams contains parameters of the storeI.IsUsernameFree
type StoreIMockIsUsernameFreeParams struct {
	ctx      context.Context
	username string
}

// StoreIMockIsUsernameFreeParamPtrs contains pointers to parameters of the storeI.IsUsernameFree
type StoreIMockIsUsernameFreeParamPtrs struct {
	ctx      *context.Context
	username *string
}

// StoreIMockIsUsernameFreeResults contains results of the storeI.IsUsernameFree
type StoreIMockIsUsernameFreeResults struct {
	b1  bool
	err error
}

// StoreIMockIsUsernameFreeOrigins contains origins of expectations of the storeI.IsUsernameFree
type StoreIMockIsUsernameFreeExpectationOrigins struct {
	origin         string
	originCtx      string
	originUsername string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmIsUsernameFree *mStoreIMockIsUsernameFree) Optional() *mStoreIMockIsUsernameFree {
	mmIsUsernameFree.optional = true
	return mmIsUsernameFree
}

// Expect sets up expected params for storeI.IsUsernameFree
func (mmIsUsernameFree *mStoreIMockIsUsernameFree) Expect(ctx context.Context, username string) *mStoreIMockIsUsernameFree {
	if mmIsUsernameFree.mock.funcIsUsernameFree != nil {
		mmIsUsernameFree.mock.t.Fatalf("StoreIMock.IsUsernameFree mock is already set by Set")
	}

	if mmIsUsernameFree.defaultExpectation == nil {
		mmIsUsernameFree.defaultExpectation = &StoreIMockIsUsernameFreeExpectation{}
	}

	if mmIsUsernameFree.defaultExpectation.paramPtrs != nil {
		mmIsUsernameFree.mock.t.Fatalf("StoreIMock.IsUsernameFree mock is already set by ExpectParams functions")
	}

	mmIsUsernameFree.defaultExpectation.params = &StoreIMockIsUsernameFreeParams{ctx, username}
	mmIsUsernameFree.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmIsUsernameFree.expectations {
		if minimock.Equal(e.params, mmIsUsernameFree.defaultExpectation.params) {
			mmIsUsernameFree.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmIsUsernameFree.defaultExpectation.params)
		}
	}

	return mmIsUsernameFree
}

// ExpectCtxParam1 sets up expected param ctx for storeI.IsUsernameFree
func (mmIsUsernameFree *mStoreIMockIsUsernameFree) ExpectCtxParam1(ctx context.Context) *mStoreIMockIsUsernameFree {
	if mmIsUsernameFree.mock.funcIsUsernameFree != nil {
		mmIsUsernameFree.mock.t.Fatalf("StoreIMock.IsUsernameFree mock is already set by Set")
	}

	if mmIsUsernameFree.defaultExpectation == nil {
		mmIsUsernameFree.defaultExpectation = &StoreIMockIsUsernameFreeExpectation{}
	}

	if mmIsUsernameFree.defaultExpectation.params != nil {
		mmIsUsernameFree.mock.t.Fatalf("StoreIMock.IsUsernameFree mock is already set by Expect")
	}

	if mmIsUsernameFree.defaultExpectation.paramPtrs == nil {
		mmIsUsernameFree.defaultExpectation.paramPtrs = &StoreIMockIsUsernameFreeParamPtrs{}
	}
	mmIsUsernameFree.defaultExpectation.paramPtrs.ctx = &ctx
	mmIsUsernameFree.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmIsUsernameFree
}

// ExpectUsernameParam2 sets up expected param username for storeI.IsUsernameFree
func (mmIsUsernameFree *mStoreIMockIsUsernameFree) ExpectUsernameParam2(username string) *mStoreIMockIsUsernameFree {
	if mmIsUsernameFree.mock.funcIsUsernameFree != nil {
		mmIsUsernameFree.mock.t.Fatalf("StoreIMock.IsUsernameFree mock is already set by Set")
	}

	if mmIsUsernameFree.defaultExpectation == nil {
		mmIsUsernameFree.defaultExpectation = &StoreIMockIsUsernameFreeExpectation{}
	}

	if mmIsUsernameFree.defaultExpectation.params != nil {
		mmIsUsernameFree.mock.t.Fatalf("StoreIMock.IsUsernameFree mock is already set by Expect")
	}

	if mmIsUsernameFree.defaultExpectation.paramPtrs == nil {
		mmIsUsernameFree.defaultExpectation.paramPtrs = &StoreIMockIsUsernameFreeParamPtrs{}
	}
	mmIsUsernameFree.defaultExpectation.paramPtrs.username = &username
	mmIsUsernameFree.defaultExpectation.expectationOrigins.originUsername = minimock.CallerInfo(1)

	return mmIsUsernameFree
}

// Inspect accepts an inspector function that has same arguments as the storeI.IsUsernameFree
func (mmIsUsernameFree *mStoreIMockIsUsernameFree) Inspect(f func(ctx context.Context, username string)) *mStoreIMockIsUsernameFree {
	if mmIsUsernameFree.mock.inspectFuncIsUsernameFree != nil {
		mmIsUsernameFree.mock.t.Fatalf("Inspect function is already set for StoreIMock.IsUsernameFree")
	}

	mmIsUsernameFree.mock.inspectFuncIsUsernameFree = f

	return mmIsUsernameFree
}

// Return sets up results that will be returned by storeI.IsUsernameFree
func (mmIsUsernameFree *mStoreIMockIsUsernameFree) Return(b1 bool, err error) *StoreIMock {
	if mmIsUsernameFree.mock.funcIsUsernameFree != nil {
		mmIsUsernameFree.mock.t.Fatalf("StoreIMock.IsUsernameFree mock is already set by Set")
	}

	if mmIsUsernameFree.defaultExpectation == nil {
		mmIsUsernameFree.defaultExpectation = &StoreIMockIsUsernameFreeExpectation{mock: mmIsUsernameFree.mock}
	}
	mmIsUsernameFree.defaultExpectation.results = &StoreIMockIsUsernameFreeResults{b1, err}
	mmIsUsernameFree.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmIsUsernameFree.mock
}

// Set uses given function f to mock the storeI.IsUsernameFree method
func (mmIsUsernameFree *mStoreIMockIsUsernameFree) Set(f func(ctx context.Context, username string) (b1 bool, err error)) *StoreIMock {
	if mmIsUsernameFree.defaultExpectation != nil {
		mmIsUsernameFree.mock.t.Fatalf("Default expectation is already set for the storeI.IsUsernameFree method")
	}

	if len(mmIsUsernameFree.expectations) > 0 {
		mmIsUsernameFree.mock.t.Fatalf("Some expectations are already set for the storeI.IsUsernameFree method")
	}

	mmIsUsernameFree.mock.funcIsUsernameFree = f
	mmIsUsernameFree.mock.funcIsUsernameFreeOrigin = minimock.CallerInfo(1)
	return mmIsUsernameFree.mock
}

// When sets expectation for the storeI.IsUsernameFree which will trigger the result defined by the following
// Then helper
func (mmIsUsernameFree *mStoreIMockIsUsernameFree) When(ctx context.Context, username string) *StoreIMockIsUsernameFreeExpectation {
	if mmIsUsernameFree.mock.funcIsUsernameFree != nil {
		mmIsUsernameFree.mock.t.Fatalf("StoreIMock.IsUsernameFree mock is already set by Set")
	}

	expectation := &StoreIMockIsUsernameFreeExpectation{
		mock:               mmIsUsernameFree.mock,
		params:             &StoreIMockIsUsernameFreeParams{ctx, username},
		expectationOrigins: StoreIMockIsUsernameFreeExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmIsUsernameFree.expectations = append(mmIsUsernameFree.expectations, expectation)
	return expectation
}

// Then sets up storeI.IsUsernameFree return parameters for the expectation previously defined by the When method
func (e *StoreIMockIsUsernameFreeExpectation) Then(b1 bool, err error) *StoreIMock {
	e.results = &StoreIMockIsUsernameFreeResults{b1, err}
	return e.mock
}

// Times sets number of times storeI.IsUsernameFree should be invoked
func (mmIsUsernameFree *mStoreIMockIsUsernameFree) Times(n uint64) *mStoreIMockIsUsernameFree {
	if n == 0 {
		mmIsUsernameFree.mock.t.Fatalf("Times of StoreIMock.IsUsernameFree mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmIsUsernameFree.expectedInvocations, n)
	mmIsUsernameFree.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmIsUsernameFree
}

func (mmIsUsernameFree *mStoreIMockIsUsernameFree) invocationsDone() bool {
	if len(mmIsUsernameFree.expectations) == 0 && mmIsUsernameFree.defaultExpectation == nil && mmIsUsernameFree.mock.funcIsUsernameFree == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmIsUsernameFree.mock.afterIsUsernameFreeCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmIsUsernameFree.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// IsUsernameFree implements storeI
func (mmIsUsernameFree *StoreIMock) IsUsernameFree(ctx context.Context, username string) (b1 bool, err error) {
	mm_atomic.AddUint64(&mmIsUsernameFree.beforeIsUsernameFreeCounter, 1)
	defer mm_atomic.AddUint64(&mmIsUsernameFree.afterIsUsernameFreeCounter, 1)

	mmIsUsernameFree.t.Helper()

	if mmIsUsernameFree.inspectFuncIsUsernameFree != nil {
		mmIsUsernameFree.inspectFuncIsUsernameFree(ctx, username)
	}

	mm_params := StoreIMockIsUsernameFreeParams{ctx, username}

	// Record call args
	mmIsUsernameFree.IsUsernameFreeMock.mutex.Lock()
	mmIsUsernameFree.IsUsernameFreeMock.callArgs = append(mmIsUsernameFree.IsUsernameFreeMock.callArgs, &mm_params)
	mmIsUsernameFree.IsUsernameFreeMock.mutex.Unlock()

	for _, e := range mmIsUsernameFree.IsUsernameFreeMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.b1, e.results.err
		}
	}

	if mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation.Counter, 1)
		mm_want := mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation.params
		mm_want_ptrs := mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation.paramPtrs

		mm_got := StoreIMockIsUsernameFreeParams{ctx, username}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmIsUsernameFree.t.Errorf("StoreIMock.IsUsernameFree got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.username != nil && !minimock.Equal(*mm_want_ptrs.username, mm_got.username) {
				mmIsUsernameFree.t.Errorf("StoreIMock.IsUsernameFree got unexpected parameter username, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation.expectationOrigins.originUsername, *mm_want_ptrs.username, mm_got.username, minimock.Diff(*mm_want_ptrs.username, mm_got.username))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmIsUsernameFree.t.Errorf("StoreIMock.IsUsernameFree got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation.results
		if mm_results == nil {
			mmIsUsernameFree.t.Fatal("No results are set for the StoreIMock.IsUsernameFree")
		}
		return (*mm_results).b1, (*mm_results).err
	}
	if mmIsUsernameFree.funcIsUsernameFree != nil {
		return mmIsUsernameFree.funcIsUsernameFree(ctx, username)
	}
	mmIsUsernameFree.t.Fatalf("Unexpected call to StoreIMock.IsUsernameFree. %v %v", ctx, username)
	return
}

// IsUsernameFreeAfterCounter returns a count of finished StoreIMock.IsUsernameFree invocations
func (mmIsUsernameFree *StoreIMock) IsUsernameFreeAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIsUsernameFree.afterIsUsernameFreeCounter)
}

// IsUsernameFreeBeforeCounter returns a count of StoreIMock.IsUsernameFree invocations
func (mmIsUsernameFree *StoreIMock) IsUsernameFreeBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIsUsernameFree.beforeIsUsernameFreeCounter)
}

// Calls returns a list of arguments used in each call to StoreIMock.IsUsernameFree.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmIsUsernameFree *mStoreIMockIsUsernameFree) Calls() []*StoreIMockIsUsernameFreeParams {
	mmIsUsernameFree.mutex.RLock()

	argCopy := make([]*StoreIMockIsUsernameFreeParams, len(mmIsUsernameFree.callArgs))
	copy(argCopy, mmIsUsernameFree.callArgs)

	mmIsUsernameFree.mutex.RUnlock()

	return argCopy
}

// MinimockIsUsernameFreeDone returns true if the count of the IsUsernameFree invocations corresponds
// the number of defined expectations
func (m *StoreIMock) MinimockIsUsernameFreeDone() bool {
	if m.IsUsernameFreeMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.IsUsernameFreeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.IsUsernameFreeMock.invocationsDone()
}

// MinimockIsUsernameFreeInspect logs each unmet expectation
func (m *StoreIMock) MinimockIsUsernameFreeInspect() {
	for _, e := range m.IsUsernameFreeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreIMock.IsUsernameFree at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterIsUsernameFreeCounter := mm_atomic.LoadUint64(&m.afterIsUsernameFreeCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.IsUsernameFreeMock.defaultExpectation != nil && afterIsUsernameFreeCounter < 1 {
		if m.IsUsernameFreeMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreIMock.IsUsernameFree at\n%s", m.IsUsernameFreeMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreIMock.IsUsernameFree at\n%s with params: %#v", m.IsUsernameFreeMock.defaultExpectation.expectationOrigins.origin, *m.IsUsernameFreeMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcIsUsernameFree != nil && afterIsUsernameFreeCounter < 1 {
		m.t.Errorf("Expected call to StoreIMock.IsUsernameFree at\n%s", m.funcIsUsernameFreeOrigin)
	}

	if !m.IsUsernameFreeMock.invocationsDone() && afterIsUsernameFreeCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreIMock.IsUsernameFree at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.IsUsernameFreeMock.expectedInvocations), m.IsUsernameFreeMock.expectedInvocationsOrigin, afterIsUsernameFreeCounter)
	}
}

type mStoreIMockSetUserState struct {
	optional           bool
	mock               *StoreIMock
	defaultExpectation *StoreIMockSetUserStateExpectation
	expectations       []*StoreIMockSetUserStateExpectation

	callArgs []*StoreIMockSetUserStateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreIMockSetUserStateExpectation specifies expectation struct of the storeI.SetUserState
type StoreIMockSetUserStateExpectation struct {
	mock               *StoreIMock
	params             *StoreIMockSetUserStateParams
	paramPtrs          *StoreIMockSetUserStateParamPtrs
	expectationOrigins StoreIMockSetUserStateExpectationOrigins
	results            *StoreIMockSetUserStateResults
	returnOrigin       string
	Counter            uint64
}

// StoreIMockSetUserStateParams contains parameters of the storeI.SetUserState
type StoreIMockSetUserStateParams struct {
	ctx      context.Context
	username string
	state    store.UserState
}

// StoreIMockSetUserStateParamPtrs contains pointers to parameters of the storeI.SetUserState
type StoreIMockSetUserStateParamPtrs struct {
	ctx      *context.Context
	username *string
	state    *store.UserState
}

// StoreIMockSetUserStateResults contains results of the storeI.SetUserState
type StoreIMockSetUserStateResults struct {
	err error
}

// StoreIMockSetUserStateOrigins contains origins of expectations of the storeI.SetUserState
type StoreIMockSetUserStateExpectationOrigins struct {
	origin         string
	originCtx      string
	originUsername string
	originState    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSetUserState *mStoreIMockSetUserState) Optional() *mStoreIMockSetUserState {
	mmSetUserState.optional = true
	return mmSetUserState
}

// Expect sets up expected params for storeI.SetUserState
func (mmSetUserState *mStoreIMockSetUserState) Expect(ctx context.Context, username string, state store.UserState) *mStoreIMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StoreIMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &StoreIMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.paramPtrs != nil {
		mmSetUserState.mock.t.Fatalf("StoreIMock.SetUserState mock is already set by ExpectParams functions")
	}

	mmSetUserState.defaultExpectation.params = &StoreIMockSetUserStateParams{ctx, username, state}
	mmSetUserState.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSetUserState.expectations {
		if minimock.Equal(e.params, mmSetUserState.defaultExpectation.params) {
			mmSetUserState.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSetUserState.defaultExpectation.params)
		}
	}

	return mmSetUserState
}

// ExpectCtxParam1 sets up expected param ctx for storeI.SetUserState
func (mmSetUserState *mStoreIMockSetUserState) ExpectCtxParam1(ctx context.Context) *mStoreIMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StoreIMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &StoreIMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.params != nil {
		mmSetUserState.mock.t.Fatalf("StoreIMock.SetUserState mock is already set by Expect")
	}

	if mmSetUserState.defaultExpectation.paramPtrs == nil {
		mmSetUserState.defaultExpectation.paramPtrs = &StoreIMockSetUserStateParamPtrs{}
	}
	mmSetUserState.defaultExpectation.paramPtrs.ctx = &ctx
	mmSetUserState.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSetUserState
}

// ExpectUsernameParam2 sets up expected param username for storeI.SetUserState
func (mmSetUserState *mStoreIMockSetUserState) ExpectUsernameParam2(username string) *mStoreIMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StoreIMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &StoreIMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.params != nil {
		mmSetUserState.mock.t.Fatalf("StoreIMock.SetUserState mock is already set by Expect")
	}

	if mmSetUserState.defaultExpectation.paramPtrs == nil {
		mmSetUserState.defaultExpectation.paramPtrs = &StoreIMockSetUserStateParamPtrs{}
	}
	mmSetUserState.defaultExpectation.paramPtrs.username = &username
	mmSetUserState.defaultExpectation.expectationOrigins.originUsername = minimock.CallerInfo(1)

	return mmSetUserState
}

// ExpectStateParam3 sets up expected param state for storeI.SetUserState
func (mmSetUserState *mStoreIMockSetUserState) ExpectStateParam3(state store.UserState) *mStoreIMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StoreIMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &StoreIMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.params != nil {
		mmSetUserState.mock.t.Fatalf("StoreIMock.SetUserState mock is already set by Expect")
	}

	if mmSetUserState.defaultExpectation.paramPtrs == nil {
		mmSetUserState.defaultExpectation.paramPtrs = &StoreIMockSetUserStateParamPtrs{}
	}
	mmSetUserState.defaultExpectation.paramPtrs.state = &state
	mmSetUserState.defaultExpectation.expectationOrigins.originState = minimock.CallerInfo(1)

	return mmSetUserState
}

// Inspect accepts an inspector function that has same arguments as the storeI.SetUserState
func (mmSetUserState *mStoreIMockSetUserState) Inspect(f func(ctx context.Context, username string, state store.UserState)) *mStoreIMockSetUserState {
	if mmSetUserState.mock.inspectFuncSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("Inspect function is already set for StoreIMock.SetUserState")
	}

	mmSetUserState.mock.inspectFuncSetUserState = f

	return mmSetUserState
}

// Return sets up results that will be returned by storeI.SetUserState
func (mmSetUserState *mStoreIMockSetUserState) Return(err error) *StoreIMock {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StoreIMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &StoreIMockSetUserStateExpectation{mock: mmSetUserState.mock}
	}
	mmSetUserState.defaultExpectation.results = &StoreIMockSetUserStateResults{err}
	mmSetUserState.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSetUserState.mock
}

// Set uses given function f to mock the storeI.SetUserState method
func (mmSetUserState *mStoreIMockSetUserState) Set(f func(ctx context.Context, username string, state store.UserState) (err error)) *StoreIMock {
	if mmSetUserState.defaultExpectation != nil {
		mmSetUserState.mock.t.Fatalf("Default expectation is already set for the storeI.SetUserState method")
	}

	if len(mmSetUserState.expectations) > 0 {
		mmSetUserState.mock.t.Fatalf("Some expectations are already set for the storeI.SetUserState method")
	}

	mmSetUserState.mock.funcSetUserState = f
	mmSetUserState.mock.funcSetUserStateOrigin = minimock.CallerInfo(1)
	return mmSetUserState.mock
}

// When sets expectation for the storeI.SetUserState which will trigger the result defined by the following
// Then helper
func (mmSetUserState *mStoreIMockSetUserState) When(ctx context.Context, username string, state store.UserState) *StoreIMockSetUserStateExpectation {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StoreIMock.SetUserState mock is already set by Set")
	}

	expectation := &StoreIMockSetUserStateExpectation{
		mock:               mmSetUserState.mock,
		params:             &StoreIMockSetUserStateParams{ctx, username, state},
		expectationOrigins: StoreIMockSetUserStateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSetUserState.expectations = append(mmSetUserState.expectations, expectation)
	return expectation
}

// Then sets up storeI.SetUserState return parameters for the expectation previously defined by the When method
func (e *StoreIMockSetUserStateExpectation) Then(err error) *StoreIMock {
	e.results = &StoreIMockSetUserStateResults{err}
	return e.mock
}

// Times sets number of times storeI.SetUserState should be invoked
func (mmSetUserState *mStoreIMockSetUserState) Times(n uint64) *mStoreIMockSetUserState {
	if n == 0 {
		mmSetUserState.mock.t.Fatalf("Times of StoreIMock.SetUserState mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSetUserState.expectedInvocations, n)
	mmSetUserState.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSetUserState
}

func (mmSetUserState *mStoreIMockSetUserState) invocationsDone() bool {
	if len(mmSetUserState.expectations) == 0 && mmSetUserState.defaultExpectation == nil && mmSetUserState.mock.funcSetUserState == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSetUserState.mock.afterSetUserStateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSetUserState.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SetUserState implements storeI
func (mmSetUserState *StoreIMock) SetUserState(ctx context.Context, username string, state store.UserState) (err error) {
	mm_atomic.AddUint64(&mmSetUserState.beforeSetUserStateCounter, 1)
	defer mm_atomic.AddUint64(&mmSetUserState.afterSetUserStateCounter, 1)

	mmSetUserState.t.Helper()

	if mmSetUserState.inspectFuncSetUserState != nil {
		mmSetUserState.inspectFuncSetUserState(ctx, username, state)
	}

	mm_params := StoreIMockSetUserStateParams{ctx, username, state}

	// Record call args
	mmSetUserState.SetUserStateMock.mutex.Lock()
	mmSetUserState.SetUserStateMock.callArgs = append(mmSetUserState.SetUserStateMock.callArgs, &mm_params)
	mmSetUserState.SetUserStateMock.mutex.Unlock()

	for _, e := range mmSetUserState.SetUserStateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSetUserState.SetUserStateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSetUserState.SetUserStateMock.defaultExpectation.Counter, 1)
		mm_want := mmSetUserState.SetUserStateMock.defaultExpectation.params
		mm_want_ptrs := mmSetUserState.SetUserStateMock.defaultExpectation.paramPtrs

		mm_got := StoreIMockSetUserStateParams{ctx, username, state}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSetUserState.t.Errorf("StoreIMock.SetUserState got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.username != nil && !minimock.Equal(*mm_want_ptrs.username, mm_got.username) {
				mmSetUserState.t.Errorf("StoreIMock.SetUserState got unexpected parameter username, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.originUsername, *mm_want_ptrs.username, mm_got.username, minimock.Diff(*mm_want_ptrs.username, mm_got.username))
			}

			if mm_want_ptrs.state != nil && !minimock.Equal(*mm_want_ptrs.state, mm_got.state) {
				mmSetUserState.t.Errorf("StoreIMock.SetUserState got unexpected parameter state, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.originState, *mm_want_ptrs.state, mm_got.state, minimock.Diff(*mm_want_ptrs.state, mm_got.state))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSetUserState.t.Errorf("StoreIMock.SetUserState got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSetUserState.SetUserStateMock.defaultExpectation.results
		if mm_results == nil {
			mmSetUserState.t.Fatal("No results are set for the StoreIMock.SetUserState")
		}
		return (*mm_results).err
	}
	if mmSetUserState.funcSetUserState != nil {
		return mmSetUserState.funcSetUserState(ctx, username, state)
	}
	mmSetUserState.t.Fatalf("Unexpected call to StoreIMock.SetUserState. %v %v %v", ctx, username, state)
	return
}

// SetUserStateAfterCounter returns a count of finished StoreIMock.SetUserState invocations
func (mmSetUserState *StoreIMock) SetUserStateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetUserState.afterSetUserStateCounter)
}

// SetUserStateBeforeCounter returns a count of StoreIMock.SetUserState invocations
func (mmSetUserState *StoreIMock) SetUserStateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetUserState.beforeSetUserStateCounter)
}

// Calls returns a list of arguments used in each call to StoreIMock.SetUserState.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSetUserState *mStoreIMockSetUserState) Calls() []*StoreIMockSetUserStateParams {
	mmSetUserState.mutex.RLock()

	argCopy := make([]*StoreIMockSetUserStateParams, len(mmSetUserState.callArgs))
	copy(argCopy, mmSetUserState.callArgs)

	mmSetUserState.mutex.RUnlock()

	return argCopy
}

// MinimockSetUserStateDone returns true if the count of the SetUserState invocations corresponds
// the number of defined expectations
func (m *StoreIMock) MinimockSetUserStateDone() bool {
	if m.SetUserStateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SetUserStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SetUserStateMock.invocationsDone()
}

// MinimockSetUserStateInspect logs each unmet expectation
func (m *StoreIMock) MinimockSetUserStateInspect() {
	for _, e := range m.SetUserStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreIMock.SetUserState at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSetUserStateCounter := mm_atomic.LoadUint64(&m.afterSetUserStateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SetUserStateMock.defaultExpectation != nil && afterSetUserStateCounter < 1 {
		if m.SetUserStateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreIMock.SetUserState at\n%s", m.SetUserStateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreIMock.SetUserState at\n%s with params: %#v", m.SetUserStateMock.defaultExpectation.expectationOrigins.origin, *m.SetUserStateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSetUserState != nil && afterSetUserStateCounter < 1 {
		m.t.Errorf("Expected call to StoreIMock.SetUserState at\n%s", m.funcSetUserStateOrigin)
	}

	if !m.SetUserStateMock.invocationsDone() && afterSetUserStateCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreIMock.SetUserState at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SetUserStateMock.expectedInvocations), m.SetUserStateMock.expectedInvocationsOrigin, afterSetUserStateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StoreIMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateUserInspect()

			m.MinimockDeleteUserInspect()

			m.MinimockGetUserStateInspect()

			m.MinimockIsUsernameFreeInspect()

			m.MinimockSetUserStateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StoreIMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StoreIMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateUserDone() &&
		m.MinimockDeleteUserDone() &&
		m.MinimockGetUserStateDone() &&
		m.MinimockIsUsernameFreeDone() &&
		m.MinimockSetUserStateDone()
}
