// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package message

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// UsersServiceMock implements usersService
type UsersServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, username string, password string) (err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, username string, password string)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mUsersServiceMockCreate

	funcDelete          func(ctx context.Context, username string) (err error)
	funcDeleteOrigin    string
	inspectFuncDelete   func(ctx context.Context, username string)
	afterDeleteCounter  uint64
	beforeDeleteCounter uint64
	DeleteMock          mUsersServiceMockDelete

	funcIsUsernameFree          func(ctx context.Context, username string) (b1 bool, err error)
	funcIsUsernameFreeOrigin    string
	inspectFuncIsUsernameFree   func(ctx context.Context, username string)
	afterIsUsernameFreeCounter  uint64
	beforeIsUsernameFreeCounter uint64
	IsUsernameFreeMock          mUsersServiceMockIsUsernameFree
}

// NewUsersServiceMock returns a mock for usersService
func NewUsersServiceMock(t minimock.Tester) *UsersServiceMock {
	m := &UsersServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mUsersServiceMockCreate{mock: m}
	m.CreateMock.callArgs = []*UsersServiceMockCreateParams{}

	m.DeleteMock = mUsersServiceMockDelete{mock: m}
	m.DeleteMock.callArgs = []*UsersServiceMockDeleteParams{}

	m.IsUsernameFreeMock = mUsersServiceMockIsUsernameFree{mock: m}
	m.IsUsernameFreeMock.callArgs = []*UsersServiceMockIsUsernameFreeParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUsersServiceMockCreate struct {
	optional           bool
	mock               *UsersServiceMock
	defaultExpectation *UsersServiceMockCreateExpectation
	expectations       []*UsersServiceMockCreateExpectation

	callArgs []*UsersServiceMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UsersServiceMockCreateExpectation specifies expectation struct of the usersService.Create
type UsersServiceMockCreateExpectation struct {
	mock               *UsersServiceMock
	params             *UsersServiceMockCreateParams
	paramPtrs          *UsersServiceMockCreateParamPtrs
	expectationOrigins UsersServiceMockCreateExpectationOrigins
	results            *UsersServiceMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// UsersServiceMockCreateParams contains parameters of the usersService.Create
type UsersServiceMockCreateParams struct {
	ctx      context.Context
	username string
	password string
}

// UsersServiceMockCreateParamPtrs contains pointers to parameters of the usersService.Create
type UsersServiceMockCreateParamPtrs struct {
	ctx      *context.Context
	username *string
	password *string
}

// UsersServiceMockCreateResults contains results of the usersService.Create
type UsersServiceMockCreateResults struct {
	err error
}

// UsersServiceMockCreateOrigins contains origins of expectations of the usersService.Create
type UsersServiceMockCreateExpectationOrigins struct {
	origin         string
	originCtx      string
	originUsername string
	originPassword string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mUsersServiceMockCreate) Optional() *mUsersServiceMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for usersService.Create
func (mmCreate *mUsersServiceMockCreate) Expect(ctx context.Context, username string, password string) *mUsersServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UsersServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UsersServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("UsersServiceMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &UsersServiceMockCreateParams{ctx, username, password}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for usersService.Create
func (mmCreate *mUsersServiceMockCreate) ExpectCtxParam1(ctx context.Context) *mUsersServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UsersServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UsersServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("UsersServiceMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &UsersServiceMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectUsernameParam2 sets up expected param username for usersService.Create
func (mmCreate *mUsersServiceMockCreate) ExpectUsernameParam2(username string) *mUsersServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UsersServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UsersServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("UsersServiceMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &UsersServiceMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.username = &username
	mmCreate.defaultExpectation.expectationOrigins.originUsername = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectPasswordParam3 sets up expected param password for usersService.Create
func (mmCreate *mUsersServiceMockCreate) ExpectPasswordParam3(password string) *mUsersServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UsersServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UsersServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("UsersServiceMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &UsersServiceMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.password = &password
	mmCreate.defaultExpectation.expectationOrigins.originPassword = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the usersService.Create
func (mmCreate *mUsersServiceMockCreate) Inspect(f func(ctx context.Context, username string, password string)) *mUsersServiceMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for UsersServiceMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by usersService.Create
func (mmCreate *mUsersServiceMockCreate) Return(err error) *UsersServiceMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UsersServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UsersServiceMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &UsersServiceMockCreateResults{err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the usersService.Create method
func (mmCreate *mUsersServiceMockCreate) Set(f func(ctx context.Context, username string, password string) (err error)) *UsersServiceMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the usersService.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the usersService.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the usersService.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mUsersServiceMockCreate) When(ctx context.Context, username string, password string) *UsersServiceMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UsersServiceMock.Create mock is already set by Set")
	}

	expectation := &UsersServiceMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &UsersServiceMockCreateParams{ctx, username, password},
		expectationOrigins: UsersServiceMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up usersService.Create return parameters for the expectation previously defined by the When method
func (e *UsersServiceMockCreateExpectation) Then(err error) *UsersServiceMock {
	e.results = &UsersServiceMockCreateResults{err}
	return e.mock
}

// Times sets number of times usersService.Create should be invoked
func (mmCreate *mUsersServiceMockCreate) Times(n uint64) *mUsersServiceMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of UsersServiceMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mUsersServiceMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements usersService
func (mmCreate *UsersServiceMock) Create(ctx context.Context, username string, password string) (err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, username, password)
	}

	mm_params := UsersServiceMockCreateParams{ctx, username, password}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := UsersServiceMockCreateParams{ctx, username, password}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("UsersServiceMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.username != nil && !minimock.Equal(*mm_want_ptrs.username, mm_got.username) {
				mmCreate.t.Errorf("UsersServiceMock.Create got unexpected parameter username, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originUsername, *mm_want_ptrs.username, mm_got.username, minimock.Diff(*mm_want_ptrs.username, mm_got.username))
			}

			if mm_want_ptrs.password != nil && !minimock.Equal(*mm_want_ptrs.password, mm_got.password) {
				mmCreate.t.Errorf("UsersServiceMock.Create got unexpected parameter password, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originPassword, *mm_want_ptrs.password, mm_got.password, minimock.Diff(*mm_want_ptrs.password, mm_got.password))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("UsersServiceMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the UsersServiceMock.Create")
		}
		return (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, username, password)
	}
	mmCreate.t.Fatalf("Unexpected call to UsersServiceMock.Create. %v %v %v", ctx, username, password)
	return
}

// CreateAfterCounter returns a count of finished UsersServiceMock.Create invocations
func (mmCreate *UsersServiceMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of UsersServiceMock.Create invocations
func (mmCreate *UsersServiceMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to UsersServiceMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mUsersServiceMockCreate) Calls() []*UsersServiceMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*UsersServiceMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *UsersServiceMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *UsersServiceMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UsersServiceMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UsersServiceMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UsersServiceMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to UsersServiceMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to UsersServiceMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mUsersServiceMockDelete struct {
	optional           bool
	mock               *UsersServiceMock
	defaultExpectation *UsersServiceMockDeleteExpectation
	expectations       []*UsersServiceMockDeleteExpectation

	callArgs []*UsersServiceMockDeleteParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UsersServiceMockDeleteExpectation specifies expectation struct of the usersService.Delete
type UsersServiceMockDeleteExpectation struct {
	mock               *UsersServiceMock
	params             *UsersServiceMockDeleteParams
	paramPtrs          *UsersServiceMockDeleteParamPtrs
	expectationOrigins UsersServiceMockDeleteExpectationOrigins
	results            *UsersServiceMockDeleteResults
	returnOrigin       string
	Counter            uint64
}

// UsersServiceMockDeleteParams contains parameters of the usersService.Delete
type UsersServiceMockDeleteParams struct {
	ctx      context.Context
	username string
}

// UsersServiceMockDeleteParamPtrs contains pointers to parameters of the usersService.Delete
type UsersServiceMockDeleteParamPtrs struct {
	ctx      *context.Context
	username *string
}

// UsersServiceMockDeleteResults contains results of the usersService.Delete
type UsersServiceMockDeleteResults struct {
	err error
}

// UsersServiceMockDeleteOrigins contains origins of expectations of the usersService.Delete
type UsersServiceMockDeleteExpectationOrigins struct {
	origin         string
	originCtx      string
	originUsername string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDelete *mUsersServiceMockDelete) Optional() *mUsersServiceMockDelete {
	mmDelete.optional = true
	return mmDelete
}

// Expect sets up expected params for usersService.Delete
func (mmDelete *mUsersServiceMockDelete) Expect(ctx context.Context, username string) *mUsersServiceMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("UsersServiceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &UsersServiceMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.paramPtrs != nil {
		mmDelete.mock.t.Fatalf("UsersServiceMock.Delete mock is already set by ExpectParams functions")
	}

	mmDelete.defaultExpectation.params = &UsersServiceMockDeleteParams{ctx, username}
	mmDelete.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDelete.expectations {
		if minimock.Equal(e.params, mmDelete.defaultExpectation.params) {
			mmDelete.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDelete.defaultExpectation.params)
		}
	}

	return mmDelete
}

// ExpectCtxParam1 sets up expected param ctx for usersService.Delete
func (mmDelete *mUsersServiceMockDelete) ExpectCtxParam1(ctx context.Context) *mUsersServiceMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("UsersServiceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &UsersServiceMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("UsersServiceMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &UsersServiceMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.ctx = &ctx
	mmDelete.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectUsernameParam2 sets up expected param username for usersService.Delete
func (mmDelete *mUsersServiceMockDelete) ExpectUsernameParam2(username string) *mUsersServiceMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("UsersServiceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &UsersServiceMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("UsersServiceMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &UsersServiceMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.username = &username
	mmDelete.defaultExpectation.expectationOrigins.originUsername = minimock.CallerInfo(1)

	return mmDelete
}

// Inspect accepts an inspector function that has same arguments as the usersService.Delete
func (mmDelete *mUsersServiceMockDelete) Inspect(f func(ctx context.Context, username string)) *mUsersServiceMockDelete {
	if mmDelete.mock.inspectFuncDelete != nil {
		mmDelete.mock.t.Fatalf("Inspect function is already set for UsersServiceMock.Delete")
	}

	mmDelete.mock.inspectFuncDelete = f

	return mmDelete
}

// Return sets up results that will be returned by usersService.Delete
func (mmDelete *mUsersServiceMockDelete) Return(err error) *UsersServiceMock {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("UsersServiceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &UsersServiceMockDeleteExpectation{mock: mmDelete.mock}
	}
	mmDelete.defaultExpectation.results = &UsersServiceMockDeleteResults{err}
	mmDelete.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// Set uses given function f to mock the usersService.Delete method
func (mmDelete *mUsersServiceMockDelete) Set(f func(ctx context.Context, username string) (err error)) *UsersServiceMock {
	if mmDelete.defaultExpectation != nil {
		mmDelete.mock.t.Fatalf("Default expectation is already set for the usersService.Delete method")
	}

	if len(mmDelete.expectations) > 0 {
		mmDelete.mock.t.Fatalf("Some expectations are already set for the usersService.Delete method")
	}

	mmDelete.mock.funcDelete = f
	mmDelete.mock.funcDeleteOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// When sets expectation for the usersService.Delete which will trigger the result defined by the following
// Then helper
func (mmDelete *mUsersServiceMockDelete) When(ctx context.Context, username string) *UsersServiceMockDeleteExpectation {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("UsersServiceMock.Delete mock is already set by Set")
	}

	expectation := &UsersServiceMockDeleteExpectation{
		mock:               mmDelete.mock,
		params:             &UsersServiceMockDeleteParams{ctx, username},
		expectationOrigins: UsersServiceMockDeleteExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDelete.expectations = append(mmDelete.expectations, expectation)
	return expectation
}

// Then sets up usersService.Delete return parameters for the expectation previously defined by the When method
func (e *UsersServiceMockDeleteExpectation) Then(err error) *UsersServiceMock {
	e.results = &UsersServiceMockDeleteResults{err}
	return e.mock
}

// Times sets number of times usersService.Delete should be invoked
func (mmDelete *mUsersServiceMockDelete) Times(n uint64) *mUsersServiceMockDelete {
	if n == 0 {
		mmDelete.mock.t.Fatalf("Times of UsersServiceMock.Delete mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDelete.expectedInvocations, n)
	mmDelete.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDelete
}

func (mmDelete *mUsersServiceMockDelete) invocationsDone() bool {
	if len(mmDelete.expectations) == 0 && mmDelete.defaultExpectation == nil && mmDelete.mock.funcDelete == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDelete.mock.afterDeleteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDelete.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Delete implements usersService
func (mmDelete *UsersServiceMock) Delete(ctx context.Context, username string) (err error) {
	mm_atomic.AddUint64(&mmDelete.beforeDeleteCounter, 1)
	defer mm_atomic.AddUint64(&mmDelete.afterDeleteCounter, 1)

	mmDelete.t.Helper()

	if mmDelete.inspectFuncDelete != nil {
		mmDelete.inspectFuncDelete(ctx, username)
	}

	mm_params := UsersServiceMockDeleteParams{ctx, username}

	// Record call args
	mmDelete.DeleteMock.mutex.Lock()
	mmDelete.DeleteMock.callArgs = append(mmDelete.DeleteMock.callArgs, &mm_params)
	mmDelete.DeleteMock.mutex.Unlock()

	for _, e := range mmDelete.DeleteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDelete.DeleteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDelete.DeleteMock.defaultExpectation.Counter, 1)
		mm_want := mmDelete.DeleteMock.defaultExpectation.params
		mm_want_ptrs := mmDelete.DeleteMock.defaultExpectation.paramPtrs

		mm_got := UsersServiceMockDeleteParams{ctx, username}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDelete.t.Errorf("UsersServiceMock.Delete got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.username != nil && !minimock.Equal(*mm_want_ptrs.username, mm_got.username) {
				mmDelete.t.Errorf("UsersServiceMock.Delete got unexpected parameter username, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originUsername, *mm_want_ptrs.username, mm_got.username, minimock.Diff(*mm_want_ptrs.username, mm_got.username))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDelete.t.Errorf("UsersServiceMock.Delete got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDelete.DeleteMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDelete.DeleteMock.defaultExpectation.results
		if mm_results == nil {
			mmDelete.t.Fatal("No results are set for the UsersServiceMock.Delete")
		}
		return (*mm_results).err
	}
	if mmDelete.funcDelete != nil {
		return mmDelete.funcDelete(ctx, username)
	}
	mmDelete.t.Fatalf("Unexpected call to UsersServiceMock.Delete. %v %v", ctx, username)
	return
}

// DeleteAfterCounter returns a count of finished UsersServiceMock.Delete invocations
func (mmDelete *UsersServiceMock) DeleteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.afterDeleteCounter)
}

// DeleteBeforeCounter returns a count of UsersServiceMock.Delete invocations
func (mmDelete *UsersServiceMock) DeleteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.beforeDeleteCounter)
}

// Calls returns a list of arguments used in each call to UsersServiceMock.Delete.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDelete *mUsersServiceMockDelete) Calls() []*UsersServiceMockDeleteParams {
	mmDelete.mutex.RLock()

	argCopy := make([]*UsersServiceMockDeleteParams, len(mmDelete.callArgs))
	copy(argCopy, mmDelete.callArgs)

	mmDelete.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteDone returns true if the count of the Delete invocations corresponds
// the number of defined expectations
func (m *UsersServiceMock) MinimockDeleteDone() bool {
	if m.DeleteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteMock.invocationsDone()
}

// MinimockDeleteInspect logs each unmet expectation
func (m *UsersServiceMock) MinimockDeleteInspect() {
	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UsersServiceMock.Delete at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteCounter := mm_atomic.LoadUint64(&m.afterDeleteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteMock.defaultExpectation != nil && afterDeleteCounter < 1 {
		if m.DeleteMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UsersServiceMock.Delete at\n%s", m.DeleteMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UsersServiceMock.Delete at\n%s with params: %#v", m.DeleteMock.defaultExpectation.expectationOrigins.origin, *m.DeleteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDelete != nil && afterDeleteCounter < 1 {
		m.t.Errorf("Expected call to UsersServiceMock.Delete at\n%s", m.funcDeleteOrigin)
	}

	if !m.DeleteMock.invocationsDone() && afterDeleteCounter > 0 {
		m.t.Errorf("Expected %d calls to UsersServiceMock.Delete at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteMock.expectedInvocations), m.DeleteMock.expectedInvocationsOrigin, afterDeleteCounter)
	}
}

type mUsersServiceMockIsUsernameFree struct {
	optional           bool
	mock               *UsersServiceMock
	defaultExpectation *UsersServiceMockIsUsernameFreeExpectation
	expectations       []*UsersServiceMockIsUsernameFreeExpectation

	callArgs []*UsersServiceMockIsUsernameFreeParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UsersServiceMockIsUsernameFreeExpectation specifies expectation struct of the usersService.IsUsernameFree
type UsersServiceMockIsUsernameFreeExpectation struct {
	mock               *UsersServiceMock
	params             *UsersServiceMockIsUsernameFreeParams
	paramPtrs          *UsersServiceMockIsUsernameFreeParamPtrs
	expectationOrigins UsersServiceMockIsUsernameFreeExpectationOrigins
	results            *UsersServiceMockIsUsernameFreeResults
	returnOrigin       string
	Counter            uint64
}

// UsersServiceMockIsUsernameFreeParams contains parameters of the usersService.IsUsernameFree
type UsersServiceMockIsUsernameFreeParams struct {
	ctx      context.Context
	username string
}

// UsersServiceMockIsUsernameFreeParamPtrs contains pointers to parameters of the usersService.IsUsernameFree
type UsersServiceMockIsUsernameFreeParamPtrs struct {
	ctx      *context.Context
	username *string
}

// UsersServiceMockIsUsernameFreeResults contains results of the usersService.IsUsernameFree
type UsersServiceMockIsUsernameFreeResults struct {
	b1  bool
	err error
}

// UsersServiceMockIsUsernameFreeOrigins contains origins of expectations of the usersService.IsUsernameFree
type UsersServiceMockIsUsernameFreeExpectationOrigins struct {
	origin         string
	originCtx      string
	originUsername string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmIsUsernameFree *mUsersServiceMockIsUsernameFree) Optional() *mUsersServiceMockIsUsernameFree {
	mmIsUsernameFree.optional = true
	return mmIsUsernameFree
}

// Expect sets up expected params for usersService.IsUsernameFree
func (mmIsUsernameFree *mUsersServiceMockIsUsernameFree) Expect(ctx context.Context, username string) *mUsersServiceMockIsUsernameFree {
	if mmIsUsernameFree.mock.funcIsUsernameFree != nil {
		mmIsUsernameFree.mock.t.Fatalf("UsersServiceMock.IsUsernameFree mock is already set by Set")
	}

	if mmIsUsernameFree.defaultExpectation == nil {
		mmIsUsernameFree.defaultExpectation = &UsersServiceMockIsUsernameFreeExpectation{}
	}

	if mmIsUsernameFree.defaultExpectation.paramPtrs != nil {
		mmIsUsernameFree.mock.t.Fatalf("UsersServiceMock.IsUsernameFree mock is already set by ExpectParams functions")
	}

	mmIsUsernameFree.defaultExpectation.params = &UsersServiceMockIsUsernameFreeParams{ctx, username}
	mmIsUsernameFree.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmIsUsernameFree.expectations {
		if minimock.Equal(e.params, mmIsUsernameFree.defaultExpectation.params) {
			mmIsUsernameFree.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmIsUsernameFree.defaultExpectation.params)
		}
	}

	return mmIsUsernameFree
}

// ExpectCtxParam1 sets up expected param ctx for usersService.IsUsernameFree
func (mmIsUsernameFree *mUsersServiceMockIsUsernameFree) ExpectCtxParam1(ctx context.Context) *mUsersServiceMockIsUsernameFree {
	if mmIsUsernameFree.mock.funcIsUsernameFree != nil {
		mmIsUsernameFree.mock.t.Fatalf("UsersServiceMock.IsUsernameFree mock is already set by Set")
	}

	if mmIsUsernameFree.defaultExpectation == nil {
		mmIsUsernameFree.defaultExpectation = &UsersServiceMockIsUsernameFreeExpectation{}
	}

	if mmIsUsernameFree.defaultExpectation.params != nil {
		mmIsUsernameFree.mock.t.Fatalf("UsersServiceMock.IsUsernameFree mock is already set by Expect")
	}

	if mmIsUsernameFree.defaultExpectation.paramPtrs == nil {
		mmIsUsernameFree.defaultExpectation.paramPtrs = &UsersServiceMockIsUsernameFreeParamPtrs{}
	}
	mmIsUsernameFree.defaultExpectation.paramPtrs.ctx = &ctx
	mmIsUsernameFree.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmIsUsernameFree
}

// ExpectUsernameParam2 sets up expected param username for usersService.IsUsernameFree
func (mmIsUsernameFree *mUsersServiceMockIsUsernameFree) ExpectUsernameParam2(username string) *mUsersServiceMockIsUsernameFree {
	if mmIsUsernameFree.mock.funcIsUsernameFree != nil {
		mmIsUsernameFree.mock.t.Fatalf("UsersServiceMock.IsUsernameFree mock is already set by Set")
	}

	if mmIsUsernameFree.defaultExpectation == nil {
		mmIsUsernameFree.defaultExpectation = &UsersServiceMockIsUsernameFreeExpectation{}
	}

	if mmIsUsernameFree.defaultExpectation.params != nil {
		mmIsUsernameFree.mock.t.Fatalf("UsersServiceMock.IsUsernameFree mock is already set by Expect")
	}

	if mmIsUsernameFree.defaultExpectation.paramPtrs == nil {
		mmIsUsernameFree.defaultExpectation.paramPtrs = &UsersServiceMockIsUsernameFreeParamPtrs{}
	}
	mmIsUsernameFree.defaultExpectation.paramPtrs.username = &username
	mmIsUsernameFree.defaultExpectation.expectationOrigins.originUsername = minimock.CallerInfo(1)

	return mmIsUsernameFree
}

// Inspect accepts an inspector function that has same arguments as the usersService.IsUsernameFree
func (mmIsUsernameFree *mUsersServiceMockIsUsernameFree) Inspect(f func(ctx context.Context, username string)) *mUsersServiceMockIsUsernameFree {
	if mmIsUsernameFree.mock.inspectFuncIsUsernameFree != nil {
		mmIsUsernameFree.mock.t.Fatalf("Inspect function is already set for UsersServiceMock.IsUsernameFree")
	}

	mmIsUsernameFree.mock.inspectFuncIsUsernameFree = f

	return mmIsUsernameFree
}

// Return sets up results that will be returned by usersService.IsUsernameFree
func (mmIsUsernameFree *mUsersServiceMockIsUsernameFree) Return(b1 bool, err error) *UsersServiceMock {
	if mmIsUsernameFree.mock.funcIsUsernameFree != nil {
		mmIsUsernameFree.mock.t.Fatalf("UsersServiceMock.IsUsernameFree mock is already set by Set")
	}

	if mmIsUsernameFree.defaultExpectation == nil {
		mmIsUsernameFree.defaultExpectation = &UsersServiceMockIsUsernameFreeExpectation{mock: mmIsUsernameFree.mock}
	}
	mmIsUsernameFree.defaultExpectation.results = &UsersServiceMockIsUsernameFreeResults{b1, err}
	mmIsUsernameFree.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmIsUsernameFree.mock
}

// Set uses given function f to mock the usersService.IsUsernameFree method
func (mmIsUsernameFree *mUsersServiceMockIsUsernameFree) Set(f func(ctx context.Context, username string) (b1 bool, err error)) *UsersServiceMock {
	if mmIsUsernameFree.defaultExpectation != nil {
		mmIsUsernameFree.mock.t.Fatalf("Default expectation is already set for the usersService.IsUsernameFree method")
	}

	if len(mmIsUsernameFree.expectations) > 0 {
		mmIsUsernameFree.mock.t.Fatalf("Some expectations are already set for the usersService.IsUsernameFree method")
	}

	mmIsUsernameFree.mock.funcIsUsernameFree = f
	mmIsUsernameFree.mock.funcIsUsernameFreeOrigin = minimock.CallerInfo(1)
	return mmIsUsernameFree.mock
}

// When sets expectation for the usersService.IsUsernameFree which will trigger the result defined by the following
// Then helper
func (mmIsUsernameFree *mUsersServiceMockIsUsernameFree) When(ctx context.Context, username string) *UsersServiceMockIsUsernameFreeExpectation {
	if mmIsUsernameFree.mock.funcIsUsernameFree != nil {
		mmIsUsernameFree.mock.t.Fatalf("UsersServiceMock.IsUsernameFree mock is already set by Set")
	}

	expectation := &UsersServiceMockIsUsernameFreeExpectation{
		mock:               mmIsUsernameFree.mock,
		params:             &UsersServiceMockIsUsernameFreeParams{ctx, username},
		expectationOrigins: UsersServiceMockIsUsernameFreeExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmIsUsernameFree.expectations = append(mmIsUsernameFree.expectations, expectation)
	return expectation
}

// Then sets up usersService.IsUsernameFree return parameters for the expectation previously defined by the When method
func (e *UsersServiceMockIsUsernameFreeExpectation) Then(b1 bool, err error) *UsersServiceMock {
	e.results = &UsersServiceMockIsUsernameFreeResults{b1, err}
	return e.mock
}

// Times sets number of times usersService.IsUsernameFree should be invoked
func (mmIsUsernameFree *mUsersServiceMockIsUsernameFree) Times(n uint64) *mUsersServiceMockIsUsernameFree {
	if n == 0 {
		mmIsUsernameFree.mock.t.Fatalf("Times of UsersServiceMock.IsUsernameFree mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmIsUsernameFree.expectedInvocations, n)
	mmIsUsernameFree.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmIsUsernameFree
}

func (mmIsUsernameFree *mUsersServiceMockIsUsernameFree) invocationsDone() bool {
	if len(mmIsUsernameFree.expectations) == 0 && mmIsUsernameFree.defaultExpectation == nil && mmIsUsernameFree.mock.funcIsUsernameFree == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmIsUsernameFree.mock.afterIsUsernameFreeCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmIsUsernameFree.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// IsUsernameFree implements usersService
func (mmIsUsernameFree *UsersServiceMock) IsUsernameFree(ctx context.Context, username string) (b1 bool, err error) {
	mm_atomic.AddUint64(&mmIsUsernameFree.beforeIsUsernameFreeCounter, 1)
	defer mm_atomic.AddUint64(&mmIsUsernameFree.afterIsUsernameFreeCounter, 1)

	mmIsUsernameFree.t.Helper()

	if mmIsUsernameFree.inspectFuncIsUsernameFree != nil {
		mmIsUsernameFree.inspectFuncIsUsernameFree(ctx, username)
	}

	mm_params := UsersServiceMockIsUsernameFreeParams{ctx, username}

	// Record call args
	mmIsUsernameFree.IsUsernameFreeMock.mutex.Lock()
	mmIsUsernameFree.IsUsernameFreeMock.callArgs = append(mmIsUsernameFree.IsUsernameFreeMock.callArgs, &mm_params)
	mmIsUsernameFree.IsUsernameFreeMock.mutex.Unlock()

	for _, e := range mmIsUsernameFree.IsUsernameFreeMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.b1, e.results.err
		}
	}

	if mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation.Counter, 1)
		mm_want := mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation.params
		mm_want_ptrs := mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation.paramPtrs

		mm_got := UsersServiceMockIsUsernameFreeParams{ctx, username}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmIsUsernameFree.t.Errorf("UsersServiceMock.IsUsernameFree got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.username != nil && !minimock.Equal(*mm_want_ptrs.username, mm_got.username) {
				mmIsUsernameFree.t.Errorf("UsersServiceMock.IsUsernameFree got unexpected parameter username, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation.expectationOrigins.originUsername, *mm_want_ptrs.username, mm_got.username, minimock.Diff(*mm_want_ptrs.username, mm_got.username))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmIsUsernameFree.t.Errorf("UsersServiceMock.IsUsernameFree got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmIsUsernameFree.IsUsernameFreeMock.defaultExpectation.results
		if mm_results == nil {
			mmIsUsernameFree.t.Fatal("No results are set for the UsersServiceMock.IsUsernameFree")
		}
		return (*mm_results).b1, (*mm_results).err
	}
	if mmIsUsernameFree.funcIsUsernameFree != nil {
		return mmIsUsernameFree.funcIsUsernameFree(ctx, username)
	}
	mmIsUsernameFree.t.Fatalf("Unexpected call to UsersServiceMock.IsUsernameFree. %v %v", ctx, username)
	return
}

// IsUsernameFreeAfterCounter returns a count of finished UsersServiceMock.IsUsernameFree invocations
func (mmIsUsernameFree *UsersServiceMock) IsUsernameFreeAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIsUsernameFree.afterIsUsernameFreeCounter)
}

// IsUsernameFreeBeforeCounter returns a count of UsersServiceMock.IsUsernameFree invocations
func (mmIsUsernameFree *UsersServiceMock) IsUsernameFreeBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIsUsernameFree.beforeIsUsernameFreeCounter)
}

// Calls returns a list of arguments used in each call to UsersServiceMock.IsUsernameFree.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmIsUsernameFree *mUsersServiceMockIsUsernameFree) Calls() []*UsersServiceMockIsUsernameFreeParams {
	mmIsUsernameFree.mutex.RLock()

	argCopy := make([]*UsersServiceMockIsUsernameFreeParams, len(mmIsUsernameFree.callArgs))
	copy(argCopy, mmIsUsernameFree.callArgs)

	mmIsUsernameFree.mutex.RUnlock()

	return argCopy
}

// MinimockIsUsernameFreeDone returns true if the count of the IsUsernameFree invocations corresponds
// the number of defined expectations
func (m *UsersServiceMock) MinimockIsUsernameFreeDone() bool {
	if m.IsUsernameFreeMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.IsUsernameFreeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.IsUsernameFreeMock.invocationsDone()
}

// MinimockIsUsernameFreeInspect logs each unmet expectation
func (m *UsersServiceMock) MinimockIsUsernameFreeInspect() {
	for _, e := range m.IsUsernameFreeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UsersServiceMock.IsUsernameFree at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterIsUsernameFreeCounter := mm_atomic.LoadUint64(&m.afterIsUsernameFreeCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.IsUsernameFreeMock.defaultExpectation != nil && afterIsUsernameFreeCounter < 1 {
		if m.IsUsernameFreeMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UsersServiceMock.IsUsernameFree at\n%s", m.IsUsernameFreeMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UsersServiceMock.IsUsernameFree at\n%s with params: %#v", m.IsUsernameFreeMock.defaultExpectation.expectationOrigins.origin, *m.IsUsernameFreeMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcIsUsernameFree != nil && afterIsUsernameFreeCounter < 1 {
		m.t.Errorf("Expected call to UsersServiceMock.IsUsernameFree at\n%s", m.funcIsUsernameFreeOrigin)
	}

	if !m.IsUsernameFreeMock.invocationsDone() && afterIsUsernameFreeCounter > 0 {
		m.t.Errorf("Expected %d calls to UsersServiceMock.IsUsernameFree at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.IsUsernameFreeMock.expectedInvocations), m.IsUsernameFreeMock.expectedInvocationsOrigin, afterIsUsernameFreeCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UsersServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockDeleteInspect()

			m.MinimockIsUsernameFreeInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UsersServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UsersServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockDeleteDone() &&
		m.MinimockIsUsernameFreeDone()
}
