// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package deleteuser

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/nskondratev/socks5-proxy-server/internal/bot/store"
)

// StateStoreMock implements stateStore
type StateStoreMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSetUserState          func(ctx context.Context, username string, state store.UserState) (err error)
	funcSetUserStateOrigin    string
	inspectFuncSetUserState   func(ctx context.Context, username string, state store.UserState)
	afterSetUserStateCounter  uint64
	beforeSetUserStateCounter uint64
	SetUserStateMock          mStateStoreMockSetUserState
}

// NewStateStoreMock returns a mock for stateStore
func NewStateStoreMock(t minimock.Tester) *StateStoreMock {
	m := &StateStoreMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SetUserStateMock = mStateStoreMockSetUserState{mock: m}
	m.SetUserStateMock.callArgs = []*StateStoreMockSetUserStateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStateStoreMockSetUserState struct {
	optional           bool
	mock               *StateStoreMock
	defaultExpectation *StateStoreMockSetUserStateExpectation
	expectations       []*StateStoreMockSetUserStateExpectation

	callArgs []*StateStoreMockSetUserStateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StateStoreMockSetUserStateExpectation specifies expectation struct of the stateStore.SetUserState
type StateStoreMockSetUserStateExpectation struct {
	mock               *StateStoreMock
	params             *StateStoreMockSetUserStateParams
	paramPtrs          *StateStoreMockSetUserStateParamPtrs
	expectationOrigins StateStoreMockSetUserStateExpectationOrigins
	results            *StateStoreMockSetUserStateResults
	returnOrigin       string
	Counter            uint64
}

// StateStoreMockSetUserStateParams contains parameters of the stateStore.SetUserState
type StateStoreMockSetUserStateParams struct {
	ctx      context.Context
	username string
	state    store.UserState
}

// StateStoreMockSetUserStateParamPtrs contains pointers to parameters of the stateStore.SetUserState
type StateStoreMockSetUserStateParamPtrs struct {
	ctx      *context.Context
	username *string
	state    *store.UserState
}

// StateStoreMockSetUserStateResults contains results of the stateStore.SetUserState
type StateStoreMockSetUserStateResults struct {
	err error
}

// StateStoreMockSetUserStateOrigins contains origins of expectations of the stateStore.SetUserState
type StateStoreMockSetUserStateExpectationOrigins struct {
	origin         string
	originCtx      string
	originUsername string
	originState    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSetUserState *mStateStoreMockSetUserState) Optional() *mStateStoreMockSetUserState {
	mmSetUserState.optional = true
	return mmSetUserState
}

// Expect sets up expected params for stateStore.SetUserState
func (mmSetUserState *mStateStoreMockSetUserState) Expect(ctx context.Context, username string, state store.UserState) *mStateStoreMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StateStoreMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &StateStoreMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.paramPtrs != nil {
		mmSetUserState.mock.t.Fatalf("StateStoreMock.SetUserState mock is already set by ExpectParams functions")
	}

	mmSetUserState.defaultExpectation.params = &StateStoreMockSetUserStateParams{ctx, username, state}
	mmSetUserState.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSetUserState.expectations {
		if minimock.Equal(e.params, mmSetUserState.defaultExpectation.params) {
			mmSetUserState.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSetUserState.defaultExpectation.params)
		}
	}

	return mmSetUserState
}

// ExpectCtxParam1 sets up expected param ctx for stateStore.SetUserState
func (mmSetUserState *mStateStoreMockSetUserState) ExpectCtxParam1(ctx context.Context) *mStateStoreMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StateStoreMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &StateStoreMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.params != nil {
		mmSetUserState.mock.t.Fatalf("StateStoreMock.SetUserState mock is already set by Expect")
	}

	if mmSetUserState.defaultExpectation.paramPtrs == nil {
		mmSetUserState.defaultExpectation.paramPtrs = &StateStoreMockSetUserStateParamPtrs{}
	}
	mmSetUserState.defaultExpectation.paramPtrs.ctx = &ctx
	mmSetUserState.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSetUserState
}

// ExpectUsernameParam2 sets up expected param username for stateStore.SetUserState
func (mmSetUserState *mStateStoreMockSetUserState) ExpectUsernameParam2(username string) *mStateStoreMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StateStoreMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &StateStoreMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.params != nil {
		mmSetUserState.mock.t.Fatalf("StateStoreMock.SetUserState mock is already set by Expect")
	}

	if mmSetUserState.defaultExpectation.paramPtrs == nil {
		mmSetUserState.defaultExpectation.paramPtrs = &StateStoreMockSetUserStateParamPtrs{}
	}
	mmSetUserState.defaultExpectation.paramPtrs.username = &username
	mmSetUserState.defaultExpectation.expectationOrigins.originUsername = minimock.CallerInfo(1)

	return mmSetUserState
}

// ExpectStateParam3 sets up expected param state for stateStore.SetUserState
func (mmSetUserState *mStateStoreMockSetUserState) ExpectStateParam3(state store.UserState) *mStateStoreMockSetUserState {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StateStoreMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &StateStoreMockSetUserStateExpectation{}
	}

	if mmSetUserState.defaultExpectation.params != nil {
		mmSetUserState.mock.t.Fatalf("StateStoreMock.SetUserState mock is already set by Expect")
	}

	if mmSetUserState.defaultExpectation.paramPtrs == nil {
		mmSetUserState.defaultExpectation.paramPtrs = &StateStoreMockSetUserStateParamPtrs{}
	}
	mmSetUserState.defaultExpectation.paramPtrs.state = &state
	mmSetUserState.defaultExpectation.expectationOrigins.originState = minimock.CallerInfo(1)

	return mmSetUserState
}

// Inspect accepts an inspector function that has same arguments as the stateStore.SetUserState
func (mmSetUserState *mStateStoreMockSetUserState) Inspect(f func(ctx context.Context, username string, state store.UserState)) *mStateStoreMockSetUserState {
	if mmSetUserState.mock.inspectFuncSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("Inspect function is already set for StateStoreMock.SetUserState")
	}

	mmSetUserState.mock.inspectFuncSetUserState = f

	return mmSetUserState
}

// Return sets up results that will be returned by stateStore.SetUserState
func (mmSetUserState *mStateStoreMockSetUserState) Return(err error) *StateStoreMock {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StateStoreMock.SetUserState mock is already set by Set")
	}

	if mmSetUserState.defaultExpectation == nil {
		mmSetUserState.defaultExpectation = &StateStoreMockSetUserStateExpectation{mock: mmSetUserState.mock}
	}
	mmSetUserState.defaultExpectation.results = &StateStoreMockSetUserStateResults{err}
	mmSetUserState.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSetUserState.mock
}

// Set uses given function f to mock the stateStore.SetUserState method
func (mmSetUserState *mStateStoreMockSetUserState) Set(f func(ctx context.Context, username string, state store.UserState) (err error)) *StateStoreMock {
	if mmSetUserState.defaultExpectation != nil {
		mmSetUserState.mock.t.Fatalf("Default expectation is already set for the stateStore.SetUserState method")
	}

	if len(mmSetUserState.expectations) > 0 {
		mmSetUserState.mock.t.Fatalf("Some expectations are already set for the stateStore.SetUserState method")
	}

	mmSetUserState.mock.funcSetUserState = f
	mmSetUserState.mock.funcSetUserStateOrigin = minimock.CallerInfo(1)
	return mmSetUserState.mock
}

// When sets expectation for the stateStore.SetUserState which will trigger the result defined by the following
// Then helper
func (mmSetUserState *mStateStoreMockSetUserState) When(ctx context.Context, username string, state store.UserState) *StateStoreMockSetUserStateExpectation {
	if mmSetUserState.mock.funcSetUserState != nil {
		mmSetUserState.mock.t.Fatalf("StateStoreMock.SetUserState mock is already set by Set")
	}

	expectation := &StateStoreMockSetUserStateExpectation{
		mock:               mmSetUserState.mock,
		params:             &StateStoreMockSetUserStateParams{ctx, username, state},
		expectationOrigins: StateStoreMockSetUserStateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSetUserState.expectations = append(mmSetUserState.expectations, expectation)
	return expectation
}

// Then sets up stateStore.SetUserState return parameters for the expectation previously defined by the When method
func (e *StateStoreMockSetUserStateExpectation) Then(err error) *StateStoreMock {
	e.results = &StateStoreMockSetUserStateResults{err}
	return e.mock
}

// Times sets number of times stateStore.SetUserState should be invoked
func (mmSetUserState *mStateStoreMockSetUserState) Times(n uint64) *mStateStoreMockSetUserState {
	if n == 0 {
		mmSetUserState.mock.t.Fatalf("Times of StateStoreMock.SetUserState mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSetUserState.expectedInvocations, n)
	mmSetUserState.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSetUserState
}

func (mmSetUserState *mStateStoreMockSetUserState) invocationsDone() bool {
	if len(mmSetUserState.expectations) == 0 && mmSetUserState.defaultExpectation == nil && mmSetUserState.mock.funcSetUserState == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSetUserState.mock.afterSetUserStateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSetUserState.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SetUserState implements stateStore
func (mmSetUserState *StateStoreMock) SetUserState(ctx context.Context, username string, state store.UserState) (err error) {
	mm_atomic.AddUint64(&mmSetUserState.beforeSetUserStateCounter, 1)
	defer mm_atomic.AddUint64(&mmSetUserState.afterSetUserStateCounter, 1)

	mmSetUserState.t.Helper()

	if mmSetUserState.inspectFuncSetUserState != nil {
		mmSetUserState.inspectFuncSetUserState(ctx, username, state)
	}

	mm_params := StateStoreMockSetUserStateParams{ctx, username, state}

	// Record call args
	mmSetUserState.SetUserStateMock.mutex.Lock()
	mmSetUserState.SetUserStateMock.callArgs = append(mmSetUserState.SetUserStateMock.callArgs, &mm_params)
	mmSetUserState.SetUserStateMock.mutex.Unlock()

	for _, e := range mmSetUserState.SetUserStateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSetUserState.SetUserStateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSetUserState.SetUserStateMock.defaultExpectation.Counter, 1)
		mm_want := mmSetUserState.SetUserStateMock.defaultExpectation.params
		mm_want_ptrs := mmSetUserState.SetUserStateMock.defaultExpectation.paramPtrs

		mm_got := StateStoreMockSetUserStateParams{ctx, username, state}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSetUserState.t.Errorf("StateStoreMock.SetUserState got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.username != nil && !minimock.Equal(*mm_want_ptrs.username, mm_got.username) {
				mmSetUserState.t.Errorf("StateStoreMock.SetUserState got unexpected parameter username, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.originUsername, *mm_want_ptrs.username, mm_got.username, minimock.Diff(*mm_want_ptrs.username, mm_got.username))
			}

			if mm_want_ptrs.state != nil && !minimock.Equal(*mm_want_ptrs.state, mm_got.state) {
				mmSetUserState.t.Errorf("StateStoreMock.SetUserState got unexpected parameter state, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.originState, *mm_want_ptrs.state, mm_got.state, minimock.Diff(*mm_want_ptrs.state, mm_got.state))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSetUserState.t.Errorf("StateStoreMock.SetUserState got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSetUserState.SetUserStateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSetUserState.SetUserStateMock.defaultExpectation.results
		if mm_results == nil {
			mmSetUserState.t.Fatal("No results are set for the StateStoreMock.SetUserState")
		}
		return (*mm_results).err
	}
	if mmSetUserState.funcSetUserState != nil {
		return mmSetUserState.funcSetUserState(ctx, username, state)
	}
	mmSetUserState.t.Fatalf("Unexpected call to StateStoreMock.SetUserState. %v %v %v", ctx, username, state)
	return
}

// SetUserStateAfterCounter returns a count of finished StateStoreMock.SetUserState invocations
func (mmSetUserState *StateStoreMock) SetUserStateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetUserState.afterSetUserStateCounter)
}

// SetUserStateBeforeCounter returns a count of StateStoreMock.SetUserState invocations
func (mmSetUserState *StateStoreMock) SetUserStateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetUserState.beforeSetUserStateCounter)
}

// Calls returns a list of arguments used in each call to StateStoreMock.SetUserState.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSetUserState *mStateStoreMockSetUserState) Calls() []*StateStoreMockSetUserStateParams {
	mmSetUserState.mutex.RLock()

	argCopy := make([]*StateStoreMockSetUserStateParams, len(mmSetUserState.callArgs))
	copy(argCopy, mmSetUserState.callArgs)

	mmSetUserState.mutex.RUnlock()

	return argCopy
}

// MinimockSetUserStateDone returns true if the count of the SetUserState invocations corresponds
// the number of defined expectations
func (m *StateStoreMock) MinimockSetUserStateDone() bool {
	if m.SetUserStateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SetUserStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SetUserStateMock.invocationsDone()
}

// MinimockSetUserStateInspect logs each unmet expectation
func (m *StateStoreMock) MinimockSetUserStateInspect() {
	for _, e := range m.SetUserStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StateStoreMock.SetUserState at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSetUserStateCounter := mm_atomic.LoadUint64(&m.afterSetUserStateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SetUserStateMock.defaultExpectation != nil && afterSetUserStateCounter < 1 {
		if m.SetUserStateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StateStoreMock.SetUserState at\n%s", m.SetUserStateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StateStoreMock.SetUserState at\n%s with params: %#v", m.SetUserStateMock.defaultExpectation.expectationOrigins.origin, *m.SetUserStateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSetUserState != nil && afterSetUserStateCounter < 1 {
		m.t.Errorf("Expected call to StateStoreMock.SetUserState at\n%s", m.funcSetUserStateOrigin)
	}

	if !m.SetUserStateMock.invocationsDone() && afterSetUserStateCounter > 0 {
		m.t.Errorf("Expected %d calls to StateStoreMock.SetUserState at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SetUserStateMock.expectedInvocations), m.SetUserStateMock.expectedInvocationsOrigin, afterSetUserStateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StateStoreMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSetUserStateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StateStoreMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StateStoreMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSetUserStateDone()
}
