// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package cli

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// RedisMock implements redis
type RedisMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcHDel          func(ctx context.Context, key string, fields ...string) (err error)
	funcHDelOrigin    string
	inspectFuncHDel   func(ctx context.Context, key string, fields ...string)
	afterHDelCounter  uint64
	beforeHDelCounter uint64
	HDelMock          mRedisMockHDel

	funcHExists          func(ctx context.Context, key string, field string) (b1 bool, err error)
	funcHExistsOrigin    string
	inspectFuncHExists   func(ctx context.Context, key string, field string)
	afterHExistsCounter  uint64
	beforeHExistsCounter uint64
	HExistsMock          mRedisMockHExists

	funcHGet          func(ctx context.Context, key string, field string) (s1 string, err error)
	funcHGetOrigin    string
	inspectFuncHGet   func(ctx context.Context, key string, field string)
	afterHGetCounter  uint64
	beforeHGetCounter uint64
	HGetMock          mRedisMockHGet

	funcHGetAll          func(ctx context.Context, key string) (m1 map[string]string, err error)
	funcHGetAllOrigin    string
	inspectFuncHGetAll   func(ctx context.Context, key string)
	afterHGetAllCounter  uint64
	beforeHGetAllCounter uint64
	HGetAllMock          mRedisMockHGetAll

	funcHSet          func(ctx context.Context, key string, values ...interface{}) (err error)
	funcHSetOrigin    string
	inspectFuncHSet   func(ctx context.Context, key string, values ...interface{})
	afterHSetCounter  uint64
	beforeHSetCounter uint64
	HSetMock          mRedisMockHSet
}

// NewRedisMock returns a mock for redis
func NewRedisMock(t minimock.Tester) *RedisMock {
	m := &RedisMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.HDelMock = mRedisMockHDel{mock: m}
	m.HDelMock.callArgs = []*RedisMockHDelParams{}

	m.HExistsMock = mRedisMockHExists{mock: m}
	m.HExistsMock.callArgs = []*RedisMockHExistsParams{}

	m.HGetMock = mRedisMockHGet{mock: m}
	m.HGetMock.callArgs = []*RedisMockHGetParams{}

	m.HGetAllMock = mRedisMockHGetAll{mock: m}
	m.HGetAllMock.callArgs = []*RedisMockHGetAllParams{}

	m.HSetMock = mRedisMockHSet{mock: m}
	m.HSetMock.callArgs = []*RedisMockHSetParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRedisMockHDel struct {
	optional           bool
	mock               *RedisMock
	defaultExpectation *RedisMockHDelExpectation
	expectations       []*RedisMockHDelExpectation

	callArgs []*RedisMockHDelParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RedisMockHDelExpectation specifies expectation struct of the redis.HDel
type RedisMockHDelExpectation struct {
	mock               *RedisMock
	params             *RedisMockHDelParams
	paramPtrs          *RedisMockHDelParamPtrs
	expectationOrigins RedisMockHDelExpectationOrigins
	results            *RedisMockHDelResults
	returnOrigin       string
	Counter            uint64
}

// RedisMockHDelParams contains parameters of the redis.HDel
type RedisMockHDelParams struct {
	ctx    context.Context
	key    string
	fields []string
}

// RedisMockHDelParamPtrs contains pointers to parameters of the redis.HDel
type RedisMockHDelParamPtrs struct {
	ctx    *context.Context
	key    *string
	fields *[]string
}

// RedisMockHDelResults contains results of the redis.HDel
type RedisMockHDelResults struct {
	err error
}

// RedisMockHDelOrigins contains origins of expectations of the redis.HDel
type RedisMockHDelExpectationOrigins struct {
	origin       string
	originCtx    string
	originKey    string
	originFields string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmHDel *mRedisMockHDel) Optional() *mRedisMockHDel {
	mmHDel.optional = true
	return mmHDel
}

// Expect sets up expected params for redis.HDel
func (mmHDel *mRedisMockHDel) Expect(ctx context.Context, key string, fields ...string) *mRedisMockHDel {
	if mmHDel.mock.funcHDel != nil {
		mmHDel.mock.t.Fatalf("RedisMock.HDel mock is already set by Set")
	}

	if mmHDel.defaultExpectation == nil {
		mmHDel.defaultExpectation = &RedisMockHDelExpectation{}
	}

	if mmHDel.defaultExpectation.paramPtrs != nil {
		mmHDel.mock.t.Fatalf("RedisMock.HDel mock is already set by ExpectParams functions")
	}

	mmHDel.defaultExpectation.params = &RedisMockHDelParams{ctx, key, fields}
	mmHDel.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmHDel.expectations {
		if minimock.Equal(e.params, mmHDel.defaultExpectation.params) {
			mmHDel.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmHDel.defaultExpectation.params)
		}
	}

	return mmHDel
}

// ExpectCtxParam1 sets up expected param ctx for redis.HDel
func (mmHDel *mRedisMockHDel) ExpectCtxParam1(ctx context.Context) *mRedisMockHDel {
	if mmHDel.mock.funcHDel != nil {
		mmHDel.mock.t.Fatalf("RedisMock.HDel mock is already set by Set")
	}

	if mmHDel.defaultExpectation == nil {
		mmHDel.defaultExpectation = &RedisMockHDelExpectation{}
	}

	if mmHDel.defaultExpectation.params != nil {
		mmHDel.mock.t.Fatalf("RedisMock.HDel mock is already set by Expect")
	}

	if mmHDel.defaultExpectation.paramPtrs == nil {
		mmHDel.defaultExpectation.paramPtrs = &RedisMockHDelParamPtrs{}
	}
	mmHDel.defaultExpectation.paramPtrs.ctx = &ctx
	mmHDel.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmHDel
}

// ExpectKeyParam2 sets up expected param key for redis.HDel
func (mmHDel *mRedisMockHDel) ExpectKeyParam2(key string) *mRedisMockHDel {
	if mmHDel.mock.funcHDel != nil {
		mmHDel.mock.t.Fatalf("RedisMock.HDel mock is already set by Set")
	}

	if mmHDel.defaultExpectation == nil {
		mmHDel.defaultExpectation = &RedisMockHDelExpectation{}
	}

	if mmHDel.defaultExpectation.params != nil {
		mmHDel.mock.t.Fatalf("RedisMock.HDel mock is already set by Expect")
	}

	if mmHDel.defaultExpectation.paramPtrs == nil {
		mmHDel.defaultExpectation.paramPtrs = &RedisMockHDelParamPtrs{}
	}
	mmHDel.defaultExpectation.paramPtrs.key = &key
	mmHDel.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmHDel
}

// ExpectFieldsParam3 sets up expected param fields for redis.HDel
func (mmHDel *mRedisMockHDel) ExpectFieldsParam3(fields ...string) *mRedisMockHDel {
	if mmHDel.mock.funcHDel != nil {
		mmHDel.mock.t.Fatalf("RedisMock.HDel mock is already set by Set")
	}

	if mmHDel.defaultExpectation == nil {
		mmHDel.defaultExpectation = &RedisMockHDelExpectation{}
	}

	if mmHDel.defaultExpectation.params != nil {
		mmHDel.mock.t.Fatalf("RedisMock.HDel mock is already set by Expect")
	}

	if mmHDel.defaultExpectation.paramPtrs == nil {
		mmHDel.defaultExpectation.paramPtrs = &RedisMockHDelParamPtrs{}
	}
	mmHDel.defaultExpectation.paramPtrs.fields = &fields
	mmHDel.defaultExpectation.expectationOrigins.originFields = minimock.CallerInfo(1)

	return mmHDel
}

// Inspect accepts an inspector function that has same arguments as the redis.HDel
func (mmHDel *mRedisMockHDel) Inspect(f func(ctx context.Context, key string, fields ...string)) *mRedisMockHDel {
	if mmHDel.mock.inspectFuncHDel != nil {
		mmHDel.mock.t.Fatalf("Inspect function is already set for RedisMock.HDel")
	}

	mmHDel.mock.inspectFuncHDel = f

	return mmHDel
}

// Return sets up results that will be returned by redis.HDel
func (mmHDel *mRedisMockHDel) Return(err error) *RedisMock {
	if mmHDel.mock.funcHDel != nil {
		mmHDel.mock.t.Fatalf("RedisMock.HDel mock is already set by Set")
	}

	if mmHDel.defaultExpectation == nil {
		mmHDel.defaultExpectation = &RedisMockHDelExpectation{mock: mmHDel.mock}
	}
	mmHDel.defaultExpectation.results = &RedisMockHDelResults{err}
	mmHDel.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmHDel.mock
}

// Set uses given function f to mock the redis.HDel method
func (mmHDel *mRedisMockHDel) Set(f func(ctx context.Context, key string, fields ...string) (err error)) *RedisMock {
	if mmHDel.defaultExpectation != nil {
		mmHDel.mock.t.Fatalf("Default expectation is already set for the redis.HDel method")
	}

	if len(mmHDel.expectations) > 0 {
		mmHDel.mock.t.Fatalf("Some expectations are already set for the redis.HDel method")
	}

	mmHDel.mock.funcHDel = f
	mmHDel.mock.funcHDelOrigin = minimock.CallerInfo(1)
	return mmHDel.mock
}

// When sets expectation for the redis.HDel which will trigger the result defined by the following
// Then helper
func (mmHDel *mRedisMockHDel) When(ctx context.Context, key string, fields ...string) *RedisMockHDelExpectation {
	if mmHDel.mock.funcHDel != nil {
		mmHDel.mock.t.Fatalf("RedisMock.HDel mock is already set by Set")
	}

	expectation := &RedisMockHDelExpectation{
		mock:               mmHDel.mock,
		params:             &RedisMockHDelParams{ctx, key, fields},
		expectationOrigins: RedisMockHDelExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmHDel.expectations = append(mmHDel.expectations, expectation)
	return expectation
}

// Then sets up redis.HDel return parameters for the expectation previously defined by the When method
func (e *RedisMockHDelExpectation) Then(err error) *RedisMock {
	e.results = &RedisMockHDelResults{err}
	return e.mock
}

// Times sets number of times redis.HDel should be invoked
func (mmHDel *mRedisMockHDel) Times(n uint64) *mRedisMockHDel {
	if n == 0 {
		mmHDel.mock.t.Fatalf("Times of RedisMock.HDel mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmHDel.expectedInvocations, n)
	mmHDel.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmHDel
}

func (mmHDel *mRedisMockHDel) invocationsDone() bool {
	if len(mmHDel.expectations) == 0 && mmHDel.defaultExpectation == nil && mmHDel.mock.funcHDel == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmHDel.mock.afterHDelCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmHDel.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// HDel implements redis
func (mmHDel *RedisMock) HDel(ctx context.Context, key string, fields ...string) (err error) {
	mm_atomic.AddUint64(&mmHDel.beforeHDelCounter, 1)
	defer mm_atomic.AddUint64(&mmHDel.afterHDelCounter, 1)

	mmHDel.t.Helper()

	if mmHDel.inspectFuncHDel != nil {
		mmHDel.inspectFuncHDel(ctx, key, fields...)
	}

	mm_params := RedisMockHDelParams{ctx, key, fields}

	// Record call args
	mmHDel.HDelMock.mutex.Lock()
	mmHDel.HDelMock.callArgs = append(mmHDel.HDelMock.callArgs, &mm_params)
	mmHDel.HDelMock.mutex.Unlock()

	for _, e := range mmHDel.HDelMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmHDel.HDelMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmHDel.HDelMock.defaultExpectation.Counter, 1)
		mm_want := mmHDel.HDelMock.defaultExpectation.params
		mm_want_ptrs := mmHDel.HDelMock.defaultExpectation.paramPtrs

		mm_got := RedisMockHDelParams{ctx, key, fields}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmHDel.t.Errorf("RedisMock.HDel got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHDel.HDelMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmHDel.t.Errorf("RedisMock.HDel got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHDel.HDelMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

			if mm_want_ptrs.fields != nil && !minimock.Equal(*mm_want_ptrs.fields, mm_got.fields) {
				mmHDel.t.Errorf("RedisMock.HDel got unexpected parameter fields, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHDel.HDelMock.defaultExpectation.expectationOrigins.originFields, *mm_want_ptrs.fields, mm_got.fields, minimock.Diff(*mm_want_ptrs.fields, mm_got.fields))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmHDel.t.Errorf("RedisMock.HDel got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmHDel.HDelMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmHDel.HDelMock.defaultExpectation.results
		if mm_results == nil {
			mmHDel.t.Fatal("No results are set for the RedisMock.HDel")
		}
		return (*mm_results).err
	}
	if mmHDel.funcHDel != nil {
		return mmHDel.funcHDel(ctx, key, fields...)
	}
	mmHDel.t.Fatalf("Unexpected call to RedisMock.HDel. %v %v %v", ctx, key, fields)
	return
}

// HDelAfterCounter returns a count of finished RedisMock.HDel invocations
func (mmHDel *RedisMock) HDelAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHDel.afterHDelCounter)
}

// HDelBeforeCounter returns a count of RedisMock.HDel invocations
func (mmHDel *RedisMock) HDelBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHDel.beforeHDelCounter)
}

// Calls returns a list of arguments used in each call to RedisMock.HDel.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmHDel *mRedisMockHDel) Calls() []*RedisMockHDelParams {
	mmHDel.mutex.RLock()

	argCopy := make([]*RedisMockHDelParams, len(mmHDel.callArgs))
	copy(argCopy, mmHDel.callArgs)

	mmHDel.mutex.RUnlock()

	return argCopy
}

// MinimockHDelDone returns true if the count of the HDel invocations corresponds
// the number of defined expectations
func (m *RedisMock) MinimockHDelDone() bool {
	if m.HDelMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.HDelMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.HDelMock.invocationsDone()
}

// MinimockHDelInspect logs each unmet expectation
func (m *RedisMock) MinimockHDelInspect() {
	for _, e := range m.HDelMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RedisMock.HDel at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterHDelCounter := mm_atomic.LoadUint64(&m.afterHDelCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.HDelMock.defaultExpectation != nil && afterHDelCounter < 1 {
		if m.HDelMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RedisMock.HDel at\n%s", m.HDelMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RedisMock.HDel at\n%s with params: %#v", m.HDelMock.defaultExpectation.expectationOrigins.origin, *m.HDelMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcHDel != nil && afterHDelCounter < 1 {
		m.t.Errorf("Expected call to RedisMock.HDel at\n%s", m.funcHDelOrigin)
	}

	if !m.HDelMock.invocationsDone() && afterHDelCounter > 0 {
		m.t.Errorf("Expected %d calls to RedisMock.HDel at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.HDelMock.expectedInvocations), m.HDelMock.expectedInvocationsOrigin, afterHDelCounter)
	}
}

type mRedisMockHExists struct {
	optional           bool
	mock               *RedisMock
	defaultExpectation *RedisMockHExistsExpectation
	expectations       []*RedisMockHExistsExpectation

	callArgs []*RedisMockHExistsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RedisMockHExistsExpectation specifies expectation struct of the redis.HExists
type RedisMockHExistsExpectation struct {
	mock               *RedisMock
	params             *RedisMockHExistsParams
	paramPtrs          *RedisMockHExistsParamPtrs
	expectationOrigins RedisMockHExistsExpectationOrigins
	results            *RedisMockHExistsResults
	returnOrigin       string
	Counter            uint64
}

// RedisMockHExistsParams contains parameters of the redis.HExists
type RedisMockHExistsParams struct {
	ctx   context.Context
	key   string
	field string
}

// RedisMockHExistsParamPtrs contains pointers to parameters of the redis.HExists
type RedisMockHExistsParamPtrs struct {
	ctx   *context.Context
	key   *string
	field *string
}

// RedisMockHExistsResults contains results of the redis.HExists
type RedisMockHExistsResults struct {
	b1  bool
	err error
}

// RedisMockHExistsOrigins contains origins of expectations of the redis.HExists
type RedisMockHExistsExpectationOrigins struct {
	origin      string
	originCtx   string
	originKey   string
	originField string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmHExists *mRedisMockHExists) Optional() *mRedisMockHExists {
	mmHExists.optional = true
	return mmHExists
}

// Expect sets up expected params for redis.HExists
func (mmHExists *mRedisMockHExists) Expect(ctx context.Context, key string, field string) *mRedisMockHExists {
	if mmHExists.mock.funcHExists != nil {
		mmHExists.mock.t.Fatalf("RedisMock.HExists mock is already set by Set")
	}

	if mmHExists.defaultExpectation == nil {
		mmHExists.defaultExpectation = &RedisMockHExistsExpectation{}
	}

	if mmHExists.defaultExpectation.paramPtrs != nil {
		mmHExists.mock.t.Fatalf("RedisMock.HExists mock is already set by ExpectParams functions")
	}

	mmHExists.defaultExpectation.params = &RedisMockHExistsParams{ctx, key, field}
	mmHExists.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmHExists.expectations {
		if minimock.Equal(e.params, mmHExists.defaultExpectation.params) {
			mmHExists.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmHExists.defaultExpectation.params)
		}
	}

	return mmHExists
}

// ExpectCtxParam1 sets up expected param ctx for redis.HExists
func (mmHExists *mRedisMockHExists) ExpectCtxParam1(ctx context.Context) *mRedisMockHExists {
	if mmHExists.mock.funcHExists != nil {
		mmHExists.mock.t.Fatalf("RedisMock.HExists mock is already set by Set")
	}

	if mmHExists.defaultExpectation == nil {
		mmHExists.defaultExpectation = &RedisMockHExistsExpectation{}
	}

	if mmHExists.defaultExpectation.params != nil {
		mmHExists.mock.t.Fatalf("RedisMock.HExists mock is already set by Expect")
	}

	if mmHExists.defaultExpectation.paramPtrs == nil {
		mmHExists.defaultExpectation.paramPtrs = &RedisMockHExistsParamPtrs{}
	}
	mmHExists.defaultExpectation.paramPtrs.ctx = &ctx
	mmHExists.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmHExists
}

// ExpectKeyParam2 sets up expected param key for redis.HExists
func (mmHExists *mRedisMockHExists) ExpectKeyParam2(key string) *mRedisMockHExists {
	if mmHExists.mock.funcHExists != nil {
		mmHExists.mock.t.Fatalf("RedisMock.HExists mock is already set by Set")
	}

	if mmHExists.defaultExpectation == nil {
		mmHExists.defaultExpectation = &RedisMockHExistsExpectation{}
	}

	if mmHExists.defaultExpectation.params != nil {
		mmHExists.mock.t.Fatalf("RedisMock.HExists mock is already set by Expect")
	}

	if mmHExists.defaultExpectation.paramPtrs == nil {
		mmHExists.defaultExpectation.paramPtrs = &RedisMockHExistsParamPtrs{}
	}
	mmHExists.defaultExpectation.paramPtrs.key = &key
	mmHExists.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmHExists
}

// ExpectFieldParam3 sets up expected param field for redis.HExists
func (mmHExists *mRedisMockHExists) ExpectFieldParam3(field string) *mRedisMockHExists {
	if mmHExists.mock.funcHExists != nil {
		mmHExists.mock.t.Fatalf("RedisMock.HExists mock is already set by Set")
	}

	if mmHExists.defaultExpectation == nil {
		mmHExists.defaultExpectation = &RedisMockHExistsExpectation{}
	}

	if mmHExists.defaultExpectation.params != nil {
		mmHExists.mock.t.Fatalf("RedisMock.HExists mock is already set by Expect")
	}

	if mmHExists.defaultExpectation.paramPtrs == nil {
		mmHExists.defaultExpectation.paramPtrs = &RedisMockHExistsParamPtrs{}
	}
	mmHExists.defaultExpectation.paramPtrs.field = &field
	mmHExists.defaultExpectation.expectationOrigins.originField = minimock.CallerInfo(1)

	return mmHExists
}

// Inspect accepts an inspector function that has same arguments as the redis.HExists
func (mmHExists *mRedisMockHExists) Inspect(f func(ctx context.Context, key string, field string)) *mRedisMockHExists {
	if mmHExists.mock.inspectFuncHExists != nil {
		mmHExists.mock.t.Fatalf("Inspect function is already set for RedisMock.HExists")
	}

	mmHExists.mock.inspectFuncHExists = f

	return mmHExists
}

// Return sets up results that will be returned by redis.HExists
func (mmHExists *mRedisMockHExists) Return(b1 bool, err error) *RedisMock {
	if mmHExists.mock.funcHExists != nil {
		mmHExists.mock.t.Fatalf("RedisMock.HExists mock is already set by Set")
	}

	if mmHExists.defaultExpectation == nil {
		mmHExists.defaultExpectation = &RedisMockHExistsExpectation{mock: mmHExists.mock}
	}
	mmHExists.defaultExpectation.results = &RedisMockHExistsResults{b1, err}
	mmHExists.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmHExists.mock
}

// Set uses given function f to mock the redis.HExists method
func (mmHExists *mRedisMockHExists) Set(f func(ctx context.Context, key string, field string) (b1 bool, err error)) *RedisMock {
	if mmHExists.defaultExpectation != nil {
		mmHExists.mock.t.Fatalf("Default expectation is already set for the redis.HExists method")
	}

	if len(mmHExists.expectations) > 0 {
		mmHExists.mock.t.Fatalf("Some expectations are already set for the redis.HExists method")
	}

	mmHExists.mock.funcHExists = f
	mmHExists.mock.funcHExistsOrigin = minimock.CallerInfo(1)
	return mmHExists.mock
}

// When sets expectation for the redis.HExists which will trigger the result defined by the following
// Then helper
func (mmHExists *mRedisMockHExists) When(ctx context.Context, key string, field string) *RedisMockHExistsExpectation {
	if mmHExists.mock.funcHExists != nil {
		mmHExists.mock.t.Fatalf("RedisMock.HExists mock is already set by Set")
	}

	expectation := &RedisMockHExistsExpectation{
		mock:               mmHExists.mock,
		params:             &RedisMockHExistsParams{ctx, key, field},
		expectationOrigins: RedisMockHExistsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmHExists.expectations = append(mmHExists.expectations, expectation)
	return expectation
}

// Then sets up redis.HExists return parameters for the expectation previously defined by the When method
func (e *RedisMockHExistsExpectation) Then(b1 bool, err error) *RedisMock {
	e.results = &RedisMockHExistsResults{b1, err}
	return e.mock
}

// Times sets number of times redis.HExists should be invoked
func (mmHExists *mRedisMockHExists) Times(n uint64) *mRedisMockHExists {
	if n == 0 {
		mmHExists.mock.t.Fatalf("Times of RedisMock.HExists mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmHExists.expectedInvocations, n)
	mmHExists.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmHExists
}

func (mmHExists *mRedisMockHExists) invocationsDone() bool {
	if len(mmHExists.expectations) == 0 && mmHExists.defaultExpectation == nil && mmHExists.mock.funcHExists == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmHExists.mock.afterHExistsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmHExists.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// HExists implements redis
func (mmHExists *RedisMock) HExists(ctx context.Context, key string, field string) (b1 bool, err error) {
	mm_atomic.AddUint64(&mmHExists.beforeHExistsCounter, 1)
	defer mm_atomic.AddUint64(&mmHExists.afterHExistsCounter, 1)

	mmHExists.t.Helper()

	if mmHExists.inspectFuncHExists != nil {
		mmHExists.inspectFuncHExists(ctx, key, field)
	}

	mm_params := RedisMockHExistsParams{ctx, key, field}

	// Record call args
	mmHExists.HExistsMock.mutex.Lock()
	mmHExists.HExistsMock.callArgs = append(mmHExists.HExistsMock.callArgs, &mm_params)
	mmHExists.HExistsMock.mutex.Unlock()

	for _, e := range mmHExists.HExistsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.b1, e.results.err
		}
	}

	if mmHExists.HExistsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmHExists.HExistsMock.defaultExpectation.Counter, 1)
		mm_want := mmHExists.HExistsMock.defaultExpectation.params
		mm_want_ptrs := mmHExists.HExistsMock.defaultExpectation.paramPtrs

		mm_got := RedisMockHExistsParams{ctx, key, field}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmHExists.t.Errorf("RedisMock.HExists got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHExists.HExistsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmHExists.t.Errorf("RedisMock.HExists got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHExists.HExistsMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

			if mm_want_ptrs.field != nil && !minimock.Equal(*mm_want_ptrs.field, mm_got.field) {
				mmHExists.t.Errorf("RedisMock.HExists got unexpected parameter field, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHExists.HExistsMock.defaultExpectation.expectationOrigins.originField, *mm_want_ptrs.field, mm_got.field, minimock.Diff(*mm_want_ptrs.field, mm_got.field))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmHExists.t.Errorf("RedisMock.HExists got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmHExists.HExistsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmHExists.HExistsMock.defaultExpectation.results
		if mm_results == nil {
			mmHExists.t.Fatal("No results are set for the RedisMock.HExists")
		}
		return (*mm_results).b1, (*mm_results).err
	}
	if mmHExists.funcHExists != nil {
		return mmHExists.funcHExists(ctx, key, field)
	}
	mmHExists.t.Fatalf("Unexpected call to RedisMock.HExists. %v %v %v", ctx, key, field)
	return
}

// HExistsAfterCounter returns a count of finished RedisMock.HExists invocations
func (mmHExists *RedisMock) HExistsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHExists.afterHExistsCounter)
}

// HExistsBeforeCounter returns a count of RedisMock.HExists invocations
func (mmHExists *RedisMock) HExistsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHExists.beforeHExistsCounter)
}

// Calls returns a list of arguments used in each call to RedisMock.HExists.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmHExists *mRedisMockHExists) Calls() []*RedisMockHExistsParams {
	mmHExists.mutex.RLock()

	argCopy := make([]*RedisMockHExistsParams, len(mmHExists.callArgs))
	copy(argCopy, mmHExists.callArgs)

	mmHExists.mutex.RUnlock()

	return argCopy
}

// MinimockHExistsDone returns true if the count of the HExists invocations corresponds
// the number of defined expectations
func (m *RedisMock) MinimockHExistsDone() bool {
	if m.HExistsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.HExistsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.HExistsMock.invocationsDone()
}

// MinimockHExistsInspect logs each unmet expectation
func (m *RedisMock) MinimockHExistsInspect() {
	for _, e := range m.HExistsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RedisMock.HExists at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterHExistsCounter := mm_atomic.LoadUint64(&m.afterHExistsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.HExistsMock.defaultExpectation != nil && afterHExistsCounter < 1 {
		if m.HExistsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RedisMock.HExists at\n%s", m.HExistsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RedisMock.HExists at\n%s with params: %#v", m.HExistsMock.defaultExpectation.expectationOrigins.origin, *m.HExistsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcHExists != nil && afterHExistsCounter < 1 {
		m.t.Errorf("Expected call to RedisMock.HExists at\n%s", m.funcHExistsOrigin)
	}

	if !m.HExistsMock.invocationsDone() && afterHExistsCounter > 0 {
		m.t.Errorf("Expected %d calls to RedisMock.HExists at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.HExistsMock.expectedInvocations), m.HExistsMock.expectedInvocationsOrigin, afterHExistsCounter)
	}
}

type mRedisMockHGet struct {
	optional           bool
	mock               *RedisMock
	defaultExpectation *RedisMockHGetExpectation
	expectations       []*RedisMockHGetExpectation

	callArgs []*RedisMockHGetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RedisMockHGetExpectation specifies expectation struct of the redis.HGet
type RedisMockHGetExpectation struct {
	mock               *RedisMock
	params             *RedisMockHGetParams
	paramPtrs          *RedisMockHGetParamPtrs
	expectationOrigins RedisMockHGetExpectationOrigins
	results            *RedisMockHGetResults
	returnOrigin       string
	Counter            uint64
}

// RedisMockHGetParams contains parameters of the redis.HGet
type RedisMockHGetParams struct {
	ctx   context.Context
	key   string
	field string
}

// RedisMockHGetParamPtrs contains pointers to parameters of the redis.HGet
type RedisMockHGetParamPtrs struct {
	ctx   *context.Context
	key   *string
	field *string
}

// RedisMockHGetResults contains results of the redis.HGet
type RedisMockHGetResults struct {
	s1  string
	err error
}

// RedisMockHGetOrigins contains origins of expectations of the redis.HGet
type RedisMockHGetExpectationOrigins struct {
	origin      string
	originCtx   string
	originKey   string
	originField string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmHGet *mRedisMockHGet) Optional() *mRedisMockHGet {
	mmHGet.optional = true
	return mmHGet
}

// Expect sets up expected params for redis.HGet
func (mmHGet *mRedisMockHGet) Expect(ctx context.Context, key string, field string) *mRedisMockHGet {
	if mmHGet.mock.funcHGet != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Set")
	}

	if mmHGet.defaultExpectation == nil {
		mmHGet.defaultExpectation = &RedisMockHGetExpectation{}
	}

	if mmHGet.defaultExpectation.paramPtrs != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by ExpectParams functions")
	}

	mmHGet.defaultExpectation.params = &RedisMockHGetParams{ctx, key, field}
	mmHGet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmHGet.expectations {
		if minimock.Equal(e.params, mmHGet.defaultExpectation.params) {
			mmHGet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmHGet.defaultExpectation.params)
		}
	}

	return mmHGet
}

// ExpectCtxParam1 sets up expected param ctx for redis.HGet
func (mmHGet *mRedisMockHGet) ExpectCtxParam1(ctx context.Context) *mRedisMockHGet {
	if mmHGet.mock.funcHGet != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Set")
	}

	if mmHGet.defaultExpectation == nil {
		mmHGet.defaultExpectation = &RedisMockHGetExpectation{}
	}

	if mmHGet.defaultExpectation.params != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Expect")
	}

	if mmHGet.defaultExpectation.paramPtrs == nil {
		mmHGet.defaultExpectation.paramPtrs = &RedisMockHGetParamPtrs{}
	}
	mmHGet.defaultExpectation.paramPtrs.ctx = &ctx
	mmHGet.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmHGet
}

// ExpectKeyParam2 sets up expected param key for redis.HGet
func (mmHGet *mRedisMockHGet) ExpectKeyParam2(key string) *mRedisMockHGet {
	if mmHGet.mock.funcHGet != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Set")
	}

	if mmHGet.defaultExpectation == nil {
		mmHGet.defaultExpectation = &RedisMockHGetExpectation{}
	}

	if mmHGet.defaultExpectation.params != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Expect")
	}

	if mmHGet.defaultExpectation.paramPtrs == nil {
		mmHGet.defaultExpectation.paramPtrs = &RedisMockHGetParamPtrs{}
	}
	mmHGet.defaultExpectation.paramPtrs.key = &key
	mmHGet.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmHGet
}

// ExpectFieldParam3 sets up expected param field for redis.HGet
func (mmHGet *mRedisMockHGet) ExpectFieldParam3(field string) *mRedisMockHGet {
	if mmHGet.mock.funcHGet != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Set")
	}

	if mmHGet.defaultExpectation == nil {
		mmHGet.defaultExpectation = &RedisMockHGetExpectation{}
	}

	if mmHGet.defaultExpectation.params != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Expect")
	}

	if mmHGet.defaultExpectation.paramPtrs == nil {
		mmHGet.defaultExpectation.paramPtrs = &RedisMockHGetParamPtrs{}
	}
	mmHGet.defaultExpectation.paramPtrs.field = &field
	mmHGet.defaultExpectation.expectationOrigins.originField = minimock.CallerInfo(1)

	return mmHGet
}

// Inspect accepts an inspector function that has same arguments as the redis.HGet
func (mmHGet *mRedisMockHGet) Inspect(f func(ctx context.Context, key string, field string)) *mRedisMockHGet {
	if mmHGet.mock.inspectFuncHGet != nil {
		mmHGet.mock.t.Fatalf("Inspect function is already set for RedisMock.HGet")
	}

	mmHGet.mock.inspectFuncHGet = f

	return mmHGet
}

// Return sets up results that will be returned by redis.HGet
func (mmHGet *mRedisMockHGet) Return(s1 string, err error) *RedisMock {
	if mmHGet.mock.funcHGet != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Set")
	}

	if mmHGet.defaultExpectation == nil {
		mmHGet.defaultExpectation = &RedisMockHGetExpectation{mock: mmHGet.mock}
	}
	mmHGet.defaultExpectation.results = &RedisMockHGetResults{s1, err}
	mmHGet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmHGet.mock
}

// Set uses given function f to mock the redis.HGet method
func (mmHGet *mRedisMockHGet) Set(f func(ctx context.Context, key string, field string) (s1 string, err error)) *RedisMock {
	if mmHGet.defaultExpectation != nil {
		mmHGet.mock.t.Fatalf("Default expectation is already set for the redis.HGet method")
	}

	if len(mmHGet.expectations) > 0 {
		mmHGet.mock.t.Fatalf("Some expectations are already set for the redis.HGet method")
	}

	mmHGet.mock.funcHGet = f
	mmHGet.mock.funcHGetOrigin = minimock.CallerInfo(1)
	return mmHGet.mock
}

// When sets expectation for the redis.HGet which will trigger the result defined by the following
// Then helper
func (mmHGet *mRedisMockHGet) When(ctx context.Context, key string, field string) *RedisMockHGetExpectation {
	if mmHGet.mock.funcHGet != nil {
		mmHGet.mock.t.Fatalf("RedisMock.HGet mock is already set by Set")
	}

	expectation := &RedisMockHGetExpectation{
		mock:               mmHGet.mock,
		params:             &RedisMockHGetParams{ctx, key, field},
		expectationOrigins: RedisMockHGetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmHGet.expectations = append(mmHGet.expectations, expectation)
	return expectation
}

// Then sets up redis.HGet return parameters for the expectation previously defined by the When method
func (e *RedisMockHGetExpectation) Then(s1 string, err error) *RedisMock {
	e.results = &RedisMockHGetResults{s1, err}
	return e.mock
}

// Times sets number of times redis.HGet should be invoked
func (mmHGet *mRedisMockHGet) Times(n uint64) *mRedisMockHGet {
	if n == 0 {
		mmHGet.mock.t.Fatalf("Times of RedisMock.HGet mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmHGet.expectedInvocations, n)
	mmHGet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmHGet
}

func (mmHGet *mRedisMockHGet) invocationsDone() bool {
	if len(mmHGet.expectations) == 0 && mmHGet.defaultExpectation == nil && mmHGet.mock.funcHGet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmHGet.mock.afterHGetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmHGet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// HGet implements redis
func (mmHGet *RedisMock) HGet(ctx context.Context, key string, field string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmHGet.beforeHGetCounter, 1)
	defer mm_atomic.AddUint64(&mmHGet.afterHGetCounter, 1)

	mmHGet.t.Helper()

	if mmHGet.inspectFuncHGet != nil {
		mmHGet.inspectFuncHGet(ctx, key, field)
	}

	mm_params := RedisMockHGetParams{ctx, key, field}

	// Record call args
	mmHGet.HGetMock.mutex.Lock()
	mmHGet.HGetMock.callArgs = append(mmHGet.HGetMock.callArgs, &mm_params)
	mmHGet.HGetMock.mutex.Unlock()

	for _, e := range mmHGet.HGetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmHGet.HGetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmHGet.HGetMock.defaultExpectation.Counter, 1)
		mm_want := mmHGet.HGetMock.defaultExpectation.params
		mm_want_ptrs := mmHGet.HGetMock.defaultExpectation.paramPtrs

		mm_got := RedisMockHGetParams{ctx, key, field}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmHGet.t.Errorf("RedisMock.HGet got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHGet.HGetMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmHGet.t.Errorf("RedisMock.HGet got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHGet.HGetMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

			if mm_want_ptrs.field != nil && !minimock.Equal(*mm_want_ptrs.field, mm_got.field) {
				mmHGet.t.Errorf("RedisMock.HGet got unexpected parameter field, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHGet.HGetMock.defaultExpectation.expectationOrigins.originField, *mm_want_ptrs.field, mm_got.field, minimock.Diff(*mm_want_ptrs.field, mm_got.field))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmHGet.t.Errorf("RedisMock.HGet got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmHGet.HGetMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmHGet.HGetMock.defaultExpectation.results
		if mm_results == nil {
			mmHGet.t.Fatal("No results are set for the RedisMock.HGet")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmHGet.funcHGet != nil {
		return mmHGet.funcHGet(ctx, key, field)
	}
	mmHGet.t.Fatalf("Unexpected call to RedisMock.HGet. %v %v %v", ctx, key, field)
	return
}

// HGetAfterCounter returns a count of finished RedisMock.HGet invocations
func (mmHGet *RedisMock) HGetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHGet.afterHGetCounter)
}

// HGetBeforeCounter returns a count of RedisMock.HGet invocations
func (mmHGet *RedisMock) HGetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHGet.beforeHGetCounter)
}

// Calls returns a list of arguments used in each call to RedisMock.HGet.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmHGet *mRedisMockHGet) Calls() []*RedisMockHGetParams {
	mmHGet.mutex.RLock()

	argCopy := make([]*RedisMockHGetParams, len(mmHGet.callArgs))
	copy(argCopy, mmHGet.callArgs)

	mmHGet.mutex.RUnlock()

	return argCopy
}

// MinimockHGetDone returns true if the count of the HGet invocations corresponds
// the number of defined expectations
func (m *RedisMock) MinimockHGetDone() bool {
	if m.HGetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.HGetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.HGetMock.invocationsDone()
}

// MinimockHGetInspect logs each unmet expectation
func (m *RedisMock) MinimockHGetInspect() {
	for _, e := range m.HGetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RedisMock.HGet at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterHGetCounter := mm_atomic.LoadUint64(&m.afterHGetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.HGetMock.defaultExpectation != nil && afterHGetCounter < 1 {
		if m.HGetMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RedisMock.HGet at\n%s", m.HGetMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RedisMock.HGet at\n%s with params: %#v", m.HGetMock.defaultExpectation.expectationOrigins.origin, *m.HGetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcHGet != nil && afterHGetCounter < 1 {
		m.t.Errorf("Expected call to RedisMock.HGet at\n%s", m.funcHGetOrigin)
	}

	if !m.HGetMock.invocationsDone() && afterHGetCounter > 0 {
		m.t.Errorf("Expected %d calls to RedisMock.HGet at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.HGetMock.expectedInvocations), m.HGetMock.expectedInvocationsOrigin, afterHGetCounter)
	}
}

type mRedisMockHGetAll struct {
	optional           bool
	mock               *RedisMock
	defaultExpectation *RedisMockHGetAllExpectation
	expectations       []*RedisMockHGetAllExpectation

	callArgs []*RedisMockHGetAllParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RedisMockHGetAllExpectation specifies expectation struct of the redis.HGetAll
type RedisMockHGetAllExpectation struct {
	mock               *RedisMock
	params             *RedisMockHGetAllParams
	paramPtrs          *RedisMockHGetAllParamPtrs
	expectationOrigins RedisMockHGetAllExpectationOrigins
	results            *RedisMockHGetAllResults
	returnOrigin       string
	Counter            uint64
}

// RedisMockHGetAllParams contains parameters of the redis.HGetAll
type RedisMockHGetAllParams struct {
	ctx context.Context
	key string
}

// RedisMockHGetAllParamPtrs contains pointers to parameters of the redis.HGetAll
type RedisMockHGetAllParamPtrs struct {
	ctx *context.Context
	key *string
}

// RedisMockHGetAllResults contains results of the redis.HGetAll
type RedisMockHGetAllResults struct {
	m1  map[string]string
	err error
}

// RedisMockHGetAllOrigins contains origins of expectations of the redis.HGetAll
type RedisMockHGetAllExpectationOrigins struct {
	origin    string
	originCtx string
	originKey string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmHGetAll *mRedisMockHGetAll) Optional() *mRedisMockHGetAll {
	mmHGetAll.optional = true
	return mmHGetAll
}

// Expect sets up expected params for redis.HGetAll
func (mmHGetAll *mRedisMockHGetAll) Expect(ctx context.Context, key string) *mRedisMockHGetAll {
	if mmHGetAll.mock.funcHGetAll != nil {
		mmHGetAll.mock.t.Fatalf("RedisMock.HGetAll mock is already set by Set")
	}

	if mmHGetAll.defaultExpectation == nil {
		mmHGetAll.defaultExpectation = &RedisMockHGetAllExpectation{}
	}

	if mmHGetAll.defaultExpectation.paramPtrs != nil {
		mmHGetAll.mock.t.Fatalf("RedisMock.HGetAll mock is already set by ExpectParams functions")
	}

	mmHGetAll.defaultExpectation.params = &RedisMockHGetAllParams{ctx, key}
	mmHGetAll.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmHGetAll.expectations {
		if minimock.Equal(e.params, mmHGetAll.defaultExpectation.params) {
			mmHGetAll.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmHGetAll.defaultExpectation.params)
		}
	}

	return mmHGetAll
}

// ExpectCtxParam1 sets up expected param ctx for redis.HGetAll
func (mmHGetAll *mRedisMockHGetAll) ExpectCtxParam1(ctx context.Context) *mRedisMockHGetAll {
	if mmHGetAll.mock.funcHGetAll != nil {
		mmHGetAll.mock.t.Fatalf("RedisMock.HGetAll mock is already set by Set")
	}

	if mmHGetAll.defaultExpectation == nil {
		mmHGetAll.defaultExpectation = &RedisMockHGetAllExpectation{}
	}

	if mmHGetAll.defaultExpectation.params != nil {
		mmHGetAll.mock.t.Fatalf("RedisMock.HGetAll mock is already set by Expect")
	}

	if mmHGetAll.defaultExpectation.paramPtrs == nil {
		mmHGetAll.defaultExpectation.paramPtrs = &RedisMockHGetAllParamPtrs{}
	}
	mmHGetAll.defaultExpectation.paramPtrs.ctx = &ctx
	mmHGetAll.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmHGetAll
}

// ExpectKeyParam2 sets up expected param key for redis.HGetAll
func (mmHGetAll *mRedisMockHGetAll) ExpectKeyParam2(key string) *mRedisMockHGetAll {
	if mmHGetAll.mock.funcHGetAll != nil {
		mmHGetAll.mock.t.Fatalf("RedisMock.HGetAll mock is already set by Set")
	}

	if mmHGetAll.defaultExpectation == nil {
		mmHGetAll.defaultExpectation = &RedisMockHGetAllExpectation{}
	}

	if mmHGetAll.defaultExpectation.params != nil {
		mmHGetAll.mock.t.Fatalf("RedisMock.HGetAll mock is already set by Expect")
	}

	if mmHGetAll.defaultExpectation.paramPtrs == nil {
		mmHGetAll.defaultExpectation.paramPtrs = &RedisMockHGetAllParamPtrs{}
	}
	mmHGetAll.defaultExpectation.paramPtrs.key = &key
	mmHGetAll.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmHGetAll
}

// Inspect accepts an inspector function that has same arguments as the redis.HGetAll
func (mmHGetAll *mRedisMockHGetAll) Inspect(f func(ctx context.Context, key string)) *mRedisMockHGetAll {
	if mmHGetAll.mock.inspectFuncHGetAll != nil {
		mmHGetAll.mock.t.Fatalf("Inspect function is already set for RedisMock.HGetAll")
	}

	mmHGetAll.mock.inspectFuncHGetAll = f

	return mmHGetAll
}

// Return sets up results that will be returned by redis.HGetAll
func (mmHGetAll *mRedisMockHGetAll) Return(m1 map[string]string, err error) *RedisMock {
	if mmHGetAll.mock.funcHGetAll != nil {
		mmHGetAll.mock.t.Fatalf("RedisMock.HGetAll mock is already set by Set")
	}

	if mmHGetAll.defaultExpectation == nil {
		mmHGetAll.defaultExpectation = &RedisMockHGetAllExpectation{mock: mmHGetAll.mock}
	}
	mmHGetAll.defaultExpectation.results = &RedisMockHGetAllResults{m1, err}
	mmHGetAll.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmHGetAll.mock
}

// Set uses given function f to mock the redis.HGetAll method
func (mmHGetAll *mRedisMockHGetAll) Set(f func(ctx context.Context, key string) (m1 map[string]string, err error)) *RedisMock {
	if mmHGetAll.defaultExpectation != nil {
		mmHGetAll.mock.t.Fatalf("Default expectation is already set for the redis.HGetAll method")
	}

	if len(mmHGetAll.expectations) > 0 {
		mmHGetAll.mock.t.Fatalf("Some expectations are already set for the redis.HGetAll method")
	}

	mmHGetAll.mock.funcHGetAll = f
	mmHGetAll.mock.funcHGetAllOrigin = minimock.CallerInfo(1)
	return mmHGetAll.mock
}

// When sets expectation for the redis.HGetAll which will trigger the result defined by the following
// Then helper
func (mmHGetAll *mRedisMockHGetAll) When(ctx context.Context, key string) *RedisMockHGetAllExpectation {
	if mmHGetAll.mock.funcHGetAll != nil {
		mmHGetAll.mock.t.Fatalf("RedisMock.HGetAll mock is already set by Set")
	}

	expectation := &RedisMockHGetAllExpectation{
		mock:               mmHGetAll.mock,
		params:             &RedisMockHGetAllParams{ctx, key},
		expectationOrigins: RedisMockHGetAllExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmHGetAll.expectations = append(mmHGetAll.expectations, expectation)
	return expectation
}

// Then sets up redis.HGetAll return parameters for the expectation previously defined by the When method
func (e *RedisMockHGetAllExpectation) Then(m1 map[string]string, err error) *RedisMock {
	e.results = &RedisMockHGetAllResults{m1, err}
	return e.mock
}

// Times sets number of times redis.HGetAll should be invoked
func (mmHGetAll *mRedisMockHGetAll) Times(n uint64) *mRedisMockHGetAll {
	if n == 0 {
		mmHGetAll.mock.t.Fatalf("Times of RedisMock.HGetAll mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmHGetAll.expectedInvocations, n)
	mmHGetAll.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmHGetAll
}

func (mmHGetAll *mRedisMockHGetAll) invocationsDone() bool {
	if len(mmHGetAll.expectations) == 0 && mmHGetAll.defaultExpectation == nil && mmHGetAll.mock.funcHGetAll == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmHGetAll.mock.afterHGetAllCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmHGetAll.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// HGetAll implements redis
func (mmHGetAll *RedisMock) HGetAll(ctx context.Context, key string) (m1 map[string]string, err error) {
	mm_atomic.AddUint64(&mmHGetAll.beforeHGetAllCounter, 1)
	defer mm_atomic.AddUint64(&mmHGetAll.afterHGetAllCounter, 1)

	mmHGetAll.t.Helper()

	if mmHGetAll.inspectFuncHGetAll != nil {
		mmHGetAll.inspectFuncHGetAll(ctx, key)
	}

	mm_params := RedisMockHGetAllParams{ctx, key}

	// Record call args
	mmHGetAll.HGetAllMock.mutex.Lock()
	mmHGetAll.HGetAllMock.callArgs = append(mmHGetAll.HGetAllMock.callArgs, &mm_params)
	mmHGetAll.HGetAllMock.mutex.Unlock()

	for _, e := range mmHGetAll.HGetAllMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.m1, e.results.err
		}
	}

	if mmHGetAll.HGetAllMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmHGetAll.HGetAllMock.defaultExpectation.Counter, 1)
		mm_want := mmHGetAll.HGetAllMock.defaultExpectation.params
		mm_want_ptrs := mmHGetAll.HGetAllMock.defaultExpectation.paramPtrs

		mm_got := RedisMockHGetAllParams{ctx, key}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmHGetAll.t.Errorf("RedisMock.HGetAll got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHGetAll.HGetAllMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmHGetAll.t.Errorf("RedisMock.HGetAll got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHGetAll.HGetAllMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmHGetAll.t.Errorf("RedisMock.HGetAll got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmHGetAll.HGetAllMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmHGetAll.HGetAllMock.defaultExpectation.results
		if mm_results == nil {
			mmHGetAll.t.Fatal("No results are set for the RedisMock.HGetAll")
		}
		return (*mm_results).m1, (*mm_results).err
	}
	if mmHGetAll.funcHGetAll != nil {
		return mmHGetAll.funcHGetAll(ctx, key)
	}
	mmHGetAll.t.Fatalf("Unexpected call to RedisMock.HGetAll. %v %v", ctx, key)
	return
}

// HGetAllAfterCounter returns a count of finished RedisMock.HGetAll invocations
func (mmHGetAll *RedisMock) HGetAllAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHGetAll.afterHGetAllCounter)
}

// HGetAllBeforeCounter returns a count of RedisMock.HGetAll invocations
func (mmHGetAll *RedisMock) HGetAllBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHGetAll.beforeHGetAllCounter)
}

// Calls returns a list of arguments used in each call to RedisMock.HGetAll.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmHGetAll *mRedisMockHGetAll) Calls() []*RedisMockHGetAllParams {
	mmHGetAll.mutex.RLock()

	argCopy := make([]*RedisMockHGetAllParams, len(mmHGetAll.callArgs))
	copy(argCopy, mmHGetAll.callArgs)

	mmHGetAll.mutex.RUnlock()

	return argCopy
}

// MinimockHGetAllDone returns true if the count of the HGetAll invocations corresponds
// the number of defined expectations
func (m *RedisMock) MinimockHGetAllDone() bool {
	if m.HGetAllMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.HGetAllMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.HGetAllMock.invocationsDone()
}

// MinimockHGetAllInspect logs each unmet expectation
func (m *RedisMock) MinimockHGetAllInspect() {
	for _, e := range m.HGetAllMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RedisMock.HGetAll at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterHGetAllCounter := mm_atomic.LoadUint64(&m.afterHGetAllCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.HGetAllMock.defaultExpectation != nil && afterHGetAllCounter < 1 {
		if m.HGetAllMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RedisMock.HGetAll at\n%s", m.HGetAllMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RedisMock.HGetAll at\n%s with params: %#v", m.HGetAllMock.defaultExpectation.expectationOrigins.origin, *m.HGetAllMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcHGetAll != nil && afterHGetAllCounter < 1 {
		m.t.Errorf("Expected call to RedisMock.HGetAll at\n%s", m.funcHGetAllOrigin)
	}

	if !m.HGetAllMock.invocationsDone() && afterHGetAllCounter > 0 {
		m.t.Errorf("Expected %d calls to RedisMock.HGetAll at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.HGetAllMock.expectedInvocations), m.HGetAllMock.expectedInvocationsOrigin, afterHGetAllCounter)
	}
}

type mRedisMockHSet struct {
	optional           bool
	mock               *RedisMock
	defaultExpectation *RedisMockHSetExpectation
	expectations       []*RedisMockHSetExpectation

	callArgs []*RedisMockHSetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RedisMockHSetExpectation specifies expectation struct of the redis.HSet
type RedisMockHSetExpectation struct {
	mock               *RedisMock
	params             *RedisMockHSetParams
	paramPtrs          *RedisMockHSetParamPtrs
	expectationOrigins RedisMockHSetExpectationOrigins
	results            *RedisMockHSetResults
	returnOrigin       string
	Counter            uint64
}

// RedisMockHSetParams contains parameters of the redis.HSet
type RedisMockHSetParams struct {
	ctx    context.Context
	key    string
	values []interface{}
}

// RedisMockHSetParamPtrs contains pointers to parameters of the redis.HSet
type RedisMockHSetParamPtrs struct {
	ctx    *context.Context
	key    *string
	values *[]interface{}
}

// RedisMockHSetResults contains results of the redis.HSet
type RedisMockHSetResults struct {
	err error
}

// RedisMockHSetOrigins contains origins of expectations of the redis.HSet
type RedisMockHSetExpectationOrigins struct {
	origin       string
	originCtx    string
	originKey    string
	originValues string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmHSet *mRedisMockHSet) Optional() *mRedisMockHSet {
	mmHSet.optional = true
	return mmHSet
}

// Expect sets up expected params for redis.HSet
func (mmHSet *mRedisMockHSet) Expect(ctx context.Context, key string, values ...interface{}) *mRedisMockHSet {
	if mmHSet.mock.funcHSet != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Set")
	}

	if mmHSet.defaultExpectation == nil {
		mmHSet.defaultExpectation = &RedisMockHSetExpectation{}
	}

	if mmHSet.defaultExpectation.paramPtrs != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by ExpectParams functions")
	}

	mmHSet.defaultExpectation.params = &RedisMockHSetParams{ctx, key, values}
	mmHSet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmHSet.expectations {
		if minimock.Equal(e.params, mmHSet.defaultExpectation.params) {
			mmHSet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmHSet.defaultExpectation.params)
		}
	}

	return mmHSet
}

// ExpectCtxParam1 sets up expected param ctx for redis.HSet
func (mmHSet *mRedisMockHSet) ExpectCtxParam1(ctx context.Context) *mRedisMockHSet {
	if mmHSet.mock.funcHSet != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Set")
	}

	if mmHSet.defaultExpectation == nil {
		mmHSet.defaultExpectation = &RedisMockHSetExpectation{}
	}

	if mmHSet.defaultExpectation.params != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Expect")
	}

	if mmHSet.defaultExpectation.paramPtrs == nil {
		mmHSet.defaultExpectation.paramPtrs = &RedisMockHSetParamPtrs{}
	}
	mmHSet.defaultExpectation.paramPtrs.ctx = &ctx
	mmHSet.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmHSet
}

// ExpectKeyParam2 sets up expected param key for redis.HSet
func (mmHSet *mRedisMockHSet) ExpectKeyParam2(key string) *mRedisMockHSet {
	if mmHSet.mock.funcHSet != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Set")
	}

	if mmHSet.defaultExpectation == nil {
		mmHSet.defaultExpectation = &RedisMockHSetExpectation{}
	}

	if mmHSet.defaultExpectation.params != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Expect")
	}

	if mmHSet.defaultExpectation.paramPtrs == nil {
		mmHSet.defaultExpectation.paramPtrs = &RedisMockHSetParamPtrs{}
	}
	mmHSet.defaultExpectation.paramPtrs.key = &key
	mmHSet.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmHSet
}

// ExpectValuesParam3 sets up expected param values for redis.HSet
func (mmHSet *mRedisMockHSet) ExpectValuesParam3(values ...interface{}) *mRedisMockHSet {
	if mmHSet.mock.funcHSet != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Set")
	}

	if mmHSet.defaultExpectation == nil {
		mmHSet.defaultExpectation = &RedisMockHSetExpectation{}
	}

	if mmHSet.defaultExpectation.params != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Expect")
	}

	if mmHSet.defaultExpectation.paramPtrs == nil {
		mmHSet.defaultExpectation.paramPtrs = &RedisMockHSetParamPtrs{}
	}
	mmHSet.defaultExpectation.paramPtrs.values = &values
	mmHSet.defaultExpectation.expectationOrigins.originValues = minimock.CallerInfo(1)

	return mmHSet
}

// Inspect accepts an inspector function that has same arguments as the redis.HSet
func (mmHSet *mRedisMockHSet) Inspect(f func(ctx context.Context, key string, values ...interface{})) *mRedisMockHSet {
	if mmHSet.mock.inspectFuncHSet != nil {
		mmHSet.mock.t.Fatalf("Inspect function is already set for RedisMock.HSet")
	}

	mmHSet.mock.inspectFuncHSet = f

	return mmHSet
}

// Return sets up results that will be returned by redis.HSet
func (mmHSet *mRedisMockHSet) Return(err error) *RedisMock {
	if mmHSet.mock.funcHSet != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Set")
	}

	if mmHSet.defaultExpectation == nil {
		mmHSet.defaultExpectation = &RedisMockHSetExpectation{mock: mmHSet.mock}
	}
	mmHSet.defaultExpectation.results = &RedisMockHSetResults{err}
	mmHSet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmHSet.mock
}

// Set uses given function f to mock the redis.HSet method
func (mmHSet *mRedisMockHSet) Set(f func(ctx context.Context, key string, values ...interface{}) (err error)) *RedisMock {
	if mmHSet.defaultExpectation != nil {
		mmHSet.mock.t.Fatalf("Default expectation is already set for the redis.HSet method")
	}

	if len(mmHSet.expectations) > 0 {
		mmHSet.mock.t.Fatalf("Some expectations are already set for the redis.HSet method")
	}

	mmHSet.mock.funcHSet = f
	mmHSet.mock.funcHSetOrigin = minimock.CallerInfo(1)
	return mmHSet.mock
}

// When sets expectation for the redis.HSet which will trigger the result defined by the following
// Then helper
func (mmHSet *mRedisMockHSet) When(ctx context.Context, key string, values ...interface{}) *RedisMockHSetExpectation {
	if mmHSet.mock.funcHSet != nil {
		mmHSet.mock.t.Fatalf("RedisMock.HSet mock is already set by Set")
	}

	expectation := &RedisMockHSetExpectation{
		mock:               mmHSet.mock,
		params:             &RedisMockHSetParams{ctx, key, values},
		expectationOrigins: RedisMockHSetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmHSet.expectations = append(mmHSet.expectations, expectation)
	return expectation
}

// Then sets up redis.HSet return parameters for the expectation previously defined by the When method
func (e *RedisMockHSetExpectation) Then(err error) *RedisMock {
	e.results = &RedisMockHSetResults{err}
	return e.mock
}

// Times sets number of times redis.HSet should be invoked
func (mmHSet *mRedisMockHSet) Times(n uint64) *mRedisMockHSet {
	if n == 0 {
		mmHSet.mock.t.Fatalf("Times of RedisMock.HSet mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmHSet.expectedInvocations, n)
	mmHSet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmHSet
}

func (mmHSet *mRedisMockHSet) invocationsDone() bool {
	if len(mmHSet.expectations) == 0 && mmHSet.defaultExpectation == nil && mmHSet.mock.funcHSet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmHSet.mock.afterHSetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmHSet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// HSet implements redis
func (mmHSet *RedisMock) HSet(ctx context.Context, key string, values ...interface{}) (err error) {
	mm_atomic.AddUint64(&mmHSet.beforeHSetCounter, 1)
	defer mm_atomic.AddUint64(&mmHSet.afterHSetCounter, 1)

	mmHSet.t.Helper()

	if mmHSet.inspectFuncHSet != nil {
		mmHSet.inspectFuncHSet(ctx, key, values...)
	}

	mm_params := RedisMockHSetParams{ctx, key, values}

	// Record call args
	mmHSet.HSetMock.mutex.Lock()
	mmHSet.HSetMock.callArgs = append(mmHSet.HSetMock.callArgs, &mm_params)
	mmHSet.HSetMock.mutex.Unlock()

	for _, e := range mmHSet.HSetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmHSet.HSetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmHSet.HSetMock.defaultExpectation.Counter, 1)
		mm_want := mmHSet.HSetMock.defaultExpectation.params
		mm_want_ptrs := mmHSet.HSetMock.defaultExpectation.paramPtrs

		mm_got := RedisMockHSetParams{ctx, key, values}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmHSet.t.Errorf("RedisMock.HSet got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHSet.HSetMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmHSet.t.Errorf("RedisMock.HSet got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHSet.HSetMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

			if mm_want_ptrs.values != nil && !minimock.Equal(*mm_want_ptrs.values, mm_got.values) {
				mmHSet.t.Errorf("RedisMock.HSet got unexpected parameter values, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHSet.HSetMock.defaultExpectation.expectationOrigins.originValues, *mm_want_ptrs.values, mm_got.values, minimock.Diff(*mm_want_ptrs.values, mm_got.values))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmHSet.t.Errorf("RedisMock.HSet got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmHSet.HSetMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmHSet.HSetMock.defaultExpectation.results
		if mm_results == nil {
			mmHSet.t.Fatal("No results are set for the RedisMock.HSet")
		}
		return (*mm_results).err
	}
	if mmHSet.funcHSet != nil {
		return mmHSet.funcHSet(ctx, key, values...)
	}
	mmHSet.t.Fatalf("Unexpected call to RedisMock.HSet. %v %v %v", ctx, key, values)
	return
}

// HSetAfterCounter returns a count of finished RedisMock.HSet invocations
func (mmHSet *RedisMock) HSetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHSet.afterHSetCounter)
}

// HSetBeforeCounter returns a count of RedisMock.HSet invocations
func (mmHSet *RedisMock) HSetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHSet.beforeHSetCounter)
}

// Calls returns a list of arguments used in each call to RedisMock.HSet.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmHSet *mRedisMockHSet) Calls() []*RedisMockHSetParams {
	mmHSet.mutex.RLock()

	argCopy := make([]*RedisMockHSetParams, len(mmHSet.callArgs))
	copy(argCopy, mmHSet.callArgs)

	mmHSet.mutex.RUnlock()

	return argCopy
}

// MinimockHSetDone returns true if the count of the HSet invocations corresponds
// the number of defined expectations
func (m *RedisMock) MinimockHSetDone() bool {
	if m.HSetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.HSetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.HSetMock.invocationsDone()
}

// MinimockHSetInspect logs each unmet expectation
func (m *RedisMock) MinimockHSetInspect() {
	for _, e := range m.HSetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RedisMock.HSet at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterHSetCounter := mm_atomic.LoadUint64(&m.afterHSetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.HSetMock.defaultExpectation != nil && afterHSetCounter < 1 {
		if m.HSetMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RedisMock.HSet at\n%s", m.HSetMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RedisMock.HSet at\n%s with params: %#v", m.HSetMock.defaultExpectation.expectationOrigins.origin, *m.HSetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcHSet != nil && afterHSetCounter < 1 {
		m.t.Errorf("Expected call to RedisMock.HSet at\n%s", m.funcHSetOrigin)
	}

	if !m.HSetMock.invocationsDone() && afterHSetCounter > 0 {
		m.t.Errorf("Expected %d calls to RedisMock.HSet at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.HSetMock.expectedInvocations), m.HSetMock.expectedInvocationsOrigin, afterHSetCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RedisMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockHDelInspect()

			m.MinimockHExistsInspect()

			m.MinimockHGetInspect()

			m.MinimockHGetAllInspect()

			m.MinimockHSetInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RedisMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RedisMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockHDelDone() &&
		m.MinimockHExistsDone() &&
		m.MinimockHGetDone() &&
		m.MinimockHGetAllDone() &&
		m.MinimockHSetDone()
}
