// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package middleware

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// AdminServiceMock implements adminService
type AdminServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcIsAdmin          func(ctx context.Context, username string) (b1 bool, err error)
	funcIsAdminOrigin    string
	inspectFuncIsAdmin   func(ctx context.Context, username string)
	afterIsAdminCounter  uint64
	beforeIsAdminCounter uint64
	IsAdminMock          mAdminServiceMockIsAdmin
}

// NewAdminServiceMock returns a mock for adminService
func NewAdminServiceMock(t minimock.Tester) *AdminServiceMock {
	m := &AdminServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.IsAdminMock = mAdminServiceMockIsAdmin{mock: m}
	m.IsAdminMock.callArgs = []*AdminServiceMockIsAdminParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAdminServiceMockIsAdmin struct {
	optional           bool
	mock               *AdminServiceMock
	defaultExpectation *AdminServiceMockIsAdminExpectation
	expectations       []*AdminServiceMockIsAdminExpectation

	callArgs []*AdminServiceMockIsAdminParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AdminServiceMockIsAdminExpectation specifies expectation struct of the adminService.IsAdmin
type AdminServiceMockIsAdminExpectation struct {
	mock               *AdminServiceMock
	params             *AdminServiceMockIsAdminParams
	paramPtrs          *AdminServiceMockIsAdminParamPtrs
	expectationOrigins AdminServiceMockIsAdminExpectationOrigins
	results            *AdminServiceMockIsAdminResults
	returnOrigin       string
	Counter            uint64
}

// AdminServiceMockIsAdminParams contains parameters of the adminService.IsAdmin
type AdminServiceMockIsAdminParams struct {
	ctx      context.Context
	username string
}

// AdminServiceMockIsAdminParamPtrs contains pointers to parameters of the adminService.IsAdmin
type AdminServiceMockIsAdminParamPtrs struct {
	ctx      *context.Context
	username *string
}

// AdminServiceMockIsAdminResults contains results of the adminService.IsAdmin
type AdminServiceMockIsAdminResults struct {
	b1  bool
	err error
}

// AdminServiceMockIsAdminOrigins contains origins of expectations of the adminService.IsAdmin
type AdminServiceMockIsAdminExpectationOrigins struct {
	origin         string
	originCtx      string
	originUsername string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmIsAdmin *mAdminServiceMockIsAdmin) Optional() *mAdminServiceMockIsAdmin {
	mmIsAdmin.optional = true
	return mmIsAdmin
}

// Expect sets up expected params for adminService.IsAdmin
func (mmIsAdmin *mAdminServiceMockIsAdmin) Expect(ctx context.Context, username string) *mAdminServiceMockIsAdmin {
	if mmIsAdmin.mock.funcIsAdmin != nil {
		mmIsAdmin.mock.t.Fatalf("AdminServiceMock.IsAdmin mock is already set by Set")
	}

	if mmIsAdmin.defaultExpectation == nil {
		mmIsAdmin.defaultExpectation = &AdminServiceMockIsAdminExpectation{}
	}

	if mmIsAdmin.defaultExpectation.paramPtrs != nil {
		mmIsAdmin.mock.t.Fatalf("AdminServiceMock.IsAdmin mock is already set by ExpectParams functions")
	}

	mmIsAdmin.defaultExpectation.params = &AdminServiceMockIsAdminParams{ctx, username}
	mmIsAdmin.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmIsAdmin.expectations {
		if minimock.Equal(e.params, mmIsAdmin.defaultExpectation.params) {
			mmIsAdmin.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmIsAdmin.defaultExpectation.params)
		}
	}

	return mmIsAdmin
}

// ExpectCtxParam1 sets up expected param ctx for adminService.IsAdmin
func (mmIsAdmin *mAdminServiceMockIsAdmin) ExpectCtxParam1(ctx context.Context) *mAdminServiceMockIsAdmin {
	if mmIsAdmin.mock.funcIsAdmin != nil {
		mmIsAdmin.mock.t.Fatalf("AdminServiceMock.IsAdmin mock is already set by Set")
	}

	if mmIsAdmin.defaultExpectation == nil {
		mmIsAdmin.defaultExpectation = &AdminServiceMockIsAdminExpectation{}
	}

	if mmIsAdmin.defaultExpectation.params != nil {
		mmIsAdmin.mock.t.Fatalf("AdminServiceMock.IsAdmin mock is already set by Expect")
	}

	if mmIsAdmin.defaultExpectation.paramPtrs == nil {
		mmIsAdmin.defaultExpectation.paramPtrs = &AdminServiceMockIsAdminParamPtrs{}
	}
	mmIsAdmin.defaultExpectation.paramPtrs.ctx = &ctx
	mmIsAdmin.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmIsAdmin
}

// ExpectUsernameParam2 sets up expected param username for adminService.IsAdmin
func (mmIsAdmin *mAdminServiceMockIsAdmin) ExpectUsernameParam2(username string) *mAdminServiceMockIsAdmin {
	if mmIsAdmin.mock.funcIsAdmin != nil {
		mmIsAdmin.mock.t.Fatalf("AdminServiceMock.IsAdmin mock is already set by Set")
	}

	if mmIsAdmin.defaultExpectation == nil {
		mmIsAdmin.defaultExpectation = &AdminServiceMockIsAdminExpectation{}
	}

	if mmIsAdmin.defaultExpectation.params != nil {
		mmIsAdmin.mock.t.Fatalf("AdminServiceMock.IsAdmin mock is already set by Expect")
	}

	if mmIsAdmin.defaultExpectation.paramPtrs == nil {
		mmIsAdmin.defaultExpectation.paramPtrs = &AdminServiceMockIsAdminParamPtrs{}
	}
	mmIsAdmin.defaultExpectation.paramPtrs.username = &username
	mmIsAdmin.defaultExpectation.expectationOrigins.originUsername = minimock.CallerInfo(1)

	return mmIsAdmin
}

// Inspect accepts an inspector function that has same arguments as the adminService.IsAdmin
func (mmIsAdmin *mAdminServiceMockIsAdmin) Inspect(f func(ctx context.Context, username string)) *mAdminServiceMockIsAdmin {
	if mmIsAdmin.mock.inspectFuncIsAdmin != nil {
		mmIsAdmin.mock.t.Fatalf("Inspect function is already set for AdminServiceMock.IsAdmin")
	}

	mmIsAdmin.mock.inspectFuncIsAdmin = f

	return mmIsAdmin
}

// Return sets up results that will be returned by adminService.IsAdmin
func (mmIsAdmin *mAdminServiceMockIsAdmin) Return(b1 bool, err error) *AdminServiceMock {
	if mmIsAdmin.mock.funcIsAdmin != nil {
		mmIsAdmin.mock.t.Fatalf("AdminServiceMock.IsAdmin mock is already set by Set")
	}

	if mmIsAdmin.defaultExpectation == nil {
		mmIsAdmin.defaultExpectation = &AdminServiceMockIsAdminExpectation{mock: mmIsAdmin.mock}
	}
	mmIsAdmin.defaultExpectation.results = &AdminServiceMockIsAdminResults{b1, err}
	mmIsAdmin.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmIsAdmin.mock
}

// Set uses given function f to mock the adminService.IsAdmin method
func (mmIsAdmin *mAdminServiceMockIsAdmin) Set(f func(ctx context.Context, username string) (b1 bool, err error)) *AdminServiceMock {
	if mmIsAdmin.defaultExpectation != nil {
		mmIsAdmin.mock.t.Fatalf("Default expectation is already set for the adminService.IsAdmin method")
	}

	if len(mmIsAdmin.expectations) > 0 {
		mmIsAdmin.mock.t.Fatalf("Some expectations are already set for the adminService.IsAdmin method")
	}

	mmIsAdmin.mock.funcIsAdmin = f
	mmIsAdmin.mock.funcIsAdminOrigin = minimock.CallerInfo(1)
	return mmIsAdmin.mock
}

// When sets expectation for the adminService.IsAdmin which will trigger the result defined by the following
// Then helper
func (mmIsAdmin *mAdminServiceMockIsAdmin) When(ctx context.Context, username string) *AdminServiceMockIsAdminExpectation {
	if mmIsAdmin.mock.funcIsAdmin != nil {
		mmIsAdmin.mock.t.Fatalf("AdminServiceMock.IsAdmin mock is already set by Set")
	}

	expectation := &AdminServiceMockIsAdminExpectation{
		mock:               mmIsAdmin.mock,
		params:             &AdminServiceMockIsAdminParams{ctx, username},
		expectationOrigins: AdminServiceMockIsAdminExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmIsAdmin.expectations = append(mmIsAdmin.expectations, expectation)
	return expectation
}

// Then sets up adminService.IsAdmin return parameters for the expectation previously defined by the When method
func (e *AdminServiceMockIsAdminExpectation) Then(b1 bool, err error) *AdminServiceMock {
	e.results = &AdminServiceMockIsAdminResults{b1, err}
	return e.mock
}

// Times sets number of times adminService.IsAdmin should be invoked
func (mmIsAdmin *mAdminServiceMockIsAdmin) Times(n uint64) *mAdminServiceMockIsAdmin {
	if n == 0 {
		mmIsAdmin.mock.t.Fatalf("Times of AdminServiceMock.IsAdmin mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmIsAdmin.expectedInvocations, n)
	mmIsAdmin.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmIsAdmin
}

func (mmIsAdmin *mAdminServiceMockIsAdmin) invocationsDone() bool {
	if len(mmIsAdmin.expectations) == 0 && mmIsAdmin.defaultExpectation == nil && mmIsAdmin.mock.funcIsAdmin == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmIsAdmin.mock.afterIsAdminCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmIsAdmin.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// IsAdmin implements adminService
func (mmIsAdmin *AdminServiceMock) IsAdmin(ctx context.Context, username string) (b1 bool, err error) {
	mm_atomic.AddUint64(&mmIsAdmin.beforeIsAdminCounter, 1)
	defer mm_atomic.AddUint64(&mmIsAdmin.afterIsAdminCounter, 1)

	mmIsAdmin.t.Helper()

	if mmIsAdmin.inspectFuncIsAdmin != nil {
		mmIsAdmin.inspectFuncIsAdmin(ctx, username)
	}

	mm_params := AdminServiceMockIsAdminParams{ctx, username}

	// Record call args
	mmIsAdmin.IsAdminMock.mutex.Lock()
	mmIsAdmin.IsAdminMock.callArgs = append(mmIsAdmin.IsAdminMock.callArgs, &mm_params)
	mmIsAdmin.IsAdminMock.mutex.Unlock()

	for _, e := range mmIsAdmin.IsAdminMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.b1, e.results.err
		}
	}

	if mmIsAdmin.IsAdminMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmIsAdmin.IsAdminMock.defaultExpectation.Counter, 1)
		mm_want := mmIsAdmin.IsAdminMock.defaultExpectation.params
		mm_want_ptrs := mmIsAdmin.IsAdminMock.defaultExpectation.paramPtrs

		mm_got := AdminServiceMockIsAdminParams{ctx, username}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmIsAdmin.t.Errorf("AdminServiceMock.IsAdmin got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmIsAdmin.IsAdminMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.username != nil && !minimock.Equal(*mm_want_ptrs.username, mm_got.username) {
				mmIsAdmin.t.Errorf("AdminServiceMock.IsAdmin got unexpected parameter username, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmIsAdmin.IsAdminMock.defaultExpectation.expectationOrigins.originUsername, *mm_want_ptrs.username, mm_got.username, minimock.Diff(*mm_want_ptrs.username, mm_got.username))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmIsAdmin.t.Errorf("AdminServiceMock.IsAdmin got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmIsAdmin.IsAdminMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmIsAdmin.IsAdminMock.defaultExpectation.results
		if mm_results == nil {
			mmIsAdmin.t.Fatal("No results are set for the AdminServiceMock.IsAdmin")
		}
		return (*mm_results).b1, (*mm_results).err
	}
	if mmIsAdmin.funcIsAdmin != nil {
		return mmIsAdmin.funcIsAdmin(ctx, username)
	}
	mmIsAdmin.t.Fatalf("Unexpected call to AdminServiceMock.IsAdmin. %v %v", ctx, username)
	return
}

// IsAdminAfterCounter returns a count of finished AdminServiceMock.IsAdmin invocations
func (mmIsAdmin *AdminServiceMock) IsAdminAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIsAdmin.afterIsAdminCounter)
}

// IsAdminBeforeCounter returns a count of AdminServiceMock.IsAdmin invocations
func (mmIsAdmin *AdminServiceMock) IsAdminBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIsAdmin.beforeIsAdminCounter)
}

// Calls returns a list of arguments used in each call to AdminServiceMock.IsAdmin.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmIsAdmin *mAdminServiceMockIsAdmin) Calls() []*AdminServiceMockIsAdminParams {
	mmIsAdmin.mutex.RLock()

	argCopy := make([]*AdminServiceMockIsAdminParams, len(mmIsAdmin.callArgs))
	copy(argCopy, mmIsAdmin.callArgs)

	mmIsAdmin.mutex.RUnlock()

	return argCopy
}

// MinimockIsAdminDone returns true if the count of the IsAdmin invocations corresponds
// the number of defined expectations
func (m *AdminServiceMock) MinimockIsAdminDone() bool {
	if m.IsAdminMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.IsAdminMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.IsAdminMock.invocationsDone()
}

// MinimockIsAdminInspect logs each unmet expectation
func (m *AdminServiceMock) MinimockIsAdminInspect() {
	for _, e := range m.IsAdminMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AdminServiceMock.IsAdmin at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterIsAdminCounter := mm_atomic.LoadUint64(&m.afterIsAdminCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.IsAdminMock.defaultExpectation != nil && afterIsAdminCounter < 1 {
		if m.IsAdminMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AdminServiceMock.IsAdmin at\n%s", m.IsAdminMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AdminServiceMock.IsAdmin at\n%s with params: %#v", m.IsAdminMock.defaultExpectation.expectationOrigins.origin, *m.IsAdminMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcIsAdmin != nil && afterIsAdminCounter < 1 {
		m.t.Errorf("Expected call to AdminServiceMock.IsAdmin at\n%s", m.funcIsAdminOrigin)
	}

	if !m.IsAdminMock.invocationsDone() && afterIsAdminCounter > 0 {
		m.t.Errorf("Expected %d calls to AdminServiceMock.IsAdmin at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.IsAdminMock.expectedInvocations), m.IsAdminMock.expectedInvocationsOrigin, afterIsAdminCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AdminServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockIsAdminInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AdminServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AdminServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockIsAdminDone()
}
